hoppscotch/hoppscotch

- script.js
Hi there,
Awesome project going on here!!!
Well, here is my first contribution (possibly of many!!!)... :smile: 
On sending a request, the response section will be expanded, incase it was closed.
It seems only natural to want to look at the response (thats kinda the entire point of this webapp), so keeping it hidden doesn't make much sense...
> Response section expands if hidden when sending a request

- script.js
Pretty self explanatory.
History is maintained across multiple sessions using the Local Storage API
> History is persisted in local storage

- index.html
- script.js
- style.css
Well, I have implemented some styling and functionality for URL validation.
To see it in action, just put in an invalid URL
If there are any Vue mistakes, please forgive, as I am a React person actually...
Also, I have added an alert popup when the Send button is clicked with an invalid URL, I am not a big fan of that, if you would like to, you could update that with something more cleaner...
> Added validation for URL

- index.html
Quick fix for https://github.com/liyasthomas/postwoman/issues/8
> fixed spelling of at least

- manifest.json
fix for "PWA not installable #19" issue
> fix for pwa install issue

- index.html
#17 Added send request on Enter Key press.
> Add send request on Enter Key press. 

- index.html
- script.js
The Clear History button clears the entire history in one click.
Functionality Implemented:
1. Clicking the button clears the history
2. The button will be disabled when there is no history to delete
> Added Clear History button

- .travis.yml
- assets/js/pwa.js
- layouts/default.vue
- layouts/error.vue
- nuxt.config.js
I think you'll need to revert the revert commits to use this with the other code, as it seems the changes were also reverted in the `migrate-nuxt` branch.
In any case, I can confirm it's working as I'm hosting it on GitHub pages myself:
https://nbtx.github.io/postwoman-vue/
> Fix GitHub Pages deployment

- assets/css/styles.scss
- pages/index.vue
> Added Copy response Button

- pages/index.vue
At the previous PR, I've relocated the new history addition code block.
But now I've seen that I've forgotten to move the `localStorage.setItem` line.
It should be fixed now.
> Last entry bug fixed.

- package.json
- pages/index.vue
Virtual scroll mechanism added for history section.
Scrolling begins to take place after five `entry` has been created.
> Virtual scroll addition for history section.

- .gitignore
- layouts/default.vue
Reverts liyasthomas/postwoman#80
> Revert "Readable GitHub logo"

- layouts/default.vue
- pages/settings.vue
- pages/websocket.vue
With increasing number of messages, the new messages are appended to the bottom and thus needs to be scrolled automatically. Also added timestamp in the log.
> Websocket log auto scroll to bottom

- components/history.vue
- pages/index.vue
* History section has been refactored into a component.
* History filtering added.
* Bug, not adding to history after failed request fixed.
* Confirm mechanism for clearing history added.
> History component added

- .editorconfig
- assets/css/styles.scss
- pages/index.vue
An implementation to resolve #94.
This PR adds the ability to being sticky to send button.
Hotkeys are not considered in this PR.
> Sticky send button

- components/history.vue
I've noticed a css bug for the history fieldset on mobile widths.
Fixed it with default `min-height`.
> History fieldset height problem on mobile.

- pages/index.vue
Fix by @guastallaigor (#109) enhanced to work in both firefox and chrome.
> Sticky send button fix enhanced

- pages/index.vue
> 😬 Actually send the request body

- assets/css/styles.scss
the button appears below the response section when scrolling down.
> fix styling issue of send again button

- .editorconfig
- .gitignore
- assets/css/styles.scss
- build.js
- layouts/default.vue
- package.json
- pages/settings.vue
- Resolves #115 (the `.editorconfig` changes) - as was suggested in the issue.
- Resolves #97 
The version name (latest git tag), hash (git short hash) and variant (the branch - if it's not master) is automatically generated at build time by `/build.js`.
It is then included in the built application and displayed in the footer.
> Add version number to footer and improves .editorconfig

- build.js
> ⚠️ Ensure build code doesn't fail if version can't be obtained from GitHub

- components/history.vue
I have tried to fix #92 please let me know if any changes are required.
> sort functionality added in history

- assets/js/curlparser.js
- build.js
- pages/index.vue
Minor code refactor to eliminate code redundancy.
> chore: minor code refactor

- pages/index.vue
clear buttons added for entire requests and for individual authentication, headers, parameters.
fixes #155
> clear buttons added

- nuxt.config.js
> Update PWA configuration

- assets/css/themes.scss
- pages/settings.vue
Added an additional theme with a fully black background for the peeps that want to live that pure AMOLED black life 😉 
The rules for the black stylesheet is similar to the dark with the --bg-dark-color brought down a pinch
> Added Black Theme

- components/autocomplete.vue
Removed multiple else if with Switch, for better readability and perfomance
> Code Refactoring

- pages/index.vue
added updated threshold and rootMargin for IntersectionObserver to avoid the flickering issue in mobile devices
will fix #157
> updated threshold and rootMargin for IntersectionObserver

- components/toggle.vue
- pages/index.vue
- pages/settings.vue
A little code refinement
In this PR I used the actual returned value from the toggle component as `$event` to apply setting changes
> Use returned value from toggle component on change event

- pages/index.vue
Tried to fix #227. Maybe there is better way but this is what I can come out off.
> Fix #227 Exclude credentials from permalink

- README.md
This PR cleans up the documentation and fixes a few typos.
> Documentation Cleanup

- pages/index.vue
**XHR**
- Enclosed value of username, password, and headers properly with quotes
- Set bearer token header as ```'Bearer <token>'```
---
**Fetch**
- Properly close final header value with quotes; ```"headerKey": "headerValue"```
- Properly close with authorization header with quotes;
```"Authorization": "Basic <value>",```
```"Authorization": "Bearer <token>",```
- Set bearer token header as ```"Bearer <token>"``` (without the Token)
- Properly enclose generated code
---
**cURL**
- Set bearer token header correctly; ```'Bearer <value>'``` (without the Token)
> Fix #269 Incorrect code generation

- pages/index.vue
Resolve issues related with duplicated query string in generated code.
> Fix #271 Duplicated query string

- README.md
- pages/index.vue
I added a download button to download the response of request.
But I stopped with some doubts, would be better to add the request url or the date of request in the filename instead of 'request' ?
Also, I need some help with editing the version, idk where and how to do it. 
[Download button image](https://imgur.com/tjSK7us)
> Add download button

- assets/css/styles.scss
- components/ace-editor.vue
- components/autocomplete.vue
- components/collections/collection.vue
- components/collections/editCollection.vue
- components/collections/editFolder.vue
- components/collections/editRequest.vue
- components/collections/folder.vue
- components/collections/index.vue
- components/collections/request.vue
- components/collections/saveRequestAs.vue
- components/history.vue
- components/section.vue
- components/toggle.vue
- functions/templating.js
- layouts/default.vue
- pages/index.vue
- pages/settings.vue
- pages/websocket.vue
> Minor UI changes

- assets/css/styles.scss
- components/collections/folder.vue
- components/collections/request.vue
- components/modal.vue
- layouts/default.vue
- pages/index.vue
Adds keyboard shortcuts to app. To see available shortcuts, Click "More" icon on top-right corner > Shortcuts.
fixes #302
> Keyboard shortcuts

- pages/graphql.vue
Follow up of #311 
https://github.com/liyasthomas/postwoman/pull/311#discussion_r348076502
> chore(refactor): switch to async/await approach

- pages/graphql.vue
Added the ability to copy the GraphQL schema shown the in the schema textfield.
> Added button to copy GraphQL schema

- Dockerfile
- docker-compose.yml
Changes made in this PR attempt to make development process more efficient when using docker. The `npm install` process will now only run when dependencies are changed. In addition a volume containing the components has been mapped to make the modifications in them behave like a "hot reload"
This PR solves #339
> Separate dockerfile layers and add volume

- pages/graphql.vue
- store/mutations.js
- store/state.js
Added support for headers in GraphQL requests.
> GraphQL Request Headers

- components/collections/folder.vue
- components/collections/index.vue
- pages/graphql.vue
- pages/index.vue
- pages/realtime.vue
- Replace all occurrences of `var` with `const`
- Self closed components. (Vue.js best practices)
- Use `Array.includes()` instead of repeated conditional checks
- Make use of directive shorthand notations for consistency (Vue.js best practices).
> refactor: minor improvements

- pages/index.vue
- pages/settings.vue
> Add Proxy URL option

- pages/graphql.vue
- store/state.js
Added ability to enter and run GraphQL queries and the ability to see their results.
> Added ability to run GraphQL queries

- lang/fr-FR.js
- nuxt.config.js
Hello again ! (#354)  Just adding french language basic to prepare the ground.
> Adding french language basic

- lang/fa-IR.js
- nuxt.config.js
Added Farsi(Persian) language support (Basic config)
> Added Farsi language support

- lang/pt-BR.js
- nuxt.config.js
There's one more task to be completed.
Please checkout this #355 as an example.
> Added Brazilian Portuguese language support

- lang/zh-CN.js
- nuxt.config.js
Add Simplified Chinese language
> Add Simplified Chinese language

- assets/css/styles.scss
- pages/index.vue
- tests/e2e/integration/app.starter.spec.js
- tests/e2e/integration/feature.url-queries.spec.js
> Custom methods support

- components/collections/saveRequestAs.vue
- package-lock.json
- pages/index.vue
This bug appeared when saving a request with no collections available.
Fixes #390
> Fixing bug on request saving

- README.md
- assets/css/styles.scss
- assets/css/themes.scss
- components/autocomplete.vue
- components/history.vue
- layouts/default.vue
- nuxt.config.js
- package-lock.json
- package.json
- pages/settings.vue
:arrow_up: Bumped dependencies
:art: Improved UI contrast
> Bumped dependencies and Improved UI contrast

- components/graphql/argument.vue
- components/graphql/field.vue
- components/graphql/type.vue
- components/graphql/typelink.vue
- pages/graphql.vue
This PR intends to add type highlighting and jump to type documentation on click of the highlighted type.
#468 
@liyasthomas please do modifiy the styling a bit, I ain't much of a designer, so I would love for it to be modified to something more pretty :smile:
> GraphQL Type Highlight and Links

- assets/js/oauth.js
Follow up of #476 
> Couple of minor tweaks that caught my eye.
> chore: Minor tweaks

- components/graphql/queryeditor.vue
- pages/graphql.vue
This PR intends to introduce Query Validation based on schema. Therefore, errors on the query (as long as there are no syntax errors) are reported by evaluating with the schema, this helps catch undefined schema field accessing.
> GraphQL query validation based on schema

- store/postwoman.js
> Validate duplicate collections

- assets/js/curlparser.ts
- assets/js/oauth.ts
- assets/js/pwa.ts
- pages/index.vue
- tsconfig.json
This PR is ./assets/js/*.js converted to * .ts.
Specifically, it is the following file.
- curlparser.ts
- oauth.ts
- pwa.ts
supplement.
How to convert to TypeScript.
If you make convert to TypeScript at once, you will have the following problems.
- Checks take a long time due to a large number of update files
- The Difference from The latest version occurs
So, I want to put out PR in detail for each directory.
> Update asset/*. js to  asset/*. ts.

- store/postwoman.js
> fix(chore): Take letter casing into account while checking for duplicate collection

- components/collections/collection.vue
- components/collections/editFolder.vue
- components/collections/editRequest.vue
- components/collections/folder.vue
- components/collections/importExportCollections.vue
- components/collections/request.vue
- components/collections/saveRequestAs.vue
- components/collections/types.ts
This PR deletes type errors and type any in `components/collections` directory.
**Supplement**  
Type refactoring work in other directories will be done in another PR.
> Refactor Type Error in Collections Dir

- lang/en-US.js
Well, pretty self explanatory.
Fixed a typo in the translation file.
> Fixed typo in translation file for Auto theme

- functions/network.js
- functions/strategies/ExtensionStrategy.js
- layouts/default.vue
> Adapt extension check to new extensions

- components/graphql/queryeditor.vue
- package-lock.json
- package.json
This PR intends to add Auto completion for the GraphQL Queries.
> GraphQL Query Autocompletion

- pages/index.vue
> Run tests even after failed request

- README.md
- components/realtime/mqtt.vue
- lang/en-US.js
- package-lock.json
- package.json
- pages/realtime.vue
Added
- `mqtt.vue` a component allows connecting to MQTT broker over Websockets.
- Added `paho-mqtt` library.
Notes:
- Used **manualDisconnect** property to check wether connection was closed intentionally. (onConnectionLost is called in all cases, connection disconnected intentionally or because of some error)
Resolve #342
> Added Support for MQTT

- pages/graphql.vue
I'm not sure about the formatting changes. I didn't stage them to the commit.
Looks like some pre-commit hook added them.
> Fix GQL introspection query not sent through extension

- components/realtime/websocket.vue
Navigate through your message history with the up and down arrows when the message input box is in focus.
> Add ability to navigate through message history

- package-lock.json
- package.json
`lint-staged` is no longer used.
https://github.com/liyasthomas/postwoman/blob/4789b76e66f473e3c0eac9c94c38884292fed743/package.json#L23
> chore(deps): remove stale dependency

- pages/settings.vue
Save collections and environments on toggling the sync options #679
> Save Collections/Environments on enabling sync

- functions/utils/valid.js
This PR intends to update the Realtime page URL validation regexes to be more lenient on its validations as the current one is catching some false negatives.
This PR fixes #873
> Make Realtime page URL validations more lenient

- components/environments/index.vue
> Fix syncing environments

- pages/index.vue
> Fixed header delete

- functions/utils/valid.js
This PR intends to fix the regex for URL validations on the Realtime page.
This PR fixes #880
> Fixed regex not validating for Realtime page for localhost URLs

- components/realtime/sse.vue
- functions/utils/contenttypes.js
- functions/utils/valid.js
- pages/index.vue
Just a small PR trying to split the work in the enormous `index.vue` file.
> Some small refactoring

- pages/graphql.vue
Pretty much self explanatory, adds a button to download the GraphQL query response JSON.
> Added ability to download GraphQL responses

- components/collections/addCollection.vue
- components/collections/collection.vue
- components/collections/editCollection.vue
- components/collections/editFolder.vue
- components/collections/editRequest.vue
- components/collections/folder.vue
- components/collections/index.vue
- components/collections/request.vue
- components/environments/editEnvironment.vue
- components/environments/environment.vue
- components/environments/index.vue
- functions/fb.js
> fix: environment and collection sync issue with firebase

- package-lock.json
- package.json
Reverts liyasthomas/postwoman#942
> Revert "⬆️ Bump nuxt from 2.12.2 to 2.13.0"

- components/realtime/log.vue
Added the ability to select text in the realtime log.
This PR intends to fix #951.
> Added ability to select text in realtime log

- pages/graphql.vue
> Fixed broken network requests in GraphQL

- components/collections/collection.vue
- components/collections/folder.vue
- components/collections/index.vue
- components/collections/request.vue
- components/layout/section.vue
- components/layout/sidenav.vue
- pages/doc.vue
- Collections section in right sidebar
- Import collection to generate documentation
> Add Collections section in Docs page

- components/lenses/renderers/mixins/TextContentRendererMixin.js
- helpers/strategies/AxiosStrategy.js
- helpers/strategies/ExtensionStrategy.js
- pages/graphql.vue
This PR tries to fix some of the bugs related to issue #994 
It mostly fixes crashes caused by the proxy error and fixes the issue with the Unexpected token during JSON parsing.
> Fix bugs with the renderer mixins

- components/ui/ace-editor.vue
- components/ui/js-editor.vue
- helpers/preRequest.js
- package.json
- pages/index.vue
This PR intends to add basic syntax linting for JavaScript code (Pre-req scripts and Test scripts) with some help from [Esprima](https://github.com/jquery/esprima).
> Basic linting for JS code

- components/realtime/socketio.vue
Add one more column to input customize path
> support user to customize the path to socket-io server

- components/collections/import-export-collections.vue
- components/environments/import-export-environment.vue
- `hoppscotch-collection.json`
- `hoppscotch-environment.json`
> chore: rename exported files

- components/collections/import-export-collections.vue
Hello everybody, 
I have created this pr in order to fix this issue #850 .
It's based on the idea mentioned by @exussum12, but instead of a space between subfolder names I have chosen -- for better clarity.
Looking forward to your feedback.
> Handle postman subfolders when importing json

- .deepsource.toml
- build.js
- components/collections/import-export-collections.vue
- components/graphql/queryeditor.vue
- components/layout/pw-header.vue
- components/settings/swatch.vue
- components/ui/ace-editor.vue
- components/ui/js-editor.vue
- components/ui/tab.vue
- components/ui/url-field.vue
- helpers/postwomanTesting.js
- layouts/default.vue
- pages/index.vue
- store/postwoman.js
This pull request fixes some of the issues raised by [DeepSource](https://deepsource.io/gh/moulik-deepsource/hoppscotch/) on my fork of this repo.
This PR also contains a .deepsource.toml, in case you want to run continuous quality analyses on your repository. If you wish to do so, you can follow these steps:
Merge this PR.
Signup on DeepSource [here](https://deepsource.io/signup/).
Activate analysis on your repo.
If you don't want to use DeepSource, I can edit the PR to remove the .deepsource.toml file.
> Fix Quality Issues using DeepSource

- helpers/codegen/codegen.js
- helpers/codegen/generators/js-axios.js
Hello hoppscotch,
I would like to add axios-js codegen.
give me your feedback
> Add: js axios codegen

- lang/id-ID.json
Add missing id translation on history component
> Add missing id translation on history component

- helpers/codegen/codegen.js
- helpers/codegen/generators/go-native.js
This PR adds codegen for requests in native Go using packages `net/http` and `net/url`. Would love feedback on this
- `helpers/codegen/codegen.js` changed
- `helpers/codegen/generators/go-native.js` added
#1190
> Add: native Go codegen

- pages/index.vue
> Fix: passing auth into codegen

- helpers/codegen/codegen.js
- helpers/codegen/generators/nodejs-request.js
- pages/index.vue
Adds NodeJs Request code generator.
#1190
> Add nodejs request codegenerator

- helpers/codegen/codegen.js
- helpers/codegen/generators/js-jQuery.js
Adds jQuery Request code generator.
#1190
> Add: JS jQuery codegen

- helpers/codegen/codegen.js
- helpers/codegen/generators/powershell.js
Adds Powershell with RestMethod code generator.
#1190
> Add: Powershell RestMethod codegen

- helpers/codegen/codegen.js
- helpers/codegen/generators/php-curl.js
* Adds PHP CURL code generator.
* Sorted Codegen List
#1190
> Add PHP CURL codegenerator

- helpers/codegen/codegen.js
- helpers/codegen/generators/python-requests.js
Add codegen for python-requests
> add codegen for python-requests

- helpers/codegen/__tests__/__snapshots__/codegen.spec.js.snap
- helpers/codegen/codegen.js
- helpers/codegen/generators/wget.js
Adds Shell with `wget` command code generator.
#1190
> Add: Shell wget codegen

- helpers/codegen/__tests__/__snapshots__/codegen.spec.js.snap
- helpers/codegen/codegen.js
- helpers/codegen/generators/cs-restsharp.js
Hi,
This PR add the code generator for C# using RestSharp as mentioned in https://github.com/hoppscotch/hoppscotch/issues/1190
Here is a sample :
Result is :
> feat:add code generator for C# RestSharp

- components/collections/collection.vue
- components/collections/folder.vue
- components/collections/index.vue
> Add search bar for collections

- helpers/codegen/__tests__/__snapshots__/codegen.spec.js.snap
- helpers/codegen/codegen.js
- helpers/codegen/generators/ruby-net-http.js
This PR adds a code generator for Ruby using the Net::HTTP standard library, as mentioned in #1190
I'm not a Rubyist myself, any feedback is welcome. Thanks!
> feat:add code generator for Ruby Net::HTTP

- helpers/codegen/__tests__/__snapshots__/codegen.spec.js.snap
- helpers/codegen/codegen.js
- helpers/codegen/generators/salesforce-apex.js
Apex wasn't mentioned in #1190 but this would be useful for my job, and I figured other people might want it too.
> Add Salesforce Apex codegen

- pages/index.vue
fixed #1257
Cant add this in the same place as the URL as you end in an infinite
loop
> Replace headers in view

- components/environments/index.vue
- pages/index.vue
fixed #1164
This takes environments called "Global" or "global" and appends them
after the current scripts.
Seems to work, but proabbly a cleaner way to acheive
> Possible solution for Global variables

- helpers/codegen/__tests__/__snapshots__/codegen.spec.js.snap
- helpers/codegen/codegen.js
- helpers/codegen/generators/shell-httpie.js
This PR adds a code generator for Shell using HTTPie, as mentioned in #1190
> feat:add code generator for Shell with HTTPie

- assets/scss/themes.scss
Hi, I found this very small font family typo and thought I'd fix it for you. Hope that's okay!
> Fix font-mono typo

- helpers/codegen/__tests__/__snapshots__/codegen.spec.js.snap
- helpers/codegen/codegen.js
- helpers/codegen/generators/java-unirest.js
> adding codegen for the java-unirest

- components/collections/save-request-as.vue
- components/layout/history.vue
- lang/en-US.json
- pages/index.vue
- store/state.js
> duplicate identifier for requests fixed

- helpers/postwomanTesting.js
- pages/index.vue
Fix for https://github.com/hoppscotch/hoppscotch/issues/1396
> #1396: Fixed assertions for toBeLevelxxx() functions

- helpers/__tests__/postwomanTesting.spec.js
- helpers/postwomanTesting.js
As discussed previously (https://github.com/hoppscotch/hoppscotch/pull/1392) , I added unit tests for the remaining test methods that weren't yet covered in postwomanTesting.spec.js.
> Unit tests for the remaining test methods

- .vscode/settings.json
- helpers/strategies/AxiosStrategy.js
- helpers/strategies/ExtensionStrategy.js
- pages/settings.vue
Updates the proxy URL from `postwoman.apollosoftware.xyz` → `hoppscotch.apollosoftware.xyz`.
> Update Proxy URL

- components/teams/add-team.vue
- components/teams/edit-team.vue
- components/teams/index.vue
- components/teams/team.vue
- lang/en-US.json
1. Added roles: OWNER, EDITOR & VIEWER.
2. Frontend checks to validate each role and selectively display edit/delete buttons.
3. Frontend checks for valid email id.
4. Frontend checks for valid team name length.
5. Feature to exit a team.
6. Frontend check to disallow the only owner to exit a team.
The hamburger icon is hidden for viewer, and only the exit button comes for editor.
> Feature: Teams new UI settings isha

- components/collections/choose-collection-type.vue
- components/collections/index.vue
**Changes:**
* Add an empty initial option for choosing teams
* Search bar shifted above collections tab
* Error on search removed (although search result is empty for now, requires a backend function)
> [Feat:Teams] Team collections tab and View team collections (2)

- components/collections/choose-collection-type.vue
- components/collections/collection.vue
- components/collections/folder.vue
- components/collections/index.vue
- components/collections/save-request-as.vue
- components/teams/index.vue
- helpers/teams/utils.js
- pages/index.vue
**Changes:**
* Created `helpers/teams/utils.js` for all utility functions related to teams.
* "Select Team" label removed from teams tab on the sidebar
* Added teams tab to sidebar
* Added a folder path parameter to show complete folder path while saving a request
**Remaining tasks:**
* Shift add,edit,delete collections and teams functions to `helpers/teams/utils.js` as well.
> Teams feature code restructure

- helpers/codegen/codegen.js
- helpers/codegen/generators/curl.js
- helpers/codegen/generators/generator.js
This PR provides the following:
- New generic Generator class to be used in ongoing refactoring for generators. (`helpers/codegen/generators/generator.js`)
- Refactoring and isolation of methods of the curl generator found in (`helpers/codegen/generators/curl.js``)
```
feat: New Generator class to serve as parent class for generators.
refactor: cURL generator.
fix: Import method used by codegen.js (New export is default and new instance of class.)
```
resolves #1550
> refactor: cURL Generator.

- components/teams/edit-team.vue
fixed the following issues
- rename team was called when the team was not even renamed
- this.name was called instead of this.$data.name
- ran prettier on the component
> fix issues with edit-team

- components/collections/collection.vue
Shift the queries to inside the component for both requests and folders
> refactor GraphQL queries in collection.vue

- components/collections/import-export-collections.vue
- components/collections/index.vue
- helpers/teams/utils.js
**Changes**
* Import from JSON into a team implemented
* Replace with JSON into a team implemented
* Import from My Collections to a team implemented
* Export team collections as JSON implemented
* Changed UI for Export Collections
> [Feat: Teams] Import from JSON and My Collections

- components/collections/collection.vue
pagination UI will appear for collections with more than 10 requests
> add pagination for requests in collection.vue

- components/collections/folder.vue
Turn queries into smart queries
> Feat/teams new UI refactor Graphql for folders component

- components/collections/folder.vue
Pagination for folders with more than 10 requests
> add pagination for requests in folder.vue

- components/teams/edit-team.vue
use smart query to fetch team members
> refactor edit-team to use smart query

- components/collections/Collection.vue
- components/collections/index.vue
- pages/doc.vue
Co-authored-by: Liyas Thomas <liyascthomas@gmail.com>
Co-authored-by: Isha Gupta <40794215+IshaGupta18@users.noreply.github.com>
Co-authored-by: IshaGupta18 <ishagupta1828@gmail.com>
> Select multiple collections (#1604)

- components/smart/AccentModePicker.vue
Simplified the capitalization of Accent Color Names by using a function for easier readability.
> Simplified the capitalization of Accent Color Names by using a function.

- assets/scss/themes.scss
- components/smart/Modal.vue
The sections in the current Black Mode is not quite visible as it's too dark. So made changes to the some of the colors in the black mode to make the sections and tab headers pop put more from the black background.
> Made changes to Black Mode to make UI elements more visible.

- components/smart/Modal.vue
Before:
https://user-images.githubusercontent.com/41614937/122031270-fc5c9f00-cde7-11eb-941b-d62c28ad691a.mp4
After: 
https://user-images.githubusercontent.com/41614937/122031335-0a122480-cde8-11eb-86a2-4819e97c34d0.mp4
> fix: modal backdrop click

- components/collections/graphql/Collection.vue
- components/collections/graphql/Folder.vue
- components/collections/graphql/Request.vue
- components/collections/graphql/index.vue
- components/collections/index.vue
- components/collections/my/Folder.vue
- components/collections/teams/Folder.vue
> fix: broken gql collection request editor

- assets/scss/styles.scss
- components/translate/SlideLeft.vue
Before:
https://user-images.githubusercontent.com/41614937/122514952-28fdfa00-d026-11eb-939e-10c4ca3483b0.mp4
After: 
https://user-images.githubusercontent.com/41614937/122514981-33b88f00-d026-11eb-9cca-8092029de6a3.mp4
> fix: janky sidebar animation

- README.md
added two flags to the docker run command to clean up the container after it has been run and also assign it a name to help manage it while it is running.
> Cleaner Docker run command

- helpers/codegen/generators/go-native.js
> refactor: fix typo in go-native.js

- helpers/oauth.js
RFC: https://datatracker.ietf.org/doc/html/rfc7636
> fix: pkce params match rfc naming convention

- CHANGELOG.md
- components/smart/JsEditor.vue
fix typo spelling grammar 
``this.initalized = true`` to ``this.initialized = true``
not included testing
> fix: typo spelling grammar

- .eslintrc.js
- helpers/fb/analytics.ts
- helpers/fb/auth.ts
- helpers/fb/collections.ts
- helpers/fb/environments.ts
- helpers/fb/history.ts
- helpers/fb/index.ts
- helpers/fb/request.ts
- helpers/fb/settings.ts
- package-lock.json
- package.json
Bump Firebase to the newly announced [v9](https://firebase.googleblog.com/2021/08/the-new-firebase-js-sdk-now-ga.html) API.
> refactor: bump firebase to v9

- components/collections/SaveRequest.vue
- helpers/types/HoppRequestSaveContext.ts
The GraphQL Request Save was partially broken due to a small typo in Save Request modal. Also, ported SaveRequest modal code to TypeScript with Composition API+Setup Script
> fix: gql request save issue (HOPP-56)

- packages/hoppscotch-app/components/environments/Environment.vue
- packages/hoppscotch-app/locales/en.json
- packages/hoppscotch-app/newstore/environments.ts
Submitted PR for feature request: #1847
> feat: add ability to copy environments

- README.md
This is my first PR for a project on public github, yay! 🥳 
Had a bit of struggle with the commitlint convention, as I didn't know this one yet - but should be fine now! Thanks in advance for review. Happy Hacktoberfest!
Refs #1852
> docs: fix broken link to .env.example in README

- packages/hoppscotch-app/components/environments/Environment.vue
feature: added ability to duplicate the global environment.
solves issue #1906.
> Allow duplication of global environment

- packages/hoppscotch-app/locales/cn.json
Keep the consistence with the Traditional Chinese translations (referred to the PR #1944, thanks for the additional translations and translation issues fixing.)
> chore(i18n): Update Simplified Chinese translations

- packages/hoppscotch-app/components/http/Authorization.vue
- packages/hoppscotch-app/helpers/utils/EffectiveURL.ts
- packages/hoppscotch-app/locales/en.json
Closes #2000  
This is the PR linked to the addition of support api-key based authentication.
Added:
> feat: (authentication) Api key based authentication [#2000]

- packages/hoppscotch-app/components/smart/EnvInput.vue
> fix: resolved #2044

- packages/hoppscotch-app/components/smart/EnvInput.vue
Chinese Pinyin input issues  simple fix #2039
I'm not sure whether it will affect other functions
> fix: chinese pinyin input - fix #2039

- packages/hoppscotch-app/assets/scss/themes.scss
- packages/hoppscotch-app/components/app/Footer.vue
- packages/hoppscotch-app/components/app/Sidenav.vue
- packages/hoppscotch-app/components/http/Authorization.vue
- packages/hoppscotch-app/components/http/Body.vue
- packages/hoppscotch-app/components/http/BodyParameters.vue
- packages/hoppscotch-app/components/http/Headers.vue
- packages/hoppscotch-app/components/http/Parameters.vue
- packages/hoppscotch-app/components/http/PreRequestScript.vue
- packages/hoppscotch-app/components/http/RawBody.vue
- packages/hoppscotch-app/components/http/Request.vue
- packages/hoppscotch-app/components/http/RequestOptions.vue
- packages/hoppscotch-app/components/http/Tests.vue
- packages/hoppscotch-app/components/http/URLEncodedParams.vue
- packages/hoppscotch-app/layouts/default.vue
- packages/hoppscotch-app/windi.config.js
Decluttered the request panel and brought the navbar to the bottom in mobile layout. 
@liyasthomas
> refactor: improve the mobile layout.

- packages/hoppscotch-app/locales/es.json
Closes # 
Minor fixed typo.
Nope.
> fix(locale): typo in the language es

- packages/hoppscotch-app/assets/icons/grip-vertical.svg
- packages/hoppscotch-app/components/graphql/RequestOptions.vue
- packages/hoppscotch-app/components/http/BodyParameters.vue
- packages/hoppscotch-app/components/http/Headers.vue
- packages/hoppscotch-app/components/http/Parameters.vue
- packages/hoppscotch-app/components/http/URLEncodedParams.vue
- packages/hoppscotch-app/components/realtime/Websocket.vue
- packages/hoppscotch-app/components/smart/EnvInput.vue
- packages/hoppscotch-app/package.json
- packages/hoppscotch-app/windi.config.js
- pnpm-lock.yaml
Closes #2174
Allow key-values entries to be drag n dropped to reorder.
Introduced [SortableJS/Vue.Draggable](https://github.com/SortableJS/vue.draggable) dependency.
> feat: reorder key-value entries

- packages/hoppscotch-cli/package.json
- pnpm-lock.yaml
Updated dependencies of hoppscotch-cli
> chore: bump hoppscotch-cli dependencies

- packages/hoppscotch-app/helpers/network.ts
- packages/hoppscotch-app/helpers/strategies/AxiosStrategy.ts
- packages/hoppscotch-app/helpers/strategies/ExtensionStrategy.ts
Closes #2275 
If we have multiple params with the request it wasn't being added with the request URL when we pass the params object. We've replaced params object with `new URLSearchParams()`
> fix: same key params are not overwritten to the last defined

- packages/hoppscotch-app/components/environments/Details.vue
- packages/hoppscotch-app/helpers/RequestRunner.ts
- packages/hoppscotch-app/newstore/environments.ts
> fix: variable typo

- packages/hoppscotch-app/helpers/curl/sub_helpers/contentParser.ts
Replace `\\"` with `"` for detection of JSON content.
> fix: curl parser json detection issues

- packages/hoppscotch-app/components/collections/ImportExport.vue
Closes hoppscotch/internal-issues#21
> fix: empty string exported when exporting team collections

- packages/hoppscotch-app/components/environments/Details.vue
Closes #2436 
This PR fixes a bug that saved the environment variables without pressing the 'save' button.
> fix: environment variables save without pressing 'save' button

- packages/hoppscotch-app/components/collections/index.vue
Disabled search button in teams collection.
> fix: disabled search in team collection

- README.md
Devs @ Google switched and rewritten the https://developers.google.com/web/ blog to https://web.dev/. 
This pull request fixes the broken PWA link.
> docs: fix PWA broken link

- packages/hoppscotch-app/languages.json
> fix: #2630

- packages/hoppscotch-app/locales/tw.json
Closes # 
1. realtime -> 即時
2. protocol -> 協定
3. In Tawian, the "計劃" is verb and "計畫" is noun. Here should use "計畫".
4. layout -> 版面
> fix: term translattion in tw.json

- .github/pull_request_template.md
> chore(PR template): fix typo

- .github/workflows/deploy-netlify.yml
Updates `actions/checkout` to `v3` in `deploy-netlify.yml`
> ci(deploy-netlify): upgrade actions/checkout to v3

- .github/workflows/codeql-analysis.yml
Updates `actions/checkout` to `v3` in `codeql-analysis.yml`
> ci(codeql-analysis): upgrade actions/checkout to v3

- .github/workflows/deploy-prod.yml
Updates `actions/checkout` to `v3` in `deploy-prod.yml`
> ci(deploy-prod): upgrade actions/checkout to v3

- .github/workflows/deploy-staging-netlify.yml
Updates `actions/checkout` to `v3` in `deploy-staging-netlify.yml`
> ci(deploy-staging-netlify): upgrade actions/checkout to v3

- .github/workflows/publish-docker.yml
Updates `actions/checkout` to `v3` in `publish-docker`
> ci(publish-docker): upgrade actions/checkout to v3

- packages/hoppscotch-app/src/components/collections/teams/Collection.vue
- packages/hoppscotch-app/src/components/collections/teams/Folder.vue
- packages/hoppscotch-app/src/components/teams/Invite.vue
> fix: fix ref access when using v-for on Invite.vue

- packages/hoppscotch-app/locales/en.json
- packages/hoppscotch-app/src/components/app/Header.vue
- packages/hoppscotch-app/src/components/profile/Picture.vue
- packages/hoppscotch-app/src/pages/profile.vue
fixes HOPPSCOTCH-APP-30
fixes #2745
> fix: fix type error when generating profile picture initials

- packages/hoppscotch-app/.env.example
- packages/hoppscotch-app/src/components/http/Request.vue
- packages/hoppscotch-app/src/components/profile/Shortcode.vue
- packages/hoppscotch-app/src/vite-envs.d.ts
This PR adds the ability to override the shortcase base URL from the env variables just like the other URLs.
> chore: allow configuration of shortcode base

- packages/hoppscotch-app/locales/id.json
> fix wrong translation and typo in Indonesia language

- packages/hoppscotch-app/src/helpers/backend/GQLClient.ts
- packages/hoppscotch-app/src/helpers/teams/TeamListAdapter.ts
fixes HOPPSCOTCH-APP-M
fixes HOPPSCOTCH-APP-3
fixes HOPPSCOTCH-APP-14
fixes HOPPSCOTCH-APP-K
fixes HOPPSCOTCH-APP-HP
fixes HOPPSCOTCH-APP-2Y
fixes HOPPSCOTCH-APP-5P
> fix: fix auth/graphql errors causing errors on logout

- packages/hoppscotch-app/src/modules/index.ts
Closes # 
import.meta.globEager is now deprecated. Use import.meta.glob('*', { eager: true }) instead.
Infomation: https://vitejs.dev/guide/migration.html#import-meta-glob
> chore: migration vite import.meta.glob

- packages/hoppscotch-app/src/composables/codemirror.ts
Description
This PR adds some temporary debug information required for HOPPSCOTCH-APP-3W and related errors.
> chore: add temporary debug info for code mirror

- packages/hoppscotch-app/locales/es.json
Closes # 
Missing Spanish translations have been added.
> feat(lang): missing translations

- packages/hoppscotch-app/src/helpers/realtime/SIOClients.ts
Fix https://github.com/hoppscotch/hoppscotch/issues/2809
> fix: socket.io v3/v4 incomming message issue

- packages/hoppscotch-app/src/components/http/RawBody.vue
- packages/hoppscotch-app/src/composables/codemirror.ts
> fix: useCodemirror getting non strings as value

- packages/hoppscotch-app/src/helpers/fb/index.ts
The firebase app_id was not configured properly. ( there was a typo in the ENV variable name ). this PR fixes this.
> fix: fix missing analytics

- packages/hoppscotch-common/src/composables/graphql.ts
**Before**
There is an infinite loop caused by two watchEffects modifying dependencies in a circular way.
1. WatchEffect#1 modifies a dependency of WatchEffect#2
2. WatchEffect#2 calls a function `expect` which modifies dependencies of WatchEffect#1
3. WatchEffect#1 runs again, and this becomes a loop
**After**
We removes this circular dependency by
1. Converting one `watchEffect` into a `watch` so we have explicit control over the reactivity, and remove tracking reactivity for `source` and `isPaused` in that watch
2. Remove `updateTicker` ref which is replaced by a function
> fix: circular watcher dependencies on invite.vue causing infinite loop

- packages/hoppscotch-common/src/components/collections/ImportExport.vue
- packages/hoppscotch-common/src/platform/index.ts
- packages/hoppscotch-web/src/main.ts
This PR introduces a temporary system to disable/enable different features in different platforms
> chore: enable/disable features in platforms

- .github/workflows/ui.yml
- packages/hoppscotch-common/src/pages/r/_id.vue
Closes HFE-106
This PR fixes the issue where the shortcode resolution screen gets stuck when the link is invalid.
> fix: shortcode resolution screen is stuck on invalid shortcodes

- packages/hoppscotch-sh-admin/src/helpers/auth.ts
> Custom location on admin redirect to base

- docker-compose.yml
- packages/hoppscotch-backend/src/errors.ts
- packages/hoppscotch-backend/src/team-environments/gql-team-env-team.guard.ts
- packages/hoppscotch-backend/src/team-environments/input-type.args.ts
- packages/hoppscotch-backend/src/team-environments/team-environments.resolver.ts
- packages/hoppscotch-backend/src/team-environments/team-environments.service.spec.ts
- packages/hoppscotch-backend/src/team-environments/team-environments.service.ts
- packages/hoppscotch-backend/src/team-environments/team.resolver.ts
Closes HBE-148
This PR introduces the Team-Environments module into the self-host project completely refactored in the pseudo-FP format.
None
> HBE-147 refactor: Introduce Team-Environments into self-host refactored to pseudo-fp format

- packages/hoppscotch-backend/src/admin/admin.service.ts
- packages/hoppscotch-backend/src/auth/auth.service.ts
- packages/hoppscotch-backend/src/mailer/mailer.service.ts
- packages/hoppscotch-backend/src/team-invitation/input-type.args.ts
- packages/hoppscotch-backend/src/team-invitation/team-invitation.resolver.ts
- packages/hoppscotch-backend/src/team-invitation/team-invitation.service.ts
- packages/hoppscotch-backend/src/team-invitation/team-invite-team-owner.guard.ts
- packages/hoppscotch-backend/src/team-invitation/team-invite-viewer.guard.ts
- packages/hoppscotch-backend/src/team-invitation/team-invitee.guard.ts
- packages/hoppscotch-backend/src/team-invitation/team-teaminvite-ext.resolver.ts
Closes HBE-152
This PR introduces code refactoring that improves the consistency of coding patterns for `team invitation` module across the other modules. Previously `team invitation` module was written in fp-ts way, and now it's being converted into pseudo fp-ts way.
Showing a general difference between fp-ts and pseudo fp-ts:
```ts
getInvitation(inviteID: string): TO.TaskOption<TeamInvitation> {
return pipe(
() =>
this.prisma.teamInvitation.findUnique({
where: {
id: inviteID,
},
}),
TO.fromTask,
TO.chain(flow(O.fromNullable, TO.fromOption)),
TO.map((x) => x as TeamInvitation),
);
}
```
```ts
async getInvitation(
inviteID: string,
): Promise<O.None | O.Some<TeamInvitation>> {
try {
const dbInvitation = await this.prisma.teamInvitation.findUniqueOrThrow({
where: {
id: inviteID,
},
}); …
```
> HBE-152 refactor: team invitation module in pseudo fp-ts

- packages/hoppscotch-backend/src/team-environments/team-environments.service.spec.ts
This PR fixes the issue in the team environments module test cases, specifically with the `createDuplicateEnvironment` method in the `team-environments.service.ts` file.
None
> fix: fixed issue in team-environment test cases

- packages/hoppscotch-common/locales/en.json
- packages/hoppscotch-common/package.json
- packages/hoppscotch-common/src/components.d.ts
- packages/hoppscotch-common/src/components/app/ContextMenu.vue
- packages/hoppscotch-common/src/components/app/Shortcuts.vue
- packages/hoppscotch-common/src/components/environments/Add.vue
- packages/hoppscotch-common/src/components/environments/Selector.vue
- packages/hoppscotch-common/src/components/environments/index.vue
- packages/hoppscotch-common/src/components/smart/EnvInput.vue
- packages/hoppscotch-common/src/composables/codemirror.ts
- packages/hoppscotch-common/src/helpers/actions.ts
- packages/hoppscotch-common/src/pages/index.vue
- packages/hoppscotch-common/src/services/context-menu/__tests__/index.spec.ts
- packages/hoppscotch-common/src/services/context-menu/index.ts
- packages/hoppscotch-common/src/services/context-menu/menu/__tests__/environment.menu.spec.ts
- packages/hoppscotch-common/src/services/context-menu/menu/__tests__/parameter.menu.spec.ts
- packages/hoppscotch-common/src/services/context-menu/menu/__tests__/url.menu.spec.ts
- packages/hoppscotch-common/src/services/context-menu/menu/environment.menu.ts
- packages/hoppscotch-common/src/services/context-menu/menu/parameter.menu.ts
- packages/hoppscotch-common/src/services/context-menu/menu/url.menu.ts
- packages/hoppscotch-ui/package.json
- pnpm-lock.yaml
Closes HP-16
This PR adds the context menu feature where a user can select any text which popups up a menu where the user will be provided with options respectively where the text is selected.
selection done in codemirror input field and response section 
- environments setting
- parameters altering in the URL input 
- URL links opening in new hoppscotch tab
> feat: context menu

- packages/hoppscotch-sh-admin/src/helpers/backend/gql/mutations/RevokeTeamInvitation.graphql
- packages/hoppscotch-sh-admin/src/pages/teams/_id.vue
Closes HBE-234
This PR updates the revoke pending team invitation mutation in the admin dashboard with a newer admin specific mutation.
> refactor: revoke team invitation in admin dashboard

- packages/hoppscotch-common/locales/en.json
- packages/hoppscotch-common/src/components/app/Header.vue
- packages/hoppscotch-common/src/pages/index.vue
- packages/hoppscotch-common/src/services/spotlight/searchers/environment.searcher.ts
- packages/hoppscotch-common/src/services/spotlight/searchers/tab.searcher.ts
- packages/hoppscotch-common/src/services/spotlight/searchers/workspace.searcher.ts
- packages/hoppscotch-ui/src/components/smart/Input.vue
This PR aims to fix spotlight issues and improve its experience
> Spotlight Issue Fixes

- packages/hoppscotch-common/locales/en.json
- packages/hoppscotch-common/src/services/context-menu/menu/parameter.menu.ts
- packages/hoppscotch-common/src/services/context-menu/menu/url.menu.ts
Closes HFE-170
This PR fixes the bugs found in the context menu feature
> fix: context menu bugs

- packages/hoppscotch-common/src/components/environments/Add.vue
- packages/hoppscotch-common/src/components/environments/Selector.vue
- packages/hoppscotch-common/src/components/environments/index.vue
- packages/hoppscotch-common/src/components/http/Headers.vue
- packages/hoppscotch-common/src/components/http/Parameters.vue
- packages/hoppscotch-common/src/components/http/Request.vue
- packages/hoppscotch-common/src/components/http/ResponseMeta.vue
- packages/hoppscotch-common/src/helpers/rest/tab.ts
- packages/hoppscotch-common/src/pages/index.vue
- packages/hoppscotch-common/src/platform/index.ts
- packages/hoppscotch-common/src/platform/inspectors.ts
- packages/hoppscotch-common/src/platform/std/inspections/__tests__/extension.inspector.spec.ts
- packages/hoppscotch-common/src/platform/std/inspections/extension.inspector.ts
- packages/hoppscotch-common/src/services/context-menu/menu/__tests__/environment.menu.spec.ts
- packages/hoppscotch-common/src/services/context-menu/menu/environment.menu.ts
- packages/hoppscotch-common/src/services/inspection/index.ts
- packages/hoppscotch-common/src/services/inspection/inspectors/__tests__/environment.inspector.spec.ts
- packages/hoppscotch-common/src/services/inspection/inspectors/__tests__/header.inspector.spec.ts
- packages/hoppscotch-common/src/services/inspection/inspectors/__tests__/response.inspector.spec.ts
- packages/hoppscotch-common/src/services/inspection/inspectors/__tests__/response.interceptor.spec.ts
- packages/hoppscotch-common/src/services/inspection/inspectors/__tests__/url.inspector.spec.ts
- packages/hoppscotch-common/src/services/inspection/inspectors/environment.inspector.ts
- packages/hoppscotch-common/src/services/inspection/inspectors/header.inspector.ts
- packages/hoppscotch-common/src/services/inspection/inspectors/response.inspector.ts
- packages/hoppscotch-common/src/services/inspection/inspectors/url.inspector.ts
- packages/hoppscotch-selfhost-web/src/main.ts
Closes HFE-154, HFE-181, HFE-182, HFE-184, HFE-169
This PR fixes the bugs found in the inspection feature
> fix: inspections bugs

- packages/hoppscotch-common/locales/tw.json
Update Traditional Chinese (Taiwan) translation for hoppscotch.
> i18n: update tw.json

- packages/hoppscotch-common/src/components/collections/index.vue
Closes #3393
This PR is a patch to fix that above mentioned bug ticket.
> fix: team collection resetting on unmount within app lifecycle

- packages/hoppscotch-common/src/components/http/Request.vue
- packages/hoppscotch-common/src/helpers/keybindings.ts
> fix: Cannot set custom method #3406

- packages/hoppscotch-common/src/composables/graphql.ts
This PR fixes memory leak issue when we open TeamInvite modal
> fix: memory leak issue on TeamInvite modal

- packages/hoppscotch-common/src/components/teams/Edit.vue
- packages/hoppscotch-common/src/components/teams/Invite.vue
The `team` can be `null` in some cases:
> fix: add optional chaining for teamMembers to handle undefined team

- packages/hoppscotch-common/src/components/graphql/Field.vue
- packages/hoppscotch-common/src/components/graphql/Sidebar.vue
- packages/hoppscotch-common/src/components/graphql/TypeLink.vue
Closes HFE-296
This PR fixes the GraphQL query deprecation highlight issue.
> fix: graphql query deprecation issue

- packages/hoppscotch-common/locales/en.json
- packages/hoppscotch-common/package.json
- packages/hoppscotch-common/src/components.d.ts
- packages/hoppscotch-common/src/components/graphql/Response.vue
- packages/hoppscotch-common/src/components/lenses/renderers/JSONLensRenderer.vue
- packages/hoppscotch-common/src/composables/lens-actions.ts
- packages/hoppscotch-common/src/helpers/utils/interfaceLanguages.ts
- packages/hoppscotch-common/src/helpers/utils/json-to-language.ts
- packages/hoppscotch-common/src/helpers/utils/languages.ts
- pnpm-lock.yaml
Closes #3551 
Added a feature to generate the interface type of JSON response into any other language.
Current behaviour:
Generated TypeScript interface:
> feat: convert json to interfaces

- packages/hoppscotch-common/src/components/app/Banner.vue
- packages/hoppscotch-common/src/components/app/Header.vue
This PR removes the unnecessary dismissible prop from Banner component
> chore: banner cleanup

- packages/hoppscotch-backend/src/errors.ts
- packages/hoppscotch-backend/src/infra-config/infra-config.service.ts
In this PR added some validation when updating any variable in InfraConfig.
Some validations are:
1. SSO secrets can not be updated with the `null` or `""` value.
2. Any SSO can not be enabled if its secret/client_id is not configured beforehand.
Nil
> hotfix: added validation on infra config update

- packages/hoppscotch-backend/src/errors.ts
Database migration message updated.
Nil
> chore: db migration missing message

- packages/hoppscotch-common/src/helpers/functional/json.ts
- packages/hoppscotch-common/src/helpers/import-export/import/hoppEnv.ts
The ability to export environments individually was added recently. This PR aims at bringing about support for importing environments individually.
Closes HFE-372.
https://github.com/hoppscotch/hoppscotch/assets/25279263/e28a6200-a46e-4305-86e1-708199af9fd0
> feat(common): support importing environments individually

- packages/hoppscotch-common/src/components/embeds/index.vue
- packages/hoppscotch-common/src/components/http/RequestOptions.vue
- packages/hoppscotch-common/src/components/share/CreateModal.vue
- packages/hoppscotch-common/src/components/share/CustomizeModal.vue
- packages/hoppscotch-common/src/components/share/Modal.vue
- packages/hoppscotch-common/src/components/share/index.vue
- packages/hoppscotch-common/src/components/share/templates/Embeds.vue
- packages/hoppscotch-common/src/helpers/shortcode/ShortcodeListAdapter.ts
- packages/hoppscotch-common/src/helpers/teams/TeamCollectionAdapter.ts
- packages/hoppscotch-common/src/newstore/collections.ts
- packages/hoppscotch-common/src/pages/e/_id.vue
Closes HFE-367
This PR fixes the bugs found in shared request feature.
- Added loading state in embeds 
- fixed i18n string when deleting a already deleted shared request
- fix shortcode subscription failing to initialize in some race condition.
> fix: bugs in shared request

- packages/hoppscotch-common/src/helpers/teams/TeamEnvironmentAdapter.ts
- packages/hoppscotch-common/src/newstore/environments.ts
- packages/hoppscotch-common/src/services/spotlight/searchers/environment.searcher.ts
Closes HFE-274
This PR adds the ability to search on team environments and switch to team environments from the spotlight.
> feat: team environment search and switch

- packages/hoppscotch-common/src/helpers/import-export/import/openapi.ts
fixes #3411
fixes HFE-388
**Changes**
* When importing from a openapi spec, we'll group the requests to folders based on the tags provided
* If no tags are provided, they'll be added to the root of the imported collection
* For each tag, a folder will be created and the requests will be added to the folder
* If a request has multiple tags, it'll be added to all the folders corresponding to the tags
for testing this PR, you can use openapi spec in this URL https://gist.githubusercontent.com/amk-dev/cc17964b48da497257502b8bf4db7e93/raw/50752cc7377602b80261370c4faf93f87c5d7626/openapi-with-tags-example
it has requests with multiple tags, single tag and no tag
> feat: use tags as folders when importing from openapi

- packages/hoppscotch-cli/src/utils/collections.ts
- packages/hoppscotch-cli/src/utils/display.ts
- packages/hoppscotch-common/src/composables/auth.ts
- packages/hoppscotch-common/src/helpers/functional/record.ts
> chore: fix some typos

- packages/hoppscotch-common/src/components/collections/Properties.vue
- packages/hoppscotch-common/src/components/collections/index.vue
- packages/hoppscotch-common/src/components/http/Headers.vue
- packages/hoppscotch-common/src/helpers/collection/collection.ts
- packages/hoppscotch-common/src/helpers/utils/EffectiveURL.ts
Closes HFE-375
This PR fixes the bugs in inherited auth-headers where the active tabs failed to update the properties, also fix type issue related to collection properties.
> fix: collection auth headers active tab update bug and type fix

- healthcheck.sh
Closes HSB-379
In this PR, we added some code to make the existing `healthcheck.sh` file to work with subpath as well.
> refactor: AIO healthcheck bash script 

- packages/hoppscotch-backend/src/errors.ts
- packages/hoppscotch-backend/src/team-collection/team-collection.controller.ts
Closes HSB-380
In this PR, we added input validation to the search route.
> chore: added input validation to search query

- packages/hoppscotch-backend/src/errors.ts
- packages/hoppscotch-backend/src/user/user.resolver.ts
- packages/hoppscotch-backend/src/user/user.service.spec.ts
- packages/hoppscotch-backend/src/user/user.service.ts
Closes HSB-381
In this PR we introduce a new mutation to allow users to update their display name in the hopscotch app.
```
mutation{
updateUserName(updatedUserName:"New Name"){
uid
displayName
email
}
}
```
> feat: added new mutation to update username in hopp app

- packages/hoppscotch-common/locales/fr.json
Updated the `packages/hoppscotch-common/locales/fr.json` file.
> i18n(fr): Updating the `packages/hoppscotch-common/locales/fr.json` file.

- packages/hoppscotch-common/locales/fr.json
> fix: french lang translation

- packages/hoppscotch-backend/nest-cli.json
Closes HSB-391
This PR has a fix for the issue with the missing handlebar files in the mailer module.
#3949
> fix: resolved mailer module email issue

- packages/hoppscotch-common/locales/en.json
- packages/hoppscotch-common/src/components/environments/my/Details.vue
- packages/hoppscotch-common/src/components/environments/teams/Details.vue
- packages/hoppscotch-common/src/components/graphql/Request.vue
- packages/hoppscotch-common/src/components/http/Request.vue
Closes HFE-484
This PR updated the REST URL placeholder to - `Enter a URL or paste a cURL command` and GraphQl URL placeholder to - `Enter a GraphQL endpoint URL`
PR also removes an extra border in the `Details.vue` component.
> chore: update placeholder text

- docker-compose.yml
- packages/hoppscotch-backend/package.json
- packages/hoppscotch-backend/src/app.module.ts
- packages/hoppscotch-backend/src/health/health.controller.ts
- packages/hoppscotch-backend/src/health/health.module.ts
- pnpm-lock.yaml
Closes HSB-436
Closes #3830 
In this PR we are adding health checks to external services used by the hopscotch backend. We introduce a new route `/health` which when called will return the status of the service in the following result.
```
{
"status": "ok",
"info": {
"database": {
"status": "up"
}
},
"error": {},
"details": {
"database": {
"status": "up"
}
}
}
```
> feat: healthcheck for external services

- packages/hoppscotch-common/locales/ru.json
> locale: update ru locale

- packages/hoppscotch-backend/Dockerfile
- prod.Dockerfile
Closes HSB-428
In this PR we are upgrading the node versions of base images to node v20.
> feat: update node version to node20-apline3.19

- packages/hoppscotch-common/src/components/app/Header.vue
- packages/hoppscotch-common/src/components/workspace/Selector.vue
- packages/hoppscotch-common/src/helpers/teams/TeamListAdapter.ts
- packages/hoppscotch-common/src/platform/index.ts
Closes HFE-507
This PR adds the UI for the workspace selector login conversion A/B testing
> chore: add workspace switcher login A/B testing flow

- packages/hoppscotch-selfhost-desktop/package.json
Closes #4091 
@hoppscotch/data was missing in selfhost-desktop package
> fix(sh-desktop): add missing @hoppscotch/data to selfhost-desktop

- docker-compose.yml
- packages/hoppscotch-backend/src/errors.ts
- packages/hoppscotch-backend/src/guards/rest-pat-auth.guard.ts
- packages/hoppscotch-backend/src/interceptors/access-token.interceptor.ts
- packages/hoppscotch-backend/src/team-collection/team-collection.service.ts
Closes # 
In this PR we are changing the status code and error messages being thrown in the `access-token.interceptor.ts` file.
> chore: changed the returned status type for errors in the access-tokens

- packages/hoppscotch-backend/src/mailer/helper.ts
Closes HSB-453
In this PR, we remove the usage of `!!` operator from `hoppscotch-backend`.
Nil
> HSB-453 hotfix: remove !! operator

- packages/hoppscotch-common/package.json
- packages/hoppscotch-common/src/components/new-collections/rest/index.vue
- packages/hoppscotch-common/src/components/workspace/Selector.vue
- packages/hoppscotch-common/src/components/workspace/TeamsWorkspaceSelector.vue
- packages/hoppscotch-common/src/helpers/backend/helpers.ts
- packages/hoppscotch-common/src/helpers/teams/TeamEnvironmentAdapter.ts
- packages/hoppscotch-common/src/helpers/teams/TeamListAdapter.ts
- packages/hoppscotch-common/src/helpers/teams/TeamsSearch.service.ts
- packages/hoppscotch-common/src/services/new-workspace/provider.ts
- packages/hoppscotch-common/src/services/new-workspace/providers/__tests__/reordering-utils.spec.ts
- packages/hoppscotch-common/src/services/new-workspace/providers/__tests__/teams.workspace.spec.ts
- packages/hoppscotch-common/src/services/new-workspace/providers/teams.workspace.ts
- packages/hoppscotch-common/src/services/new-workspace/workspace.ts
- packages/hoppscotch-common/src/services/spotlight/searchers/teamRequest.searcher.ts
- pnpm-lock.yaml
> feat: teams workspace refactor implementations

- .env.example
- docker-compose.yml
- packages/hoppscotch-backend/src/auth/helper.ts
Closes HSB-459
In this PR, we are introducing a new environment variable `ALLOW_SECURE_COOKIES` which can be used to toggle if the cookies generated by the Hoppscotch backend should be used over HTTP.
None
> feat: Ability to toggle cookies to work in HTTP

- docker-compose.yml
- packages/hoppscotch-backend/src/admin/admin.service.ts
- packages/hoppscotch-backend/src/infra-token/infra-token.controller.ts
- packages/hoppscotch-backend/src/infra-token/request-response.dto.ts
Closes HSB-477
In this PR the following were added:
- Added a new route to delete a given user. `DELETE {BASE_URL}/v1/infra/users/{uid}`
- Added 2 new fields `lastLoggedOn` and `lastActiveOn` being returned when user info is queried. 
Nil
> chore: user management api additions

- aio_run.mjs
- docker-compose.deploy.yml
- docker-compose.yml
- package.json
- packages/hoppscotch-backend/package.json
- packages/hoppscotch-backend/prod_run.mjs
- packages/hoppscotch-backend/tsconfig.build.json
- packages/hoppscotch-selfhost-web/selfhost-web.Caddyfile
- pnpm-lock.yaml
- prod.Dockerfile
This PR intends to slim down the containers (particularly the backend and hence the AIO container) and along with that move the containers to execute the servers as a non-root container user (`hoppuser`).
For the AIO container, this PR reduces the container size from 2.0GB to 501MB (as per [dive](https://github.com/wagoodman/dive) report). Similar improvements should be present in the backend container as well (from 1.9GB to 440MB) but the FE and SH Admin containers should remain the same mostly.
The size reduction is mostly achieved by removing out the existing entire monorepo copy that was present in the containers. Along with the build steps and artifacts around it. The present build artifacts also caused a lot of erroneous vulnerability reports on the container as the container had …
> refactor: slim down the backend containers

- packages/hoppscotch-backend/src/errors.ts
- packages/hoppscotch-backend/src/utils.ts
Closes HSB-482
This PR added checks to see if `DATA_ENCRYPTION_KEY` environment variable is missing from `.env` file or not.
Nil
> HSB-482 fix: add env missing checks

- packages/hoppscotch-common/locales/ru.json
> chore(lang): update ru locale #2

- packages/hoppscotch-common/src/components/accessTokens/List.vue
Closes HFE-567
This PR fixes a minor bug w.r.t to theme getting reset while navigating to profile page.
> fix: colour mode bug in profile page 

- packages/hoppscotch-common/src/components/graphql/Response.vue
- packages/hoppscotch-common/src/components/http/ResponseInterface.vue
Options added to GraphQL response to `Generate Data Schema`
> feat: graphql response schema ui

- packages/hoppscotch-cli/src/__tests__/e2e/commands/test.spec.ts
- packages/hoppscotch-common/locales/en.json
- packages/hoppscotch-common/src/components/graphql/Authorization.vue
- packages/hoppscotch-common/src/components/graphql/Headers.vue
- packages/hoppscotch-common/src/components/http/Authorization.vue
- packages/hoppscotch-common/src/components/http/authorization/AWSSign.vue
- packages/hoppscotch-common/src/components/http/authorization/OAuth2.vue
- packages/hoppscotch-common/src/helpers/graphql/connection.ts
- packages/hoppscotch-common/src/helpers/utils/EffectiveURL.ts
This PR cleans up a couple of things to AWS Signature auth type feature
> chore: AWS Signature Authorization type flow updates

- packages/hoppscotch-common/src/components/collections/ImportExport.vue
- packages/hoppscotch-common/src/components/collections/graphql/ImportExport.vue
- packages/hoppscotch-common/src/components/environments/ImportExport.vue
I noticed bug in success status message when exporting graphql collection. 
This PR is fixed this problem
> fix(status): fix import status message

- packages/hoppscotch-selfhost-desktop/src-tauri/Cargo.lock
- packages/hoppscotch-selfhost-desktop/src-tauri/Cargo.toml
- packages/hoppscotch-selfhost-desktop/src-tauri/src/interop/mod.rs
- packages/hoppscotch-selfhost-desktop/src-tauri/src/interop/startup/error.rs
- packages/hoppscotch-selfhost-desktop/src-tauri/src/interop/startup/init.rs
- packages/hoppscotch-selfhost-desktop/src-tauri/src/interop/startup/mod.rs
- packages/hoppscotch-selfhost-desktop/src-tauri/src/main.rs
- packages/hoppscotch-selfhost-desktop/src-tauri/tauri.conf.json
- packages/hoppscotch-selfhost-desktop/src/interop.ts
- packages/hoppscotch-selfhost-desktop/src/main.ts
The Hoppscotch desktop application is experiencing multiple startup-related issues:
1. A conspicuous white flash along with a lone window appearing during app initialization.
2. Delayed maximization of the app window
3. Inconsistent theme color in different theme modes
Closes #3842 #3663 
https://private-user-images.githubusercontent.com/69100154/305736648-8871aa0d-c4dc-4ef7-8ad3-325124b8fcd6.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NTk5ODgsIm5iZiI6MTcyNjY1OTY4OCwicGF0aCI6Ii82OTEwMDE1NC8zMDU3MzY2NDgtODg3MWFhMGQtYzRkYy00ZWY3LThhZDMtMzI1MTI0YjhmY2Q2Lm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyU …
> feat(desktop): faster launch with resolved desktop app startup issues

- packages/hoppscotch-common/locales/en.json
- packages/hoppscotch-common/src/components/cookies/EditCookie.vue
- packages/hoppscotch-common/src/components/graphql/Response.vue
- packages/hoppscotch-common/src/components/http/Codegen.vue
- packages/hoppscotch-common/src/components/http/ImportCurl.vue
- packages/hoppscotch-common/src/components/lenses/renderers/AudioLensRenderer.vue
- packages/hoppscotch-common/src/components/lenses/renderers/HTMLLensRenderer.vue
- packages/hoppscotch-common/src/components/lenses/renderers/ImageLensRenderer.vue
- packages/hoppscotch-common/src/components/lenses/renderers/JSONLensRenderer.vue
- packages/hoppscotch-common/src/components/lenses/renderers/PDFLensRenderer.vue
- packages/hoppscotch-common/src/components/lenses/renderers/RawLensRenderer.vue
- packages/hoppscotch-common/src/components/lenses/renderers/VideoLensRenderer.vue
- packages/hoppscotch-common/src/components/lenses/renderers/XMLLensRenderer.vue
- packages/hoppscotch-common/src/components/realtime/LogEntry.vue
- packages/hoppscotch-common/src/composables/lens-actions.ts
Closes #4265
Added name for file in all useDownloadResponse methods
Maybe we need to move file name in locale files?
> feat(filename): added filename in download functional

- packages/hoppscotch-common/locales/en.json
- packages/hoppscotch-common/package.json
- packages/hoppscotch-common/src/components/aiexperiments/MergeView.vue
- packages/hoppscotch-common/src/components/aiexperiments/ModifyBodyModal.vue
- packages/hoppscotch-common/src/components/collections/AddRequest.vue
- packages/hoppscotch-common/src/components/collections/EditRequest.vue
- packages/hoppscotch-common/src/components/collections/SaveRequest.vue
- packages/hoppscotch-common/src/components/collections/graphql/AddRequest.vue
- packages/hoppscotch-common/src/components/collections/graphql/EditRequest.vue
- packages/hoppscotch-common/src/components/http/RawBody.vue
- packages/hoppscotch-common/src/composables/ai-experiments.ts
- packages/hoppscotch-common/src/platform/experiments.ts
- pnpm-lock.yaml
**Changes**
This PR adds `hoppscotch-common` bindings for supporting
1. modifying a request body with ai
2. accepting feedbacks for our ai features
> feat: modify body with ai & feedback on ai requests hoppscotch-common bindings

- packages/hoppscotch-common/src/components/collections/Collection.vue
- packages/hoppscotch-common/src/components/collections/graphql/Collection.vue
- packages/hoppscotch-common/src/components/collections/graphql/Folder.vue
- packages/hoppscotch-common/src/components/http/RequestVariables.vue
This PR fixes the bug with Request Variable where the empty key list item was removed while switching between tabs.
The Request Variable watch have been moved up. Also unused variables have been removed.
> fix: request variable list item remove bug

- packages/hoppscotch-common/locales/en.json
- packages/hoppscotch-common/src/components/http/TestResult.vue
- packages/hoppscotch-common/src/helpers/import-export/export/testResults.ts
Closes #4328 
Add a button next to test results to export the test results as a JSON file.
Added a share icon next to trash icon in the test results tray.
Added a new file to export the test Results to a json.
> feat: add button to export test results as json

- packages/hoppscotch-common/src/components/http/BodyParameters.vue
**Changes**
This PR adds autocomplete for multipart/formdata individual content types.
> feat: add autocomplete for multipart/formdata individual content types

- packages/hoppscotch-backend/src/auth/strategies/microsoft.strategy.ts
Closes # 
update Microsoft strategy to handle multiple scopes
> feat(backend): update Microsoft strategy to handle multiple scopes

- packages/hoppscotch-common/locales/en.json
- packages/hoppscotch-common/src/components/history/index.vue
- packages/hoppscotch-common/src/platform/history.ts
- packages/hoppscotch-common/src/services/spotlight/searchers/__tests__/history.searcher.spec.ts
- packages/hoppscotch-common/src/services/spotlight/searchers/history.searcher.ts
- packages/hoppscotch-selfhost-desktop/src/api/queries/IsUserHistoryEnabled.graphql
- packages/hoppscotch-selfhost-desktop/src/api/subscriptions/UserHistoryAllDeleted.graphql
- packages/hoppscotch-selfhost-desktop/src/api/subscriptions/UserHistoryStoreStatusChanged.graphql
- packages/hoppscotch-selfhost-desktop/src/platform/history/history.api.ts
- packages/hoppscotch-selfhost-desktop/src/platform/history/history.platform.ts
- packages/hoppscotch-selfhost-web/src/api/queries/GetUserHistoryStore.graphql
- packages/hoppscotch-selfhost-web/src/api/queries/IsUserHistoryEnabled.graphql
- packages/hoppscotch-selfhost-web/src/api/subscriptions/UserHistoryAllDeleted.graphql
- packages/hoppscotch-selfhost-web/src/api/subscriptions/UserHistoryStoreStatusChanged.graphql
- packages/hoppscotch-selfhost-web/src/platform/history/history.api.ts
- packages/hoppscotch-selfhost-web/src/platform/history/history.platform.ts
- packages/hoppscotch-selfhost-web/src/platform/history/history.sync.ts
- packages/hoppscotch-sh-admin/locales/en.json
- packages/hoppscotch-sh-admin/src/components/settings/Configurations.vue
- packages/hoppscotch-sh-admin/src/components/settings/HistoryConfiguration.vue
- packages/hoppscotch-sh-admin/src/components/settings/ServerRestart.vue
- packages/hoppscotch-sh-admin/src/composables/useConfigHandler.ts
- packages/hoppscotch-sh-admin/src/helpers/backend/gql/mutations/RevokeAllUserHistoryByAdmin.graphql
- packages/hoppscotch-sh-admin/src/helpers/backend/gql/mutations/ToggleUserHistoryStore.graphql
- packages/hoppscotch-sh-admin/src/helpers/configs.ts
FIXS HFE-677,HFE-678
This PR introduces 
- the ability to toggle storing sent request history from admin panel
- platform defs & UI changes to support this toggling on the app
> feat: disable tracking request history

- packages/hoppscotch-common/locales/en.json
- packages/hoppscotch-common/src/components/http/test/RunnerModal.vue
This PR adds a loading state in the collection runner modal and enables the CLI tab for personal collection with a warning prompt saying 'Collection Runner for Personal Collection in CLI is coming soon.'
> chore: run collection modal updates

- packages/hoppscotch-common/src/components/http/BodyParameters.vue
- packages/hoppscotch-common/src/components/http/URLEncodedParams.vue
- packages/hoppscotch-common/src/newstore/settings.ts
- packages/hoppscotch-common/src/services/persistence/validation-schemas/index.ts
- packages/hoppscotch-data/src/rest/index.ts
- packages/hoppscotch-data/src/rest/v/10.ts
Fixs HFE-668
**Changes**
* Adds bulk editing to multipart/formdata
* Fixs the existing implementation for url encoded body, as it was broken
> feat: add bulk edit to multipart/form data and fix url encoded form bulk edit

- package.json
- pnpm-lock.yaml
- prod.Dockerfile
This PR resolves critical and high vulnerabilities for `cross-spawn` npm packages.
Nil
> chore: resolve Docker image vulnerabilities associated with `cross-spawn`

- packages/hoppscotch-common/locales/en.json
- packages/hoppscotch-common/src/components.d.ts
- packages/hoppscotch-common/src/components/aiexperiments/ModifyPreRequestModal.vue
- packages/hoppscotch-common/src/components/aiexperiments/ModifyTestScriptModal.vue
- packages/hoppscotch-common/src/components/http/PreRequestScript.vue
- packages/hoppscotch-common/src/components/http/Tests.vue
- packages/hoppscotch-common/src/composables/ai-experiments.ts
- packages/hoppscotch-common/src/platform/experiments.ts
Implements the accompanying front end changes to integrate https://github.com/hoppscotch/hoppscotch-backend/pull/133
What's changed
added modify with AI button to generate pre request and test scripts
related : https://github.com/hoppscotch/central/pull/88
> [HCB-148] feat: UI for testscript generation ( ai experiments )

- packages/hoppscotch-common/locales/en.json
- packages/hoppscotch-common/src/composables/ai-experiments.ts
- packages/hoppscotch-common/src/newstore/settings.ts
- packages/hoppscotch-common/src/pages/settings.vue
- packages/hoppscotch-common/src/services/persistence/validation-schemas/index.ts
added support for user to specify detailed instructions for request rename in settings
depends on : https://github.com/hoppscotch/hoppscotch-backend/pull/150
> feat(ai-exp): add support for custom request naming scheme

- packages/hoppscotch-common/locales/en.json
This PR updates collection import string for activity logs.
> chore(common): updated collection import string for activity logs

- packages/hoppscotch-selfhost-desktop/vite.config.ts
Closes #4503
I ran into a similar problem described in #4503. However, I noticed that this error does not occur in the web version. After investigating the issue, my fix solved the problem.
> fix(qs-alias): add alias for querystring

- packages/hoppscotch-common/src/helpers/import-export/import/openapi.ts
Closes #4688
I added an optional chaining operator to detect the existence of the first element in the array
> fix: import openapi file servers url detection

- packages/hoppscotch-common/src/components/graphql/Request.vue
- packages/hoppscotch-common/src/components/graphql/RequestOptions.vue
- packages/hoppscotch-common/src/helpers/graphql/connection.ts
Closes HFE-749 #4727
This pull request addresses an issue with the GraphQL connection not sending the necessary authentication headers.
> fix: ensure GraphQL connection sends authentication headers

- packages/hoppscotch-selfhost-web/webapp-server/src/bundle/model.rs
- packages/hoppscotch-selfhost-web/webapp-server/src/config.rs
> chore: bump version in webapp server

- packages/hoppscotch-agent/package.json
- packages/hoppscotch-agent/src/App.vue
- packages/hoppscotch-agent/vite.config.ts
- pnpm-lock.yaml
This PR fixes typescript build warning during agent's build process.
> fix(agent): typescript build warnings

- packages/hoppscotch-kernel/src/relay/impl/web/v/1.ts
Closes #4808 
This PR fixes the issue where the environment variable was not getting parsed while using with authorization. 
Double auth processing was happening one in EffectiveURL and other one in relay, but it was done without the parsed auth value, so the code has been temporarily commented out, till a effective way is implemented.
> fix: environment variable not working on auth

- .github/ISSUE_TEMPLATE/--bug-report.yaml
This PR updates bug report template to ask for additional information.
> docs: more detailed bug report template

- packages/hoppscotch-desktop/src/utils/updater.ts
This PR increases timeout for checking updates, mainly for slower internet connections. In most cases the update check returns almost immediately.
It also increases the fallback promise timeout to make sure there's indeed an issue with `check` and not a tie or other inconsistencies in the promise race.
You can test this out by connecting via slower network or network with major packet loss, sometimes the update check would fail and the app will continue with loading the main app.
Although even in that case it will work after a couple of restarts, so the worst case scenario is a delayed update.
> feat(desktop): update check timeout 2s -> 5s

- docker-compose.yml
This PR fixes missing service dependencies in `docker-compose.yml` file.
> fix(infra): docker compose service dependencies

- packages/hoppscotch-kernel/src/relay/v/1.ts
Closes HFE-777.
This PR fixes transformation for `application/x-www-form-urlencoded` `content` parameter mainly affecting `Extension` interceptor.
You can use attached collection to test out OAuth2.0 flows hosted by https://oauth.tools/
[OAuth Test Collection.json](https://github.com/user-attachments/files/19226596/OAuth.Test.Collection.json)
> fix(kernel): pre-req transformers for backcompat

- packages/hoppscotch-common/src/helpers/functional/domain-settings.ts
This PR fixes essentially an `&&` op on certs domain settings to `||`.
| ------ | ------|
| ![Before](https://github.com/user-attachments/assets/61e2a130-fd96-4430-84bf-16db5da9c401) | ![After](https://github.com/user-attachments/assets/0e48b8c8-4214-4218-a991-c2882b5becd4) |
When you set CA certificates for `Native` interceptor in the domain settings section
| Step 1 | Step 2 | Step 3 |
| ------ | ------ | ------ |
| Set CA certificates | Remove any client certificates | Try sending a request to untrusted server (which would be trusted by the CA cert). Notice CA cert is missing from `security` object |
| ![CA Certs](https://github.com/user-attachments/assets/d869e211-b14f-4ad5-87b3-8e67c2a287b2) | ![Client Certs …
> fix(desktop): fix missing ca certs when client certs are not present

- packages/hoppscotch-common/locales/en.json
- packages/hoppscotch-common/src/components/environments/Selector.vue
- packages/hoppscotch-common/src/components/environments/my/index.vue
- packages/hoppscotch-common/src/components/environments/teams/index.vue
- packages/hoppscotch-common/src/components/smart/EnvInput.vue
Closes HP-355 #4758 
This PR add's the feature to search environments in the selector and sidebar
Add's the feature to search environments from environment selector and environments section in sidebar
> feat: add search in environment selector and sidebar

- packages/hoppscotch-common/locales/tw.json
Update Traditional Chinese (Taiwan) translation for hoppscotch.
> chore(i18n): update tw translation

- README.md
Adding links to Desktop apps in the Readme, this will help a lot of users !!
> docs: link to the Desktop App

- packages/hoppscotch-common/src/components/http/Codegen.vue
- packages/hoppscotch-selfhost-desktop/src/platform/environments/environments.platform.ts
This PR add's the environment version migration while syncing at platform level and fixes the codegen bug not showing environment value
> fix: desktop platform level env migration and codegen bug

- packages/hoppscotch-common/locales/en.json
- packages/hoppscotch-common/src/components/app/SpotlightSearch.vue
Closes HFE-902
This PR removes the animations on the spotlight input and update the placeholder.
> chore: remove spotlight animation

- packages/hoppscotch-common/src/components/http/Headers.vue
- packages/hoppscotch-common/src/components/importExport/ImportExportSteps/UrlImport.vue
- packages/hoppscotch-common/src/helpers/auth/auth-types.ts
- packages/hoppscotch-common/src/helpers/auth/types/aws-signature.ts
- packages/hoppscotch-common/src/helpers/auth/types/jwt.ts
- packages/hoppscotch-common/src/helpers/utils/EffectiveURL.ts
Address linting issues by refining code structure and removing unnecessary parameters in function calls. This improves code readability and maintains consistency across the codebase.
> chore(common): fixes lint errors and clean up code

- packages/hoppscotch-sh-admin/locales/en.json
- packages/hoppscotch-sh-admin/src/components/onboarding/AuthSetup.vue
- packages/hoppscotch-sh-admin/src/components/onboarding/CompleteScreen.vue
- packages/hoppscotch-sh-admin/src/components/onboarding/SmtpSetup.vue
- packages/hoppscotch-sh-admin/src/components/onboarding/WelcomeScreen.vue
- packages/hoppscotch-sh-admin/src/composables/useOnboardingConfigHandler.ts
- packages/hoppscotch-sh-admin/src/modules/admin.ts
- packages/hoppscotch-sh-admin/src/pages/onboarding.vue
This PR add's i18n strings to the new onboarding flow in the sh-admin and minor cleanup
> chore: add i18n for onboarding flow and cleanup

- package.json
This pull request makes a minor update to the `package.json` file, specifically upgrading a transitive dependency to address compatibility or security concerns.
* Upgraded the `ws` package used by `subscriptions-transport-ws` from version 5.2.4 to 6.2.3 in the `resolutions` field of `package.json`.
Nil
> chore: update ws dependency for subscriptions-transport-ws
