package.json

For some reason `http-server` has a default cache header of 1 hour. That isn't very useful in dev mode. This disables that.

Disable dev server cache

---

script.js

If the XHR request fails, show a simple error message.
Test URL `https://api.twitter.com`

Display error message

---

manifest.json

Otherwise it will install `https://liyasthomas.github.io/`.

start_url should be project directory

---

index.html
script.js

User can choose Bearer Token authentication type to access apis protected with access/id token.

Added token based authentication type

---

assets/css/styles.scss
pages/index.vue

Issue #46 's request is fullfilled by adding a computed property to check after `response` changes to determine which category is the `response`.
Categories are implemented from [Http Status Code](https://www.tutorialrepublic.com/html-reference/http-status-codes.php).

Response status colors added.

---

assets/css/styles.scss
pages/index.vue

Resolves #41 - adds an HTML preview toggle-able with the 'Preview HTML' / 'Hide Preview' button in the bottom right of the response area.
When 'Preview HTML' is clicked, the HTML source is covered by a preview of the rendered HTML.
This button only shows when content type is HTML and a response has been submitted.
As always, you can test the changes here: https://nbtx.github.io/postwoman-vue/

Adds HTML preview.

---

.editorconfig
.gitignore

- Added .editorconfig. I chose 2 space indentations to keep it in line with StandardJS.
- Removed .editorconfig from .gitignore

Add editorconfig

---

README.md

Just fixing a single typo, as I assume the sentence should read:
>  Low RAM/memory and CPU usage

Fix typo "CUP" to "CPU" in readme

---

pages/index.vue

I think this is maybe related to #29. 
It enable shareable requests using query parameters in the url. Examples:
[/url=https://api.thecatapi.com&path=/v1/images/search](https://yubathom.github.io/postwoman/?url=https://api.thecatapi.com&path=/v1/images/search)
[/method=POST](https://yubathom.github.io/postwoman/?method=POST
)
[/method=PUT&contentType=/?method=PUT&contentType=www-form/urlencoded](https://yubathom.github.io/postwoman/?method=PUT&contentType=www-form/urlencoded)
it can be applied to the other items of `data` of the `pages/index` component. 
Maybe would be simpler to store theese settings (that could be stored in the router) in a collection than a encoding/decodign static files.

Enable shareable requests with parameters in url queries

---

pages/index.vue

In my opinion something is wrong right now with the button fixed, using the Intersection API (ref #107 #94). At my environment, it only works on the first scroll and every two full page scrolls after that.
This PR changes the logic a bit to make it work all the time.
**Right now:**
**After this PR:**

Fix intersection button send

---

directives/textareaAutoHeight.js
pages/index.vue

Auto resizing for textareas (auto resized the `min-height`, not the user specified height) added via `textareaAutoResizer` directive. (ref #102)
Didn't use an external library for this process. It seemed like a simple directive would suffice.

Auto resize textareas

---

pages/index.vue

* Enable uri with preseted headers, params and body. Examples:
- <a href="https://yubathom.github.io/postwoman/?headers=%5B%7B%22key%22%3A%22foo%22,%20%22value%22%3A%22bar%22%7D%5D">/?headers=[{"key":"foo", "value":"bar"}]
- <a href="https://yubathom.github.io/postwoman/?params=%5B%7B%22key%22%3A%22foo%22,%20%22value%22%3A%22bar%22%7D%5D">/?params=[{"key":"foo", "value":"bar"}]
- <a href="https://yubathom.github.io/postwoman/?method=POST&bodyParams=%5B%7B%22key%22%3A%22foo%22,%20%22value%22%3A%22bar%22%7D%5D">/?method=POST&bodyParams=[{"key":"foo", "value":"bar"}]</a>
or combined with other params like:
[/?method=POST&auth=Basic&httpUser=someUser&httpPassword=somePass](https://yubathom.github.io/postwoman/?method=POST&url=https%3A%2F%2Freqres.in&path=%2Fapi%2Fusers&auth=Basic&httpUser=some …

Bind history state and query params of requests

---

assets/css/themes.scss
components/autocomplete.vue
package-lock.json
package.json
pages/index.vue

Test URL: https://nbtx.github.io/postwoman-vue/
---
This PR:
- adds a custom autocomplete searchbox (see GIF).
- automatically turns off the 'raw input' feature when a known content type is entered.
- allows for easily defining `knownContentTypes` and `validContentTypes` (see `index.vue`).
- renames `www-urlencoded` to its proper name `application/x-www-form-urlencoded`
- Resolves #88 
- Resolves #99

⌨️Add autocomplete widget with command line completion

---

components/history.vue

Small minor improvement. Right now I can click on the clear history even if there aren't any histories there. This PR should fix this.
**Issue:**

Clear history is now disabled when there aren't any histories

---

README.md
middleware/README.md
middleware/parsedefaulturl.js
pages/index.vue

Issue - ideally the default url expected is '/' to highlight the 'Http' menu option but in PWA's case the url passed is '/?standalone=true' to indicate and load it as an app where 'standalone=true' is automatically appended by the rendering browser engine 
Solution - newly added middleware 'parsedefaulturl.js' would intercept the request before loading the default page and redirect appropriately as desired

update with PR for issue/bug #100

---

pages/index.vue

Enable raw input binding to the url. Raw inputs are now shareable. Example:
[/?method=PUT&rawParams={"foo":"bar","col":[1,2,3]}](https://yubathom.github.io/postwoman/?method=PUT&rawParams=%7B%0A%22foo%22%3A%22bar%22,%0A%22col%22%3A%5B1,2,3%5D%0A%7D)

Bind raw body input to url of requests

---

layouts/default.vue

Linkification of the footer version and commit sha. Warning, idk Vue.js. 🤔 
Resolves https://github.com/liyasthomas/postwoman/issues/134

Linkify footer version and commit sha

---

pages/index.vue

Update url at keyup at key-value params (bodyParams and headers) and bodyParam/rawParam at toggle state changes.
Fix [this](https://github.com/liyasthomas/postwoman/pull/118#issuecomment-527864188):
> 
> 
> @yubathom I've found an issue. Raw parameters are binded to URL automatically whereas key-value params are only binded to URL on adding another key-value pair. And when switching from raw parameters to key-value and vice versa, parameters are only binded after a change in input. Check on your free time.
This PR is related to #29.
And is an update of #72, #118 and #131 .

Update url at keyup and at bodyParam/rawParam toggle state changes

---

pages/index.vue

Post request headers were not properly parsed. I've checked on my local server it was sending `[Object, Object]`.

Post request headers issue resolved

---

pages/index.vue

Fixed bug where hal+json responses are not rendered properly

---

nuxt.config.js

hostname is mandatory on spa mode

🐛 Fixed sitemap configuration

---

assets/css/themes.scss
pages/settings.vue

This PR adds an automatic theme which uses the `prefers-color-scheme` media query to automatically go to dark mode or be in light mode respecting the user's system's norms (like Android and iOS dark modes, Windows/macOS dark modes (some change based on time of day)).
Now, I do kinda feel auto to be a good candidate for being the default theme, since it integrates more with the system preference. So if this can be replaced from dark as the default, please feel free to add to my commit.

Added auto theme

---

pages/index.vue

This fixes an issue where the generated code for Javascript XHR and Fetch are missing quotation marks preventing the user from easily coping and pasting the code.

Add quotation marks for generated code

---

.travis.yml
cypress.json
package-lock.json
package.json
tests/e2e/fixtures/catapi.json
tests/e2e/integration/app.starter.spec.js
tests/e2e/integration/feature.url-queries.spec.js
tests/e2e/support/commands.js
tests/e2e/support/index.js

Related to #65.
preview of `npm run dev:e2e`
this should be running in ci too - https://travis-ci.org/yubathom/postwoman/builds/593324131
at `before_scripts`
wich should give some reports at every pull requests
* `npm run tests` - run tests once in cli mode. Now just these e2e. In future we should run unit tests too.  
* `npm run dev:e2e`- will start localhos:3000 and run e2e tests within cypress app browser. This is the default mode to tdd. 
- I'm not mounting and testing the docker container. Just testing the dev server (`run dev`) mounted at the travis-ci. 
- Though would be a better approach (running on docker) the dev server is the same enviroment that is deploying the front end. So I think this should be enough right now.
- [Cypress](https://www.cypress.io/) is awesome and we can …

Add basic e2e tests

---

components/history.vue
pages/index.vue

This pull request is based on issue #133 
I've added a field to Enter the request name for each request. Please find the screenshot below - 
Ideally, the same request name should be listed down in the History section of the request. The changes are also made in the corresponding files.

Add Request name label for every requests

---

nuxt.config.js
pages/index.vue
pages/settings.vue
proxy/index.js

In this PR I used  Nuxtjs serverMiddleware to create a proxy server and pass the requests through the proxy and get over CORS and mixed-content issue's
resolving https://github.com/liyasthomas/postwoman/issues/175 and https://github.com/liyasthomas/postwoman/issues/2

Fix CORS and mixed content issue

---

assets/js/curlparser.js

Array destructuring makes the respective code snippet much concise.

chore: minor code refactor

---

layouts/default.vue
pages/index.vue
store/postwoman.js

This re-orders the sections as follows:
- Request
- *Code* (when made visible)
- Request Options (Authentication / Headers / Parameters)
- Response
- Collections
- History
Additionally, this adds a toggle to the Authentication section (the value of which is saved) that allows a user to toggle whether or not they want the authentication information in the URL.
_Authentication in the URL is also now turned **off** by default for security reasons._
Closes https://github.com/liyasthomas/postwoman/issues/178

Re-order sections and add toggle for including authentication in URL

---

components/section.vue
pages/settings.vue
store/postwoman.js

There ~is~ was a bug on frame colors toggle. When you click once the toggle changes.
- Change the setting name to `FRAME_COLORS_ENABLED` to match the pattern and improve readability
- Using `toggleSetting` method for toggle components
To reproduce this bug, just open https://postwoman.io/settings and try to toggle Multi-Color in Frames section
fixed: https://www.loom.com/share/bd598afe32b44cb583fed608ccb50584

Fixed frame colors toggle

---

assets/css/styles.scss

A very simple tweak; by making the pages a minimum height of 100vh, it makes the app feel smoother as the footer can be scrolled into view on any page and the app does not 'jump' in height when pages are changed.

Make page changes more fluid

---

components/collections/editCollection.vue
components/collections/editFolder.vue
components/collections/editRequest.vue
components/collections/saveRequestAs.vue

It bugged me that I had to hit the save button for collections, requests etc manually with the mouse, so I quickly added the correct event handler for the enter key.

Enhancement: make saving of collections, requests, folder more convenient

---

pages/graphql.vue
store/mutations.js
store/state.js

* A section for GraphQL related fields is added to the global store
* A new reducer `setGQLState` is added to the global store for updating the GQL store
* GraphQL endpoint field is now persisted through the GQL store

GraphQL endpoint field is now persisted

---

pages/graphql.vue

Pretty much explained by the title. :stuck_out_tongue:

GraphQL introspection requests now support and respect proxying

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

Improved the readability of CODE_OF_CONDUCT.md and CONTRIBUTING.md.
For CONTRIBUTING.md.
First change just improved grammar.
Second change, made sentence into two as there were two 'ands' used.
Third change, making it more clear who's code of conduct it is.
For CODE_OF_CONDUCT.md
First change, made sentence into two as there were two 'ands' used.
Second change, making it more clear who's code of conduct it is.

Minor text improvements

---

pages/graphql.vue
pages/index.vue

Added the ability to undo header/param/body param deletion.
NOTE : Because toasts are for some reason not appearing in `index.vue`, I haven't tested the code used in that page, but it works in the GraphQL page. I am working really late, so I might have made some mistakes, reviewers, please do check :stuck_out_tongue:

Undo header/param/body param deletion

---

layouts/default.vue

Added the missing shortcuts to query and response panels for GraphQL in the navbar.
Along with that, I updated the icons for the endpoint and schema shortcuts to something which made more sense to me (feel free to edit that out, I am pretty sleep deprived and my eyes maybe deceiving me :sweat_smile: )

Added nav shortcuts to GraphQL query and response, updated GraphQL shortcut icons

---

nuxt.config.js

According my todays tweet (https://twitter.com/daviddalbusco/status/1200671798708391937?s=20) it seems that the image provided in the meta tag `twitter:image` respectively `./logo.jpg` wasn't interpreted by Twitter.
For DeckDeckGo I use absolute URL and I double checked DEV.to, which also use absolute.
Therefore I think that the image might need to be provide in such form respectively `https://postwoman.io/logo.jpg`
P.S.: I didn't modified the `og:image` because I quickly tested Facebook and it seems they are fine with a relative path

fix: twitter summary card image url

---

components/ace-editor.vue
pages/graphql.vue
pages/index.vue

Added two way data binding features (v-model) to the Ace Editor component.
Along with that, updated the GraphQL Query Field and the Pre-Request Script field to use this two-way binding supported Ace Editor.
This PR fixes #235 .
( alright, imma gonna sleep now :sweat_smile: )

Two Way Data Binding (v-model) to Ace Editor component

---

components/collections/collection.vue
components/collections/editCollection.vue
components/collections/editFolder.vue
components/collections/folder.vue
components/collections/index.vue
components/collections/saveRequestAs.vue
layouts/default.vue
pages/index.vue

- Self closing components.
- Use directive short-hands across the code-base for consistency.

chore: stick to Vue.js best practices

---

lang/de-DE.js
lang/en-US.js
lang/es-ES.js
lang/fa-IR.js
lang/fr-FR.js
lang/id-ID.js
lang/ja-JP.js
lang/pt-BR.js
lang/tr-TR.js
lang/zh-CN.js
package-lock.json
pages/graphql.vue
store/mutations.js
store/state.js

Added the ability to add variables for queries.
E.g. if you do the following query:
```gql
query MySearch($limit: Int, $where: JSON) {
nodes(limit: $limit, where: $where) {
id
title
}
}
```
You can now add the variables `$limit` and `$where`.
There is still one problem which requires discussion:
The type validation of variables is required. So if it's an `Int` it needs to be converted. I've done it with a regex for now, but apollo-client would do better with this. I wasn't really sure if I should introduce a new dependency or not.

Added variables to graphql page.

---

functions/network.js
functions/strategies/AxiosStrategy.js
functions/strategies/FirefoxStrategy.js
functions/strategies/ProxyStrategy.js

This PR intends to introduce compatibility with [Postwoman Firefox Extension](https://addons.mozilla.org/en-US/firefox/addon/postwoman/)
This adds a new NetworkStrategy to hook with the Firefox Content Script to run the query.
Do NOT use the extension from the store to test the strategy, because, the extension is configured to only hook into the postwoman.io and postwoman.netlify.com domains. Other domains won't get hooked and hence won't get access to the extension hooks.
So, to test this PR, you have to clone the [postwoman-firefox](https://github.com/AndrewBastin/postwoman-firefox) repo.
Then head into the `manifest.json` file and edit it to match this snippet below
```
"content_scripts": [
{
"matches": [
"*://*/*",
"https://postwoman.io/",
"https://postwoman.io/*", …
```

Firefox Extension compatibility

---

pages/graphql.vue

This fixes the issue with null string type variables, as described in #497

💚 Fixed #497

---

README.md
functions/network.js
functions/strategies/ChromeStrategy.js
functions/strategies/FirefoxStrategy.js
layouts/default.vue

This PR intends to introduce compatibility with [Postwoman Chrome Extension](https://chrome.google.com/webstore/detail/postwoman-extension-for-c/amknoiejhlmhancpahfcfcfhllgkpbld)
This adds a new NetworkStrategy to hook with the Chrome Content Script and Background Script to run the query.
Do NOT use the extension from the store to test the strategy, because, the extension is configured to only hook into the `postwoman.io` and `postwoman.netlify.com` domains. Other domains won't get hooked and hence won't get access to the extension hooks.
So, to test this PR, you have to clone the [postwoman-chrome](https://github.com/AndrewBastin/postwoman-chrome) repo.
Then head into the `manifest.json` file and edit it to match this snippet below
```
"content_scripts": [
{
"matches": [ …
```

Support for Google Chrome Extension

---

components/collections/addCollection.vue
components/collections/editCollection.vue
store/postwoman.js

closes #515 
Follow up of #510

Validations for edit and create collections activity

---

assets/css/styles.scss
functions/postwomanTesting.js
pages/index.vue

Follow up of #518 
- Typo fixes.
- Couple of other tweaks.

Enhancements

---

.gitignore
.travis.yml
package-lock.json
package.json
tests/e2e/integration/app.starter.spec.js
tests/e2e/integration/feature.url-queries.spec.js
tests/e2e/integration/proxy.spec.js
tests/e2e/support/commands.js

Some updates to e2e tests:
* fix error of dependency start-server-and-test update (`^1.10.8`) #544
* add test to proxy feature
* update test to url queries feature (test to add/remove passwords at url with the toggler)
* use nuxt `build/start` to run tests instead of `nuxt` 
> Some tests were failing because the vm of the ci was loading the assets (and the page was not ready to run the first test). This is a screenshot from a test that runned at travis:

update e2e tests

---

layouts/default.vue

Well, this is pretty self explanatory and pretty small PR.
The keyboard shortcuts dialog will show the shortcuts with `Ctrl` instead of `⌘` when viewing the shortcuts on the non-Apple platforms.

Show Ctrl instead of Command for shortcuts non-Apple platforms

---

functions/network.js
lang/en-US.js
pages/settings.vue
store/postwoman.js

This PR intends to add a toggle in the Settings page to turn off and on the use of extensions to send requests.
**NOTE for Translators:**
New entries added in the translations file

Added toggle to decide whether extensions should be used

---

components/collections/addCollection.vue
components/collections/editCollection.vue
functions/network.js
lang/en-US.js
pages/settings.vue

Follow up of #551
- Use `typeof` as an operator to ensure consistency across the codebase.
- Replace hard-coded strings with localizable strings.

chore: use typeof as an operator and make use of localizable strings

---

components/collections/addCollection.vue
components/collections/saveRequestAs.vue

Heyo! I was having issues syncing collections/requests and realized syncing only seems to work if you create and then edit collections. I just added the sync method to the add collection and save request components. There might be a better way to do it then how I've done it.

Added create collection and save request syncs

---

layouts/default.vue

Follow up of #571 
The `share` button seems to show up only if `Web Share API` is supported in the user's browser.

fix: drop the toast which doesn't show up

---

functions/network.js
functions/strategies/ExtensionStrategy.js

See AndrewBastin/postwoman-chrome#2 for more details.
I would propose to merge and release this change here a few days before releasing a new version of the extensions. So the new code inside Postwoman is loaded on most machines and nothing breaks.
Please wait until the PR at postwoman-chrome is approved before merging anything. Maybe more changes are needed here based on feedback.

Unify Chrome and Firefox extensions

---

store/state.js

I don't have any variables set, and when running a mutation; I get the following error:
```
Error SyntaxError: Unexpected end of JSON input
at JSON.parse (<anonymous>)
at VueComponent._callee$ (graphql.vue?f047:505)
at tryCatch (runtime.js?96cf:45)
at Generator.invoke [as _invoke] (runtime.js?96cf:271)
at Generator.prototype.<computed> [as next] (runtime.js?96cf:97)
at asyncGeneratorStep (asyncToGenerator.js?1da1:3)
at _next (asyncToGenerator.js?1da1:25)
at eval (asyncToGenerator.js?1da1:32)
at new Promise (<anonymous>)
at VueComponent.eval (asyncToGenerator.js?1da1:21)
```
**This error is caused by Postwoman trying to JSON parse an empty string, which is set as the default.**
https://github.com/liyasthomas/postwoman/blob/f690ea01c4319d57ea311261c9857faf4a8f6baa/pages/graphql.vue#L505 …

Fix variablesJSONString store default for GraphQL page

---

functions/editorutils.js
pages/index.vue

The Raw Request Body editor for POST requests is set to JSON mode and only provided the syntax highlighting mode for JSON. This PR intends to add the ability to for the user to update the syntax highlighting by updating the Content-Type.
So, for example, if the POST Content-Type is set to `application/xml`, the raw request editor updates the language mode to XML mode and if the request mode is set to `application/json`, it updates the mode to JSON Syntax Highlighting mode.

POST request body editor reacts to the content type

---

lang/en-US.js
pages/graphql.vue
pages/index.vue
pages/settings.vue
store/postwoman.js

Adds a toggle on the settings page (under the theme section) to enable and disable auto scroll (`scrollInto` functionality) on both graphql and index pages.

Added settings toggle for enabling/disabling auto scrolling (scrollInto functionality)

---

assets/css/fonts.scss
assets/css/styles.scss
components/ace-editor.vue
components/graphql/queryeditor.vue
layouts/default.vue
pages/settings.vue

Various improvements to the UI in terms of page loading/unloading.

Improve page load/unload experience (remove FOUCs)

---

components/ace-editor.vue
functions/jsonParse.js

This PR intends to add the ability for the Ace Code Editor to provide linting for JSON files in Postwoman.
You can try out the linter through any editor instance that specifies JSON as the language (so basically the GraphQL variable editor and the POST request content editor (when content type is set to `application/json`)).

JSON linting in the code editor

---

pages/index.vue
pages/index.vue.orig
store/state.js
tests/e2e/integration/proxy.spec.js

Added regex to handle url parts

---

layouts/default.vue

This PR intends to fix a bug with which the extension install toast appears even though the extension is installed.

Fixed install extension toast appearing even when extension is installed

---

package.json

This adds a `--staged` parameter to the `pretty-quick` pre-commit script, which will make sure only staged files are formatted. Partially staged files will not be re-staged after formatting, and pretty-quick will exit with a non-zero exit code. The intent is to abort the git commit, and allow the user to amend their selective staging to include formatting fixes.

Add --staged parameter to pretty-quick pre-commit

---

components/firebase/login.vue
lang/en-US.js
pages/settings.vue

This is the hacky solution- Open alternate signin popup on error catch.

Link multiple auth providers

---

components/graphql/queryeditor.vue
functions/platformutils.js
layouts/default.vue
pages/graphql.vue

This PR introduces a new shortcut to the GraphQL Query Editor which allows the user press Ctrl+Enter (Cmd+Enter on Mac) to run the query while editing in the query editor.

Added shortcut to quickly run the GraphQL query

---

pages/graphql.vue

This is a simple patch to ignore empty GraphQL variable strings.
That's about it. :sweat_smile:

Ignore empty GQL Variable Strings

---

.travis.yml
tests/e2e/integration/proxy.spec.js

- Simplify travis config. Chopped off all the envs and firebase build steps. Use travis just to run tests
- Update proxy test

test: purge travis

---

lang/en-US.js
pages/graphql.vue
store/state.js

- Schema will show `(waiting to receive schema)` until the schema is actually requested. (There's no point to show the editor box if there's no schema)
- Added default values for the Query and Variables editors (Most people coming to this page might not even know what GraphQL is. So it's best to give them an example of a query and the correct variables to pass. They can go right to the GraphQL page and click the `runQuery` button)
- Response will show `(waiting to receive response)` (Similar to reasoning above)
- Decreased the `minLines` for variables to 10, `minLines` for variables to 5, and `minLines` for response to 10.

Minor GraphQL page improvements

---

lang/en-US.js
pages/graphql.vue

This PR updates the message for when GraphQL Get Schema operation fails.
**NOTE to Translators: New translation strings are added in this PR**

Updated messages for when GraphQL Get Schema fails

---

pages/doc.vue

A pretty simple PR implementing a small fix to disable linting for the code editor in the docs page.

Removed linting for the collection docs import editor

---

README.md
components/realtime/log.vue
components/realtime/socketio.vue
functions/utils/string.js
functions/utils/valid.js
lang/en-US.js
nuxt.config.js
package-lock.json
package.json
pages/realtime.vue

Add Socket.IO support, resolves #611 
Now is a simple implement , more feature will be append soon.
Pick up some function to separate file, please check it.
By the way, i have not found a public socketio server as a default value, is any good idea to improve it?

Feature: add socket io support

---

components/realtime/socketio.vue
functions/utils/valid.js

Allow http/https protocols for Socket.io endpoints.
Next step i will append event listener(because of socketio looks like cant get all message, must be specify eventName).

Add http/https support to socketio url valid

---

components/graphql/queryeditor.vue
lang/en-US.js
pages/graphql.vue

This PR intends to add the ability to do GraphQL query prettification. It adds a editor shortcut (`cmd-p` or `ctrl-p`) and also a button above the query editor to do prettification.
I am not a pretty big fan of the icon for the prettify button, I had that auto-fix magic wand icon in my mind but I think it is removed from the material icons collection now. @liyasthomas it would be awesome if you could replace that with something more aesthetically pleasing.
**NOTE to Translators: Added new entries for i10n**

Added the ability to prettify GraphQL queries

---

pages/index.vue

Fixes https://github.com/liyasthomas/postwoman/issues/597
**Scope of work**:
1. Enable _raw input_ toggle only for `application/x-www-form-urlencoded` and force true in other cases;
2. Fix default body (raw) for each content type;

Fix handling content type and raw input

---

pages/index.vue

My first PR comes with a minor bug here https://github.com/liyasthomas/postwoman/pull/678/files#diff-b19fa22add3de9cd0b98b05366479d92R1442 :disappointed: 
It's always true, so every time content type is changed to `application/json` body will be reset.
I'm fixing it here and also ensuring body is being reset to defaults only if it was not manually changed (empty or equals to default body for old content type).

Fix setting default raw params

---

pages/index.vue

Add application/vnd.api+json to the places where content type matters.
Closes #694 
I noticed there are a lot of places where this is repeated. Should we place these in an constant somewhere? I'm not sure I understand where the different types matter...

Add application/vnd.api+json

---

pages/index.vue

Related issue: https://github.com/liyasthomas/postwoman/issues/597
As I've commented on commit https://github.com/liyasthomas/postwoman/commit/b14adc29f521271306970e896c45ffe46ee04848, the problem with JSON body and raw input is happening again after this commit, maybe I've named things badly (`canListParameters`) and you misunderstood me, so I'm suggesting another fix :stuck_out_tongue: 
I've realized that it's getting `rawInput` original state from Vuex, and then it could happen to have JSON content with raw input disabled and without the toggle component, this way it would not be possible to enable raw input at all...
Now I'm making sure `rawInput` is true always `canListParameters` is false, and kept (revert) `canListParameters` to be true only with …

Fix raw input (JSON)

---

components/collections/importExportCollections.vue

If you try importing a postman collection that contains an empty raw url, it silently fails.
Just needed a nullcheck.

Fix postman import with empty url

---

pages/index.vue

[support response json array · Issue #805 · liyasthomas/postwoman](https://github.com/liyasthomas/postwoman/issues/805)
Editor component can't recognize json Array.
(It accepts json Object.)
If JSON Array, set this.responseBodyType 'json5'.
- When 'responseType` is `json/ etc`, responseBodyType will be set
- `json` : response.body.type's constructor name is `Object`. (Usual case)
- `json5` : response.body.type's constructor name is `Array`. (#805 's case)
- JSON Array
- JSON Object

Modify responseType by Object(json) or Array(json5)

---

components/realtime/socketio.vue

The SocketIo tab in realtime currently only supports string input even though the SocketIo library can support sending json data (implicitly encoding and decoding).  
This change attempts to parse the user input to json in order to send it as json instead of a string.  If the user input is not valid json, it will be sent as a string.

Realtime SocketIO support for json user input

---

nuxt.config.js

delete render option in nuxt.config.js which is skipped for spa mode

chore(config): delete render option

---

components/graphql/queryeditor.vue
functions/syntax/gqlQueryLangMode.js

Yay, first PR in after a while!
This PR intends to add syntax highlighting to the GraphQL query editor.
There could be some improvements made (like for applying highlighting non-builtin types), but this provides a working implementation for now.
This PR fixes #741

GraphQL Query Editor Syntax Highlighting

---

lang/en-US.json
pages/index.vue

Adds a button to prettify the json request body.
[![Prettify](https://i.imgur.com/9JqMouv.png)](https://i.imgur.com/9JqMouv.png)
Shows a toast error if the body isn't a proper json string.
This PR fixes #767.

Add format body option

---

functions/utils/uri.js
pages/index.vue

Fixes saving a request when using environment variables.
url and path variables get overwritten with replaced values, so before saving we reconstruct them using the original uri variable.
This PR intends to fix #642.

Environment variables in collections

---

components/environments/importExportEnvironment.vue

When importing a JSON file during the environment import we check for the Postman specific field `_postman_variable_scope` which should be set to `environment`.
If so, we re-format the JSON to the Postwoman structure and call the existing import function.
If not, we assume it is a Postwoman file and import it as usual.
This PR intends to add the feature discussed in #759

Allow importing environment variables via Postman environment json files

---

functions/strategies/AxiosStrategy.js
package-lock.json

This PR intends to update the axios default behaviour of parsing JSON strings to JSON objects even if the content-type is not JSON type.
This PR fixes #869

Fixed Axios parsing JSON for non-JSON content-types

---

functions/strategies/AxiosStrategy.js

This PR adds a small check for the `content-type` header in the transformResponse override in the AxiosStrategy file.
This PR fixes #894

Added check if content-type header is present for transformResponse

---

functions/network.js
functions/strategies/AxiosStrategy.js
functions/strategies/ExtensionStrategy.js
lang/en-US.json
pages/index.vue

This PR intends to add the ability to cancel running requests.
@liyasthomas what do you think about the cancel button ? should it be red or something ?
The browser extensions don't currently support cancellable requests, the cancel attempts will just be ignored in case of extensions for now, the support implementation will be rolled with extension version v0.10 which is a bit delayed as I am waiting for approval for the extension to the Microsoft Edge add-on store.
This PR fixes #909

Cancellable Requests

---

lang/en-US.json
pages/index.vue

This PR intends to add the ability to use `Ctrl+G` key combo to cancel running requests.
Also there is a update to the language entry for `send_request`

Cancel Request from the Keyboard

---

pages/graphql.vue

GraphQL response options (copy response and download response JSON) is only visible when a response is available.

GraphQL response options only visible when a response is shown

---

functions/utils/contenttypes.js
pages/index.vue

This PR intends to introduce the behaviour of the download response button above the response view to be hidden when the response is not a JSON response (detected from content-type).
This is a temporary fix for until the solution for #929 is implemented.

Hide download response button for non-JSON responses

---

pages/index.vue

And stop generating Content-Length header so it's easier to modify the generated code. Corresponding HTTP clients (like cURL) should handle Content-Type pretty well anyway.

Add trailing backslash to generated cURL code for easier paste-and-execute

---

pages/index.vue

Test scripts now get properly parsed to the `pw.response.body` field if it is a valid JSON body.
This PR intends to fix #1036

Test scripts get properly parsed JSON body

---

lang/en-US.json
pages/settings.vue

This PR intends to add text which reports the installed extension version (if present). Really useful for debugging purposes.
There are new translation entries in this PR.

Report Extension Version in the settings page

---

components/settings/swatch.vue

Hi,
I have added a few CSS to fix the broken placement of Tick Icons in Settings.
This PR fixes #1057 
**Below are the changes, I have implemented:**
CSS for the parent element of tick icon:
```CSS
position:relative
```
CSS for the tick icon to place it in the center:
```CSS
position:absolute;
margin: auto;
top: 0;
bottom: 0;
left: 0;
right: 0;
```

Fixed broken tick icons placement in Settings

---

components/ui/__tests__/autocomplete.spec.js

Use `toBe()` matcher for primitives.

tests: improve test suite

---

components/layout/pw-header.vue

Hi, this is a PR to fix the Addon link as detailed in #1146

Fixed firefox addon link in header

---

components/ui/autocomplete.vue

I noticed when trying to tab to the next input in the headers section, it would paste `undefined` into the current input. I've added a check that restores the tab functionality if there are no active suggestions.
Please let me know if there are any issues with this, thanks!

Add check for active suggestion

---

lang/es-ES.json

Add translation for new content since last edition. 
I didn't notice there was new content in my previous PR (#1206) so, if this can be added directly to it please do so.

docs[es-ES]: add translations for new content

---

helpers/codegen/generators/go-native.js

This PR fixes a small bug which causes url to not show up in Go codegen for get requests.
- `helpers/codegen/generators/go-native.js` changed
#1215

Fix: GET requests for Go codegen

---

components/layout/sidenav.vue

**Bug fixed**
Sidenav animation did not work
**To Reproduce**
Click on the sidenav icons. The animation is abrupt.
**Expected behavior**
The icon should slowly expand when it becomes active.
**Explanation**
- The `border-radius` on the nav link icons was set to `9999px`, hence transitioning to `16px` in 200ms did produce a noticeable change. 
- `transition-property` on the `nav > a` tags did not include border-radius.
- These were most likely due to Tailwind CSS (or that's what I understood from `@apply`)
**Solution**
- Set `border-radius` to `50%` for a circle instead of using `9999px`.
- Set `transition-property` to `all !important` for `nav > a` links.
I have verified that this fixes the animation.

Fixed sidenav animation

---

assets/scss/styles.scss
components/layout/sidenav.vue

Fixes issue #1003 
Adds extra spacing to account for the home bar on some iPhone devices, using the safe-area-inset-bottom env variable.

Fix: ios home bar covers content

---

components/ui/tabs.vue

Fixes issue #1222
The header dropdown was being cut off due to the parent container .tabs having overflow set to hidden so have removed this property from the styles and this has fixed the issue:

Fix: http page headers suggestions overlapped issue

---

components/graphql/field.vue
components/graphql/type.vue
helpers/codegen/generators/go-native.js
pages/graphql.vue

Related issue #1188 
The PR adds basic filtering for `queryFields`, `mutationFields`, `subscriptionFields` and `gqlTypes`.
The value provided to the search input is used to match on `fieldName` and `description` fields.
`gqlTypes` are handled differently as we also filter on `gqlTypes._fields` array.
Some improvements for an other PR could be to highlight matched text (?)
Also, `gqlTypes._fields` filtering could be improved by keeping only matched fields as it can be confusing to see the whole Schema and having to scroll until you find concerned field
**Unfiltered results**
**Filtered results**

Add search input & capability to graphql types and fields

---

components/realtime/socketio.vue

Issue #1149 
We can now pass multiple args to socket.io `sendMessage`.

Allow multiple arguments with socket.io

---

helpers/codegen/generators/nodejs-request.js

This PR is to fix 2 issues in the `nodejs-request` codegen.
1. form data with more than 1 key/val pairs are not parsed properly
before:
after:
2. XML is not quoted properly so it generates broken code
before:
after:

Fix form post data parsing

---

docker-compose.yml

Hi,
I was playing with the repository so I can learn how to add a code generator for the issue https://github.com/hoppscotch/hoppscotch/issues/1190 and found that the `helpers` folder was not mapped in `docker-compose.yml`.
I added it so hot-reload can work while editing code generators.
Seems like `functions`, `lang` and `netlify` folders are missing too. I didn't add them as I don't need them for now and I don't know docker enough to know what is the impact but I can edit the PR if you want them to be added.

fix:add 'helpers' folder to docker compose volumes

---

components/collections/index.vue

Accidentally left a `console.log` in #1260. This PR fixes that.

Remove extra console log

---

components/realtime/mqtt.vue
components/realtime/socketio.vue
components/realtime/sse.vue
components/realtime/websocket.vue
store/mutations.js
store/state.js

Hey, sorry for taking so long with this 😕
I was able to add persistence to 3 out of the 4 realtime tabs. It's just SocketIO that's giving me some trouble. What I've done in each tab is move all the data into `vuex` including each client. Like @LeoMartinDev suggested, I changed the connectionStates to be computed from the instance of each client, and renamed all of them to `isConnected`.
SocketIO is giving me trouble because I've followed the same pattern of putting it in `vuex`, but on connect, it says I'm mutating state outside of a store handler for some reason. 
I also haven't added persistence where it stays on the same realtime tab on refresh or going to a different tab. It just always defaults to WebSocket tab. 
Anyways, hope I can get some feedback on this to match coding standards …

WIP Feat/realtime tab session persistence

---

helpers/codegen/__tests__/__snapshots__/codegen.spec.js.snap
helpers/codegen/generators/nodejs-axios.js

Origin generators:
```javascript
axios.post('address', {
// request body
},{
headers : {
// request head
}.then(response => {
console.log(response);
}).catch(error => {
console.log(error);
})
```
after fix:
```javascript
axios.post('address', {
// request body
},{
headers : {
// request head
}).then(response => {
console.log(response);
}).catch(error => {
console.log(error);
})
```

Fix a missing close parenthesis before '.then'

---

helpers/utils/contenttypes.js

Add [JSON-LD](https://json-ld.org/) to the list of known content types. It's a standard and a format commonly used by web APIs and in the Linked Data ecosystem (Schema.org, SOLID, ActivityPub...).
It's also used by default by [API Platform](https://api-platform.com) that I maintain. I will probably create more following PR to ensure that Hoppscotch and API Platform play well together!

feat: add JSON-LD to the list of known content types

---

helpers/findStatusGroup.js

The current regular expressions detecting status code classes are incorrect. For instance `422` (which is returned by Rails, Symfony and API Platform when a request is invalid because of invalid user data) is detected as belonging to the `success` class instead of `client error` because it contains the number `2`.
The regex should be something like `/^4\d{2}$/` but using a RegExp here isn't necessary, so I switched to simple numerical comparisons (which are faster).

fix: status code detection

---

components/graphql/type.vue
pages/graphql.vue

Hello!
This PR fixes jumping to GraphQL type on click and adds input types to the types tab.

Fix "jump to graphql type" and show graphql input types

---

components/collections/choose-collection-type.vue
components/collections/collection.vue
components/collections/folder.vue
components/collections/index.vue
components/ui/tabs.vue

**Changes:**
* Implemented integration of teams with collections in collections/index.vue 
* switching between My Collections and Team Collections and choosing team under Team Collections
* viewing team collections
**Remaining tasks:**
* Add, edit, delete and import collection/folders are still to be implemented for teams (coming in another PR).
* collection fetch requests need to be of type "no-cache" (coming in another PR)
* All text is as strings and not in the $t("..") format.
**Preview:**

[Feat:Teams] Team collections tab and View team collections

---

components/collections/add-collection.vue
components/collections/choose-collection-type.vue
components/collections/collection.vue
components/collections/edit-collection.vue
components/collections/index.vue
lang/en-US.json

This PR intends to bring add, delete and edit functionalities to team collections.
The changes implemented are:
- Disable the new, edit, and delete collection button for VIEWER
- Implement functions and GraphQL mutations to add, delete and edit team collection
P.S. Folder feature in team collections is not yet implemented and would be implemented next.

Feat: Add, delete and edit team collection -  Raghav

---

Dockerfile
components/http/http-body-parameters.vue
helpers/utils/contenttypes.js
pages/index.vue
store/state.js

Add support for `multipart/form-data` content-type. When `mutipart-form-data` is chosen, an attachment icon appears in each request body line. This allows the attachment of files with named keys in the existing UI. Filename parsing and most of the UI side of things are not implemented yet and thus the ugly `[object FileList]` is being displayed.
Multiple files can be uploaded into a single field too!

Preliminary naming of form data fields support

---

components/http/http-body-parameters.vue
components/ui/deletable-chip.vue
pages/index.vue
plugins/vuex-persist.js
store/mutations.js

Per the image above, chips have been added to denote the files that have been chosen. This feature is still currently incomplete.
Todo:
File objects cannot be recreated, and this thus means that we will not be able to restore a user's files in a request after a reload. FormData file fields also will not be able to be synced/exported. Thus, we should exclude file fields from vuex and store them instead in a component's state.

[Feat: formData] Add chips to indicate chosen files in formData

---

store/postwoman.js

Since `File` is not serializable, form data fields with files cannot be saved into a collection. Thus, files are filtered out before a request is added to a collection.

[Feat/form data] Remove file fields from collections

---

README.md

[Hopp-Doc-Gen](https://github.com/hoppscotch/hopp-doc-gen)

docs: add reference to hopp-doc-gen add-on

---

components/collections/collection.vue
components/collections/folder.vue
components/collections/index.vue
components/collections/save-request-as.vue
helpers/teams/utils.js

re-utilize collections component to select folder and collections
**checks:**
- ~[ ] persist visual indication on selected location even after losing mouse focus~
**remarks:**

change UI to save request in my-collection

---

helpers/codegen/codegen.js
helpers/codegen/generators/c-libcurl.js
helpers/codegen/generators/generator.js

This PR provides the following: 
- New generic `Generator` class to be used in ongoing refactoring for generators. (`helpers/codegen/generators/generator.js`)
- Refactoring and isolation of methods of the CLibcurl generator found in (`helpers/codegen/generators/c-libcurl.js`)
```
feat: New Generator class to serve as parent class for generators.
refactor: c-libcurl.js export to class instance & isolated methods.
fix: Refactor for CLIBcurlCodegen import to expect default export.
fix: Default generator properties added and reset by generator().
When calling a generator multiple times during testing, because the generator is only
instantiated on export, ie "export default new CLibCurlCodeGen()", any properties assigned to
"this" live past a single generator instance.
The default export new …
```

refactor: CLibcurl Generator.

---

components/collections/collection.vue
components/collections/folder.vue
components/collections/index.vue
components/collections/request.vue
components/collections/save-request-as.vue
helpers/teams/utils.js

user can now select the request to overwrite for my-collections
**checks:**

add UI for overwriting request

---

components/collections/Folder.vue

Sub-folders show at the bottom of the list. You have to scroll all the way down to reach a folder you want to access.
Depends on user preference I believe but makes more sense the other way round
Before
After

Show sub-folders first instead of requests

---

components/collections/collection.vue
components/collections/edit-collection.vue
components/collections/edit-request.vue
components/collections/folder.vue
components/collections/index.vue
components/collections/request.vue
helpers/teams/utils.js

Fixed bugs for add, delete, and edit for team collections and folders. And implement edit and delete functions for team requests. This PR achieves the following
1. Collection 
* Add - Done
* Delete - Done
* Edit - Done
2. Folder
* Add - Successful but needs a refresh to get reflected in UI
* Delete - Done
* Edit - Successful, requires a refresh
3. Request
* Add - Successful, requires a refresh
* Delete - Successful, requires a refresh
* Edit - Successful, requires a refresh

Add, Delete & Edit functionalities for Team collections, folders and request

---

components/collections/ImportExport.vue

When importing a Postman Collection if the url is empty this throws a `Cannot read property 'raw' of null` and `Cannot read property 'query` error this pr fixes that.
You can recreate the error and test this pr with this postman file 
[test.postman_collection.zip](https://github.com/hoppscotch/hoppscotch/files/6308109/test.postman_collection.zip)
---
Fixed #1587

fixes empty url bug during importing postman json

---

components/app/Header.vue

Changed the Title from Hs to Hoppscotch for all sizes. I feel that using Hs is a waste of space especially on devices that have huge width like the iPad. I also tried testing this on most devices including small devices like the iPhone SE and the Galaxy Fold. It worked fine for all devices that I tested.

Changing Hoppscotch Title from Hs to Hoppscotch for all sizes

---

helpers/teams/TeamMemberAdapter.ts

Found a stray `debugger` while browsing the code, removed it for you

chore: remove stray debugger

---

components/smart/AutoComplete.vue
pages/index.vue

This PR fixes issue #1691. This fix prevents the changing of HTTP method to overwrite the content type of a request if the content type is already set.  Moreover, the `AutoComplete` component watches for updates to its `value` prop so as to update the input field contents when the `value` prop changes.

fix: prevent overwrite of content type

---

components/collections/Add.vue
components/collections/AddFolder.vue
components/collections/Edit.vue
components/collections/EditFolder.vue
components/collections/EditRequest.vue
components/collections/SaveRequest.vue
components/collections/graphql/Add.vue
components/collections/graphql/AddFolder.vue
components/collections/graphql/Edit.vue
components/collections/graphql/EditFolder.vue
components/collections/graphql/EditRequest.vue
components/environments/Add.vue
components/environments/Edit.vue

There are some duplicated inputs' ids on the page. 
To reproduce:
- click "save to collections"(gql or home page - that's doesn't matter) and check out the id of the "Request name" input.
- click "new" and compare the "Label" input id with the one from the first step. they are the same.
Sometimes duplicated ids  can lead to some really weird behavior. in this case if you click on the label from the second step - input from the first one gets focused.

fix: duplicated input ids

---

components/history/rest/Card.vue
pages/index.vue

duration is always undefined when there was any error during request

fix: undefined duration

---

helpers/oauth.js

https://developer.okta.com/docs/guides/implement-auth-code-pkce/exchange-code-token/

fix: oauth token exchange param naming convention

---

helpers/oauth.js

e.g. https://swagger.io/docs/specification/authentication/openid-connect-discovery/
I smell a rogue linter..,

fix: bad var names from oauth well.known config

---

newstore/localpersistence.ts
store/postwoman.js

The problem:
https://user-images.githubusercontent.com/41614937/128659587-6ebd297b-7f61-4db1-bf04-41c47e4d76f9.mp4
[This line](https://github.com/hoppscotch/hoppscotch/blob/main/newstore/localpersistence.ts#L32) always returns true since vuexData.postwoman.settings is an object(somehow)
[This one](https://github.com/hoppscotch/hoppscotch/blob/main/newstore/localpersistence.ts#L30) also always returns true because we are using shallow comparison for different objects, so _.isEmpty is a better choice here.
I don't fully understand the background of these migrations, but i took responsibility to refactor this file a little bit(the postwoman part of it), looks like it shouldn't break anything

fix: broken settings persistence on the home page

---

helpers/codegen/codegen.ts

fixes #1798 
The issue was because the finally calculated headers also contain the calculated authorization headers. This patch removes the header letting the codegen just use the auth state to determine

fix: auth header doubling in codegen

---

helpers/GQLConnection.ts

Fix GraphQL headers not being passed properly into the GQL requests.

fix: gql headers not passed properly (HOPP-55)

---

packages/hoppscotch-app/components/graphql/RequestOptions.vue
packages/hoppscotch-app/helpers/strategies/AxiosStrategy.js
packages/hoppscotch-app/helpers/strategies/__tests__/AxiosStrategy-NoProxy.spec.js
packages/hoppscotch-app/helpers/utils/JsonFormattedError.ts

Fix proposal (very simple) for request #1828 
I was not clear from the original ticket what the requirements were. 
- Like the toast message format might not be ideal. Maybe could indicate that it was a HTTP 400 error for example instead of the entire error message. 
- Also, should we continue to say to go and check the logs for futher details?
- I did not test with proxies. Seems like the request made is different in that case. (not using `responseType: "arraybuffer"`
Let me know what you think. thanks

Show graphql error message

---

packages/hoppscotch-app/locales/tw.json

Changelog
- Global
- response 響應 -> 回應 (Reference: [MDN Web Docs](https://developer.mozilla.org/zh-TW/docs/Web/HTTP/Status))
- punctuations: halfwidth -> fullwidth 
- type 型別 ->類型
- action
- duplicate (add and sync with en)
- auth
- account_exists (add)
- collection
- renamed (fix)
- confirm
- remove_telemetry (add)
- sync (add missing translations for second sentence.)
- layout
- column: fix https://github.com/hoppscotch/hoppscotch/pull/1940 by @jks15satoshi (Reference: [National Academy for Educational Research](https://terms.naer.edu.tw/detail/15996031/))
- row
- settings
- account_description 您 -> 你 (Consistency fix. Most of the `you` is translated into `你` in this app and so are they)
- account_email_description 您 -> 你
- account_name_description 您 -> 你
- telemetry (add)
- …

chore(i18n): update tw translations

---

packages/hoppscotch-app/components/http/ImportCurl.vue
packages/hoppscotch-app/components/http/Request.vue
packages/hoppscotch-app/components/smart/EnvInput.vue
packages/hoppscotch-app/helpers/curlparser.ts

Closes # 
I've updated the code which contains the feature: now you can copy a cURL from the network console of the browser or from anywhere and paste it to the URL field then it will automatically recognize the cURL format. And will generate the request.

feat: import cURL on paste

---

packages/hoppscotch-app/helpers/lenses/imageLens.ts

Closes # 
With all major browsers have added support for more than one year (Safari being the latest), we can safely assume WebP is available most of the time.
👇 Meta warning: below is a WebP image showing WebP support
[![](https://caniuse.bitsofco.de/image/webp.webp)](https://caniuse.com/?search=webp)
If the browser really doesn't support WebP, they just get a alt icon and nothing really breaks. That's still better than showing the raw binary:

Enable image lens for WebP

---

packages/hoppscotch-app/components/profile/Picture.vue
packages/hoppscotch-app/helpers/oauth.js

[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.

refactor: replace deprecated String.prototype.substr()

---

packages/hoppscotch-app/helpers/editor/codemirror.ts

This small patch introduces a small update that blocks IMEs from starting composition when editing a readonly code editor instance.
This is especially useful on mobile devices where the virtual keyboard is triggered when the REST Response Body is tapped on which further reduces the screen space.
Check IME behavior on Android and iOS and see how they react on readonly and readwrite fields.

Prevent IMEs from triggering when editing a readonly code editor

---

packages/hoppscotch-app/components/collections/AddRequest.vue
packages/hoppscotch-app/components/collections/graphql/AddRequest.vue
packages/hoppscotch-app/components/collections/graphql/Collection.vue
packages/hoppscotch-app/components/collections/graphql/Folder.vue
packages/hoppscotch-app/components/collections/graphql/index.vue
packages/hoppscotch-app/components/collections/index.vue
packages/hoppscotch-app/components/collections/my/Collection.vue
packages/hoppscotch-app/components/collections/my/Folder.vue
packages/hoppscotch-app/components/collections/teams/Collection.vue
packages/hoppscotch-app/components/collections/teams/Folder.vue
packages/hoppscotch-app/locales/en.json

New Request button is now available in the kabab menu
for both folders and collections in REST as well as
GraphQL.
It creates a new request, saves it to the store and
points to it.
Closes #2156

feat: add `New Request` button for folder and collection

---

packages/hoppscotch-app/components/smart/EnvInput.vue

Closes #2137 
Add code to make all forms on page have an aria label equivelent to their placeholder text. This fix works as long as forms have descriptive placeholder text. There may still be more screen reader accessibility improvements to make in the future, but it looks like every component is properly labeled for screen reader use at the moment.

fix: add aria labels to forms

---

packages/hoppscotch-cli/src/interfaces/response.ts
packages/hoppscotch-cli/src/types/request.ts
packages/hoppscotch-cli/src/types/response.ts
packages/hoppscotch-cli/src/utils/collections.ts
packages/hoppscotch-cli/src/utils/constants.ts
packages/hoppscotch-cli/src/utils/display.ts
packages/hoppscotch-cli/src/utils/getters.ts
packages/hoppscotch-cli/src/utils/pre-request.ts
packages/hoppscotch-cli/src/utils/request.ts
packages/hoppscotch-cli/src/utils/test.ts

The PR includes features mentioned below.
- Each request's execution duration in seconds.
- Each test-script's execution duration in seconds.
- Total execution duration for all requests and test-scripts respectively.
- Total passing and failing requests, test-scripts, pre-request-scripts.

feat: added execution duration and updated collection-metrics

---

packages/hoppscotch-app/components/collections/Add.vue
packages/hoppscotch-app/components/collections/AddFolder.vue
packages/hoppscotch-app/components/collections/Edit.vue
packages/hoppscotch-app/components/collections/EditFolder.vue
packages/hoppscotch-app/components/collections/EditRequest.vue
packages/hoppscotch-app/components/collections/index.vue
packages/hoppscotch-app/components/collections/my/Collection.vue
packages/hoppscotch-app/components/collections/my/Folder.vue
packages/hoppscotch-app/components/collections/my/Request.vue
packages/hoppscotch-app/components/collections/teams/Collection.vue
packages/hoppscotch-app/components/collections/teams/Folder.vue
packages/hoppscotch-app/components/collections/teams/Request.vue
packages/hoppscotch-app/components/smart/ConfirmModal.vue

Adds loading state to buttons in different modals.

feat: loading states for modal buttons

---

packages/hoppscotch-app/components/collections/SaveRequest.vue
packages/hoppscotch-app/components/http/Request.vue

Closes #2318 
This PR fixes the unsaved change popup bug in which the popup tends to trigger even though the request was saved.PR also fix a small bug that occurred when changing context while saving the request.

fix : save request popup bug

---

packages/hoppscotch-app/components/http/Request.vue
packages/hoppscotch-app/components/profile/Shortcode.vue
packages/hoppscotch-app/helpers/backend/gql/mutations/DeleteShortcode.graphql
packages/hoppscotch-app/helpers/backend/gql/queries/GetMyShortcodes.graphql
packages/hoppscotch-app/helpers/backend/gql/subscriptions/ShortcodeCreated.graphql
packages/hoppscotch-app/helpers/backend/gql/subscriptions/ShortcodeDeleted.graphql
packages/hoppscotch-app/helpers/backend/helpers.ts
packages/hoppscotch-app/helpers/backend/mutations/Shortcode.ts
packages/hoppscotch-app/helpers/shortcodes/Shortcode.ts
packages/hoppscotch-app/helpers/shortcodes/ShortcodeListAdapter.ts
packages/hoppscotch-app/locales/en.json
packages/hoppscotch-app/pages/profile.vue

This PR introduces a feature in which authenticated user can view their created shortcodes and can delete, copy shortcode link or open the request from their profile page.

feat: UI of shortcode actions

---

packages/hoppscotch-app/helpers/curl/__tests__/curlparser.spec.js
packages/hoppscotch-app/helpers/curl/curlparser.ts
packages/hoppscotch-app/helpers/curl/sub_helpers/contentParser.ts
packages/hoppscotch-app/helpers/curl/sub_helpers/preproc.ts
packages/hoppscotch-app/helpers/curl/sub_helpers/url.ts
packages/hoppscotch-app/helpers/functional/debug.ts

- All Unsafe characters are removed from the url string following RFC 1738
- All the non-tagged arguments are checked for possible presence of url
- Some more local url checks were added.
Reference: [RFC 1738](http://www.faqs.org/rfcs/rfc1738.html)

fix: curl parser url sanitisation

---

packages/hoppscotch-app/components/app/DeveloperOptions.vue
packages/hoppscotch-app/components/app/Share.vue
packages/hoppscotch-app/components/environments/Details.vue
packages/hoppscotch-app/components/graphql/RequestOptions.vue
packages/hoppscotch-app/components/graphql/Response.vue
packages/hoppscotch-app/components/graphql/Sidebar.vue
packages/hoppscotch-app/components/http/CodegenModal.vue
packages/hoppscotch-app/components/http/ImportCurl.vue
packages/hoppscotch-app/components/http/RawBody.vue
packages/hoppscotch-app/components/http/Request.vue
packages/hoppscotch-app/components/lenses/HeadersRenderer.vue
packages/hoppscotch-app/components/lenses/HeadersRendererEntry.vue
packages/hoppscotch-app/components/profile/Shortcode.vue
packages/hoppscotch-app/components/realtime/Communication.vue
packages/hoppscotch-app/components/realtime/LogEntry.vue
packages/hoppscotch-app/helpers/lenses/composables/useCopyResponse.ts
packages/hoppscotch-app/helpers/lenses/composables/useDownloadResponse.ts
packages/hoppscotch-app/pages/settings.vue

Closes https://github.com/hoppscotch/internal-issues/issues/16 
Use [`refAutoReset`](https://vueuse.org/shared/refautoreset/) instead of `setTimeout()`

refactor: use refAutoReset instead of settimeout

---

packages/hoppscotch-app/components/http/ResponseMeta.vue

The response size is always displayed using larger units like KB or MB in other API testing tools I've used. But hoppscotch shows them up with only a B. I added a tooltip to display the response size in reasonable units.
For responses with a size of 0b to 1000b, the tooltip won't show up. For those with a size of 1000b to 1000000b, kB will be shown. For those larger than 1000000b, mb will be shown. 
I am no expert on the front-end technologies, so I just imitated the current codes. If you don't like these codes, please keep the idea even if you close the pr.

feat: display response size with a bigger unit in tooltip

---

packages/hoppscotch-app/components/collections/my/Request.vue

Related to issue 2207
The issue 2207 added a warning for "unsaved changes might get lost", however, I found it annoying that the message poped up also at the default value...

feat: checks only if not default param

---

packages/hoppscotch-app/components/lenses/renderers/JSONLensRenderer.vue

Currently, the initial response body gets copied and downloaded after filtering, this PR fixes this bug.

fix: Copy and download filtered response body

---

packages/hoppscotch-app/components/http/BodyParameters.vue

Closes #2390 
This PR resolves an issue with removing a parameters for request body parameters causing the browser to crash and hang. The solution to this is to add an `id` parameter to parameters so that each item is unique in the view and gets re-rendered on change.
[x] Fixed removing a body parameter from REST Request

fix: resolve removing body parameters in requests (#2390)

---

packages/hoppscotch-app/components/collections/my/Request.vue
packages/hoppscotch-app/components/collections/teams/Request.vue

Closes #2368 
This PR closes the issue where a user could not overwrite a request and remove the confirm change popup inside the save as popup.

fix: remove confirm change popup and add ability to overwrite request in saveas popup 

---

packages/hoppscotch-app/components/http/TestResultEnv.vue

Closes #2472 
If we set environment variables in Test, The Test Results section shows the environment variable change,
But if the value of the variable is too long it breaks the UI, I have added a fix that will break the word in multiple lines if it's too long.
Screenshot of the **Test Results** section after changes(for large, overflowing values)

Test Results: Environment variables overflow issue fix

---

packages/hoppscotch-app/helpers/curl/__tests__/curlparser.spec.js
packages/hoppscotch-app/helpers/curl/curlparser.ts

x-www-form-urlencoded body is parsed correctly now with/without content-type header provided.
Solves #2424

fix: curl parser x-www-form-urlencoded body parsing

---

packages/hoppscotch-app/helpers/editor/extensions/HoppEnvironment.ts

Closes #2554 
The issue is when having an environment variable with a dash '-' in its name, the variable is not colorized in the URL. It's fixed by this PR.

Hightlight environment variable with a dash '-' in its name

---

packages/hoppscotch-app/components/app/PaneLayout.vue
packages/hoppscotch-app/pages/documentation.vue
packages/hoppscotch-app/pages/graphql.vue
packages/hoppscotch-app/pages/index.vue
packages/hoppscotch-app/pages/realtime/mqtt.vue
packages/hoppscotch-app/pages/realtime/socketio.vue
packages/hoppscotch-app/pages/realtime/sse.vue
packages/hoppscotch-app/pages/realtime/websocket.vue

Closes  #2456 
Save the different pane sizes (for instance, in local storage) in order to restore the visual configuration the next time the app is opened

feat: remember pane sizes

---

packages/hoppscotch-app/helpers/keybindings.ts
packages/hoppscotch-app/helpers/shortcuts.js

Closes #2543 
Updating the command for Go to Profile page. Previously `Alt+P` command was bound to two different commands. In this PR we changed the command for Navigate to Profile page from `Alt+P` to `Alt+M`

feat: update keyboard shortcut to navigate to profile page

---

packages/hoppscotch-app/package.json
packages/hoppscotch-cli/package.json
packages/hoppscotch-data/package.json
packages/hoppscotch-data/src/rawKeyValue.ts
packages/hoppscotch-data/src/utils/record.ts
packages/hoppscotch-js-sandbox/package.json
pnpm-lock.yaml

This PR implements ability for Raw Key Value pairs to include escape characters for parsing leading and trailing whitespaces and other special characters which may be present in a raw key or value.
Closes #2577
With the introduction of this PR, quotations will be allowed in Raw Key Value grammar
```yaml
hello: world
"quoted hello": "quoted world"
```
This will be parsed into the following AST representation
```json
[
{ "active": true, "key": "hello", "value": "world" },
{ "active": true, "key": "quoted hello", "value": "quoted world" }
]
```
This allows for representing weird characters, trailing and leading whitespaces and use of key symbols of the grammar (like `#` and `:`) within the key/value strings. Along with that, escape characters are also recognized and parsed into the AST …

feat: allow quoted key/values for escaping characters and trail/lead whitespaces in raw key value pairs

---

packages/hoppscotch-app/components/firebase/Login.vue
packages/hoppscotch-app/helpers/fb/auth.ts

Closes #2610
This fixes the original bug report in #2610 about having a Github and Google account. They were not getting linked previously. This is a draft PR to request inputs about how to handle multiple combinations of accounts.
For example sign in with Google assumes linked account is always Github. Sign in with Github assumes linked account is Google. Sign in with Microsoft assumes linked account is Github. We should allow any combination of linked accounts and our code should reflect that.
Don't know about Github/MS/Google to email behavior.
This could be an opportunity to DRY some duplicate code.

fix: link github and google

---

.github/workflows/publish-docker.yml

Closes #2524
This PR modifies the `publish-docker.yml` workflow in order to publish the docker image for ARM based platforms.
Now it pushes images for the following platforms:
- linux/amd64: already existing, default platform
- linux/arm/v7
- linux/arm64/v8
This will add support for new Apple computers with M-series chips, and newer Raspberry Pi (among other systems as well).
As the original base image [`node:lts-slim`](https://hub.docker.com/_/node/tags?page=1&name=lts-slim) supports the platforms linux/amd64, linux/arm/v7 and linux/arm64/v8, we can build for those platforms too without problem.
The workflow modifications are based on the [docker/build-push-action docs for Multi-platform image](https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md). I …

ci: modify publish-docker workflow to push for ARM platforms

---

packages/hoppscotch-app/src/components/firebase/Login.vue
packages/hoppscotch-app/src/helpers/fb/auth.ts

If an account linking error happens, new logic finds out the account and links it. Dead code related to linking accounts have been deleted.

fix: find linked account from authentication error and link it

---

packages/hoppscotch-app/locales/en.json
packages/hoppscotch-app/src/components.d.ts
packages/hoppscotch-app/src/components/app/Footer.vue
packages/hoppscotch-app/src/components/app/Header.vue
packages/hoppscotch-app/src/components/teams/Team.vue
packages/hoppscotch-app/src/helpers/backend/gql/queries/GetInviteDetails.graphql
packages/hoppscotch-app/src/pages/join-team.vue
packages/hoppscotch-app/src/pages/profile.vue

Description
use email as fallback for display name in profile picture initials

feat: use email as fallback for display name

---

packages/hoppscotch-app/src/components/http/BodyParameters.vue
packages/hoppscotch-app/src/helpers/utils/EffectiveURL.ts

`form-data` param have following properties - 
```
{
active: boolean,
key: string,
value: string,
isFile: boolean,
value: array
}
```
There was a check to remove blank parameter. This check is based on `key`.
However, in case of file upload - `key` is empty but `isFile` is set to True.
This PR updates those checks.

fix: allow posting empty key files in multipart/form-data

---

packages/hoppscotch-app/src/components/smart/EnvInput.vue

Closes #2823 
This PR fixes the issue where some codemirror fields doesn't wrap and pushes the UI elements away when overflowing.

fix: codemirror field overflow

---

packages/hoppscotch-app/src/helpers/import-export/import/hopp.ts

This PR fixes the issue when importing a hoppscotch collection (both my and teams) produced an `invalid format` error failing in importing the collections.

fix: import hopp collection

---

packages/hoppscotch-app/package.json
packages/hoppscotch-app/vite.config.ts
pnpm-lock.yaml

**Before**
we were using String.prototype.replaceAll at some places, but some people where using old browsers without it.
**After**
this PR adds the polyfill for replaceAll

chore: add polyfill for replaceAll

---

packages/hoppscotch-app/src/components/lenses/renderers/JSONLensRenderer.vue

**Before**
Calling `tippyActions.focus()` was failing because tippyActions was a ref inside a v-for, and hence an array of tippyActions refs.
**After**
Use indexes to access refs inside a v-for

fix: errors on opening json outline

---

packages/hoppscotch-app/src/helpers/editor/linting/gqlQuery.ts

fixes HOPPSCOTCH-APP-33
**Before**
1. Go to the graphql page
2. Connect
3. Send a valid request
4. Make some spelling errors
5. Send the request
6. We get a `Mark decorations may not be empty` error
**After**
This PR fixes it

fix: linting erroring out on graphql queries

---

packages/hoppscotch-app/assets/scss/styles.scss
packages/hoppscotch-app/src/components/environments/index.vue
packages/hoppscotch-app/src/components/environments/my/Details.vue
packages/hoppscotch-app/src/components/environments/my/index.vue
packages/hoppscotch-app/src/components/environments/teams/Details.vue
packages/hoppscotch-app/src/components/environments/teams/index.vue
packages/hoppscotch-app/src/components/smart/EnvInput.vue
packages/hoppscotch-app/src/helpers/actions.ts
packages/hoppscotch-app/src/helpers/editor/extensions/HoppEnvironment.ts
packages/hoppscotch-app/src/helpers/editor/themes/baseTheme.ts

Closes #2607 
- Adds edit action on environment variable tooltip:
- When the edit icon is clicked, the environment edit modal is opened with the variable value auto selected
- Implements two new actions handler to invoke the environment edit modals;
- Changes the approach on `environments/index.vue` to conditionally render env components to use v-show instead of v-if, so the modals can be called even when the correspondent tab is not active;
- Adds option to pass parameters to `invokeAction` method
- Adds `selectText` prop to EnvInput so it can auto select the text on the input when it's rendered

Feat: Add inline environment variable edit

---

packages/hoppscotch-app/src/components.d.ts
packages/hoppscotch-app/src/components/collections/ChooseType.vue
packages/hoppscotch-app/src/components/environments/ChooseType.vue
packages/hoppscotch-app/src/components/environments/index.vue
packages/hoppscotch-app/src/components/environments/my/Details.vue
packages/hoppscotch-app/src/components/environments/my/Environment.vue
packages/hoppscotch-app/src/components/environments/my/index.vue

This PR moves the global environment above the environment type selection toggle so that it's visible in both my and team's environment state. It also fixes an issue where the environment state does not revert back to my environment when the user logs out.
**Before**
**After**

refactor: move global env to top in UI

---

packages/hoppscotch-app/src/composables/codemirror.ts

**Before**
We added some sentry debug info, to figure out an edge case bug
**After**
This PR removes those info, since the bug is found and fixed

chore: remove unwanted debug info

---

packages/hoppscotch-app/src/components/http/BodyParameters.vue

fixs #2859
**Before**
See the mentioned issue for more info.
we were using ```Array.splice``` to remove an element from an array. but this was not triggering a watcher on the array.
**After**
we now use ```Array.filter``` to remove an element from an array and the reactivity works

fix: delete not working properly on request body

---

packages/hoppscotch-common/src/components/history/index.vue

**Before**
After Loading a request from user's hoppscotch history, changes to the request body where not taking effect. this is happening, because we are calling `setRequest` with a computed property, which is readonly.
**After**
We pass the computed property as a normal object to `setRequest` which fixes the issue.

fix: cannot write to body when a request is loaded from history

---

packages/hoppscotch-common/src/components.d.ts
packages/hoppscotch-common/src/components/app/ActionHandler.vue
packages/hoppscotch-common/src/components/app/Footer.vue
packages/hoppscotch-common/src/layouts/default.vue

Closes #2890 
This PR resolves the issue where the login panel was not visible on phone screens. The issue was addressed by moving all modals from the `Footer` component to a new component called `ActionHandler`, which contains the `defineActionHandler` functions. This new component was then imported into the `default` layout component, ensuring that it will be rendered on all devices.

fix: login modal not visible in small screen

---

packages/hoppscotch-common/src/components/collections/graphql/Collection.vue
packages/hoppscotch-common/src/components/collections/graphql/Request.vue

This PR fixes the bug in graphQl save request modal which the emitted payload was sent incorrectly, the type was changed in #2865.

fix: graphql save request emit payload

---

packages/hoppscotch-common/src/components/http/Response.vue
packages/hoppscotch-common/src/components/http/ResponseMeta.vue
packages/hoppscotch-common/src/components/lenses/HeadersRenderer.vue
packages/hoppscotch-common/src/components/lenses/HeadersRendererEntry.vue
packages/hoppscotch-common/src/components/lenses/ResponseBodyRenderer.vue
packages/hoppscotch-common/src/helpers/types/HoppRESTResponse.ts

Closes #2080 
Intended to be follow up of https://github.com/hoppscotch/hoppscotch/pull/2915
[Excerpt from #2915]
When the ResponseBodyRenderer component renders for each request, the active tab (json, raw etc) is always set to the first one. Users prefer if same tab is persisted. So I moved tab preferences from ResponseBodyRenderer to parent so it loads with previously opened tab.
ResponseBodyRenderer had response props of `{ type: Object, default: () => ({}) }`. Updated to `{ type: Object as PropType<HoppRESTResponse> | null }` instead. 
Which uncovered that `headers` prop in `HeadersRendererEntry.vue` and `header` prop in `HeadersRenderer.vue` were wrongly given as `HoppRESTHeader` (it has key, value, active properties). Updated those to the `HoppRESTResponseHeaderKV` type.
In …

feat: active tab no longer resets after request

---

packages/hoppscotch-common/src/components/http/Request.vue
packages/hoppscotch-common/src/helpers/strategies/ExtensionStrategy.ts
packages/hoppscotch-common/src/shims.d.ts

Closes #2897
The reported bug was in the extension. If one request had failed to return a response, second request shows a huge response time and threw an error. We guessed some object whose reference was shared between requests. Calling the `cancelRequest()` on the extension fixed the response time problem and the error.
Fixed the typing interface for `window.__POSTWOMAN_EXTENSION_HOOK__` with correct [method name](https://github.com/hoppscotch/hoppscotch-extension/blob/main/src/index.ts#L265) . Exported the `window` typing, seems it wasn't previously doing anything.

fix: response time for requests via extension has incorrect value

---

packages/hoppscotch-common/src/helpers/fb/index.ts
packages/hoppscotch-common/src/platform/environments.ts
packages/hoppscotch-common/src/platform/index.ts
packages/hoppscotch-web/src/environments.ts
packages/hoppscotch-web/src/main.ts

This PR extracts out the environments firebase syncing to hoppscotch-web, and defines the common interface to be used with other hoppscotch platforms.

chore: move environments firebase things to hoppscotch-web

---

packages/hoppscotch-common/src/components/environments/my/Details.vue
packages/hoppscotch-common/src/components/environments/my/Environment.vue
packages/hoppscotch-common/src/index.ts
packages/hoppscotch-common/src/newstore/environments.ts

**Before**
1. the `createEnvironment` store action did not support variables as parameters, we were using two actions `createEnvironment` and `updateEnvironment` just for creation.
2. there existed an edge case where the GQLClient was not initialized when `runGqlSubscription` was called, which caused the subscription to not run 
**After**
1. `createEnvironment` store action accepts optional variables parameter.
2. Updated the order of initializing GQLClient to prevent `runGqlSubscription` from not running subscription

refactor: optional variables to createEnvironment and fixing the order of initializing GqlClient

---

packages/hoppscotch-common/src/helpers/fb/index.ts
packages/hoppscotch-common/src/platform/collections.ts
packages/hoppscotch-common/src/platform/index.ts
packages/hoppscotch-web/package.json
packages/hoppscotch-web/src/collections.ts
packages/hoppscotch-web/src/main.ts
pnpm-lock.yaml

This PR extracts out the collections firebase syncing to hoppscotch-web, and defines the common interface to be used with other hoppscotch platforms.

chore: move collections sync system to platform

---

packages/hoppscotch-common/src/components.d.ts
packages/hoppscotch-common/src/components/collections/Collection.vue
packages/hoppscotch-common/src/components/collections/MyCollections.vue
packages/hoppscotch-common/src/components/collections/Request.vue
packages/hoppscotch-common/src/components/collections/TeamCollections.vue
packages/hoppscotch-common/src/components/collections/index.vue
packages/hoppscotch-common/src/helpers/teams/TeamCollectionAdapter.ts
packages/hoppscotch-common/src/newstore/collections.ts
packages/hoppscotch-common/src/newstore/reordering.ts

This PR fixes the UI and UX flow fixes for the reordering and moving feature
- disable moving a parent-to-child collection
- ease reorder flow
- increase user feedback while reordering and moving

fix: reordering bugs and UX fixes

---

packages/hoppscotch-common/src/newstore/collections.ts

**Before**
1. You needed the entire collection to call `editCollection`. This was a limitation when handling `UserCollectionEdited` subscription, because we don't have access to the entire collection. Also the only thing we updated was the collection name.
2. `navigateToFolderWithIndexPath` was not exported, but were required in the sync layer
**After**
1. `editCollection` store dispatcher takes a partial collection as an argument, instead of an entire collection
2. `navigateToFolderWithIndexPath` is exported

refactor: store changes for collections

---

packages/hoppscotch-common/src/newstore/collections.ts

before:
editCollection, editFolder dispatchers needed the entire collection to make an edit. this was not ideal when we want to update small part of the collection.
after:
now editFolder and editCollection accepts a partial collection and folder object and merges it with the collection. this is also backward compatible, so no code changes to existing system are needed.

refactor: make editFolder, editCollection take Partial collection as parameter

---

packages/hoppscotch-common/src/helpers/fb/index.ts
packages/hoppscotch-common/src/platform/index.ts
packages/hoppscotch-common/src/platform/settings.ts
packages/hoppscotch-web/src/main.ts
packages/hoppscotch-web/src/settings.ts

This PR extracts out the settings firebase syncing to hoppscotch-web, and defines the common interface to be used with other hoppscotch platforms.

chore: move settings firebase things to platform

---

packages/hoppscotch-common/src/helpers/fb/index.ts
packages/hoppscotch-common/src/platform/history.ts
packages/hoppscotch-common/src/platform/index.ts
packages/hoppscotch-web/src/history.ts
packages/hoppscotch-web/src/main.ts

This PR extracts out the history firebase syncing to hoppscotch-web, and defines the common interface to be used with other hoppscotch platforms.

chore: move history firebase things to hoppscotch-web

---

packages/hoppscotch-common/src/newstore/history.ts

This PR introduces a new dispatcher to history store, that deletes a duplicate history entry given an id, which is used to delete duplicate insertions from subscription or store sync functions.

chore: add removeDuplicateEntry dispatcher to history store

---

packages/hoppscotch-common/src/helpers/backend/gql/queries/GetCollectionChildren.graphql
packages/hoppscotch-common/src/helpers/backend/gql/queries/GetCollectionChildrenIDs.graphql
packages/hoppscotch-web/src/firebase/init.ts
packages/hoppscotch-web/src/main.ts

This PR fixes queries `GetCollectionChildren` and `GetCollectionChildrenIDs` to use IDs instead of Strings for cursor

chore: use IDs instead of Strings in graphql queries

---

packages/hoppscotch-common/src/components/collections/index.vue
packages/hoppscotch-common/src/pages/index.vue

This PR fixes the issue that occurred after the new REST Tab deployment that other pages are not rendering after navigating from the REST page. And fixes the active request delete issue from team collection.

fix: no page rendering issue after navigating from rest page

---

packages/hoppscotch-common/src/components/environments/my/Details.vue
packages/hoppscotch-common/src/components/environments/my/Environment.vue
packages/hoppscotch-common/src/helpers/RequestRunner.ts
packages/hoppscotch-common/src/newstore/environments.ts
packages/hoppscotch-data/src/environment.ts

**Before**
The env store didn't have ids for environments, this created challenges when syncing these changes to the backend.
**After**
This PR adds ids to the environments store, so hoppscotch platform can use ids for syncing if needed. also this change is kept backward compatible.

refactor: add optional ids to environments

---

packages/hoppscotch-common/src/components/collections/graphql/Collection.vue
packages/hoppscotch-common/src/components/collections/graphql/Folder.vue
packages/hoppscotch-common/src/components/collections/graphql/Request.vue
packages/hoppscotch-common/src/components/collections/index.vue
packages/hoppscotch-common/src/newstore/collections.ts
packages/hoppscotch-data/src/graphql/index.ts

This PR introduces changes to support ID based syncing for collections.
**Changes**
- `removeGraphqlCollection`, `removeGraphqlFolder`, `removeGraphqlRequest`, `removeRestCollection`, `removeRestFolder`, `removeRestRequest` all accepts an optional id. this id is not used in the store right now. but is used in the syncing system for removing these resources.
- Function for removing duplicates from the collections store

chore: changes to support id based syncing for collections

---

.env.example

Closes # 
This PR introduces the fix to change the value of the `GOOGLE_SCOPE` env variable from its previously incorrect value to the right value now.

fix: fixed incorrect GOOGLE_SCOPE env value in .env.example file

---

packages/hoppscotch-common/assets/scss/styles.scss

Whenever you switch tabs, refresh page, or opens up a collapsed pane - you could see the horizontal pane slides up with a 200ms transition. This is causing a layout shift and an unpleasant UX while working with multiple tabs (eg: REST page).
I've turned off this behaviours by setting the transition property to none.
| --- | --- |
| <video src="https://user-images.githubusercontent.com/10395817/231997245-7736c5e5-6f64-449b-8c28-bd28d1fcda4f.webm"> | <video src="https://user-images.githubusercontent.com/10395817/231999448-8b3362dd-ff23-4d65-980a-23f6e9ad27d8.webm"> |

fix: unwanted transitions caused pane layout shift

---

packages/hoppscotch-common/src/components/collections/index.vue
packages/hoppscotch-common/src/components/http/TestResult.vue
packages/hoppscotch-common/src/components/teams/Edit.vue
packages/hoppscotch-common/src/components/teams/Invite.vue
packages/hoppscotch-common/src/components/teams/index.vue
packages/hoppscotch-common/src/components/workspace/Selector.vue
packages/hoppscotch-sh-admin/src/components/teams/Invite.vue
packages/hoppscotch-sh-admin/src/components/teams/Members.vue
packages/hoppscotch-sh-admin/src/components/teams/PendingInvites.vue
packages/hoppscotch-ui/src/components/smart/FileChip.vue

We're using [unplugin-icons](https://github.com/antfu/unplugin-icons) to load icons as components on-demand.
This PR changes all instances of manual icon imports to leverage unplugin-icons' [auto Importing](https://github.com/antfu/unplugin-icons#auto-importing) feature.

chore: use auto-imported icons

---

packages/hoppscotch-common/package.json
pnpm-lock.yaml

Closes #2877
This PR fixes an issue with package `lossless-json` on v1.0.5 where `LJSON.parse()` was producing non-prettified output on large JSON objects. Upgraded to v2.0.8 which includes the fix for this issue.
Fix was suggested by @jaysoni-ash42 on https://github.com/hoppscotch/hoppscotch/issues/2877#issuecomment-1514635577.

fix: non-prettified output on large JSON objects

---

packages/hoppscotch-common/src/components/collections/SaveRequest.vue

This fixes the issue in the save request modal where the request name was not being updated while saving the current active tab request.

fix: request name not updating in the save request modal

---

packages/hoppscotch-ui/src/components/smart/Windows.vue

Issue: If multiple tabs are opened, and the first tab is selected. after going to another page from the REST page and then coming back to REST, the selection goes to the next tab.
Previously, we were forcefully selecting the first possible `Window` forcefully after removing any active `Window`. And it was happening `onBeforeUnmounted`. But, now it will select the last `Window` automatically.

fix: wrong tab selected after navigating from different route

---

packages/hoppscotch-common/assets/scss/styles.scss
packages/hoppscotch-common/src/layouts/default.vue

Closes #2994 
Fixed the disappearing request issue when opening tabs for requests with long text by adding the CSS class 
`.flex{ min-width: 0; }`. 
The fix ensures that the request remains visible and accessible by modifying the layout and styling of the request tabs.

Fix issue with disappearing tab when opening request tabs with long text in body/script

---

packages/hoppscotch-backend/src/auth/helper.ts

Fixes #3024 
Close HBE-191
So, whenever the `{BASE_URL}/v1/auth/verify` API was called, the `response` object was written with cookies. Afterward, the server sends a response to the client with conditional redirection. During sending the response, the backend service encounters the following error.
```
[Nest] 123  - 04/28/2023, 10:12:23 AM   ERROR [ExceptionsHandler] Cannot set headers after they are sent to the client
Error: Cannot set headers after they are sent to the client
at new NodeError (node:internal/errors:393:5)
at ServerResponse.setHeader (node:_http_outgoing:607:11)
at ServerResponse.header (/usr/src/app/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/response.js:794:10)
at ServerResponse.location (/usr/src/app/node_modules/.pnpm/express@4.18.2/node_modules/express/ …
```

fix: returning response from authCookieHandler

---

packages/hoppscotch-backend/src/auth/auth.service.ts

Fixes #3016 
Closes HBE-195
During the *Sign In* with the magic-link option, the user gets an email with a link (embedded with a token).
The path/route of the magic link was mismatched with the front-end application. For that reason, users are getting 404 error in the front-end application and are unable to sign in to the application successfully.
In this PR, we fixed the magic link (path/route), which was sent through email. After this fix, the user will be able to sign in to the application successfully.
Nil

fix: magic link URL

---

packages/hoppscotch-ui/src/components/smart/Windows.vue

Improved the tab head section. When a tab selection is updated automatically (like when we click on a request in a collection which has a tab open or we click on add new tab button), the tab headers section should scroll to show the new active tab header.
* Import and use `nextTick` function from `vue` to manipulate scroll position of tab container based on active tab ID ([link](https://github.com/hoppscotch/hoppscotch/pull/3013/files?diff=unified&w=0#diff-052acc17f6ece720f660d3841f7e49f0a3a1d6ad68dc973819e3d758e45141d5L134-R142), [link](https://github.com/hoppscotch/hoppscotch/pull/3013/files?diff=unified&w=0#diff-052acc17f6ece720f660d3841f7e49f0a3a1d6ad68dc973819e3d758e45141d5R307-R333))
* Define and use `TAB_WIDTH` constant to calculate tab container width and tab position …

feat: scroll to show the new active tab header

---

packages/hoppscotch-common/src/components/smart/EnvInput.vue
packages/hoppscotch-common/src/composables/codemirror.ts
packages/hoppscotch-common/src/platform/ui.ts

This PR adds an optional `onCodemirrorInstanceMount` hook to platform. this hook runs after the codemirror view is inited. which is helpful to run code after codemirror instances are mounted.

chore: add onCodemirrorInstanceMount hook to platform

---

packages/hoppscotch-common/src/newstore/environments.ts

Closes HFE-40
**Before**
If we're loading an environment index that doesnt exist from the localstorage, it could lead to unwanted behaviours.
the type for `currentEnvironment$` was not considering the enviornment could be undefined.
**After**
When setting the selectedEnvironmentIndex, we verify if the environment corresponding to the index exist in the store. Otherwise we set selectedEnvironmentIndex for 'NO_ENV_SELECTED'
Also we update the type of currentEnvironment$ to include a possible undefined

fix: invalid environment index can break the app

---

packages/hoppscotch-common/src/components/collections/SaveRequest.vue
packages/hoppscotch-common/src/components/http/Request.vue
packages/hoppscotch-common/src/components/http/Response.vue

The current tab system breaks when a user creates a new tab while waiting for a response in another tab. This issue causes unexpected behavior and impacts user experience.
This pull request fixes the issue by implementing a check for pending requests `onBeforeUnmount` in the active tab. If a pending request is found, cancel the request.

fix: tab system breaks when a new tab is created while waiting for response in another tab

---

packages/hoppscotch-backend/src/user-history/user-history.service.spec.ts

Closes HBE-194
In this PR, we fix a unit test issue for the backend by which the build was being failed.
```
packages/hoppscotch-backend do-test:     - Expected Right  - 1
packages/hoppscotch-backend do-test:     + Received Right  + 1
packages/hoppscotch-backend do-test:       Object {
packages/hoppscotch-backend do-test:     -   "executedOn": 2023-04-23T10:19:35.258Z,
packages/hoppscotch-backend do-test:     +   "executedOn": 2023-04-23T10:19:35.257Z,
packages/hoppscotch-backend do-test:         "id": "1",
packages/hoppscotch-backend do-test:         "isStarred": false,
packages/hoppscotch-backend do-test:         "reqType": "REST",
packages/hoppscotch-backend do-test:         "request": "[{}]",
packages/hoppscotch-backend do-test:         "responseMetadata": "[{}]", …
```

fix: timing dependency on test case

---

packages/hoppscotch-ui/src/components/smart/AutoComplete.vue

HFE-47
The auto-complete component used to cut off the part that's already been typed. This PR fixes that UX and keeps the characters that are already typed.

fix: don't cut off the part that's already been typed

---

packages/hoppscotch-common/src/helpers/keybindings.ts

🐛🌐⌨️
Fixed a keybinding bug for different keyboard layouts by using `ev.code` instead of `ev.key` in `getPressedKey` function. This affects the file `packages/hoppscotch-common/src/helpers/keybindings.ts`.
Keyboard event for any letters starts with `Key` in `code` property. And after `Key` it contains original letter. eg: if we press `Option+Q` the mac default key would be `Option+œ` but inside code property it would be `Option+KeyQ`. So, only for letters we are checking from `code` instead of `key`
> _`ev.code` not `key`_
> _Fixes keyboard layout bug_
> _Autumn leaves falling_
* Fix keybinding bug for different keyboard layouts by using `ev.code` instead of `ev.key` to check for letter keys ([link](https://github.com/hoppscotch/hoppscotch/pull/3058/files?diff=unified&w=0#diff-1739024c7f2b …

fix: dead key issue in mac

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components/lenses/renderers/AudioLensRenderer.vue
packages/hoppscotch-common/src/components/lenses/renderers/VideoLensRenderer.vue
packages/hoppscotch-common/src/helpers/lenses/audioLens.ts
packages/hoppscotch-common/src/helpers/lenses/lenses.ts
packages/hoppscotch-common/src/helpers/lenses/videoLens.ts

Closes #2951
Adds support to audio and video API responses.
Introduced `VideoLensRenderer`, `videoLens` and `AudioLensRenderer`, `audioLens` components to render various popular/standard [audio](https://www.iana.org/assignments/media-types/media-types.xhtml#audio) and [video](https://www.iana.org/assignments/media-types/media-types.xhtml#video) MIME types.
**Preview**
| Audio | Video |
|-|-|
| <img width="1470" alt="Screenshot 2023-05-09 at 9 05 56 PM" src="https://github.com/hoppscotch/hoppscotch/assets/10395817/76a7efeb-aab5-44b0-9ad2-2bcc5f2e7a18"> | <img width="1470" alt="Screenshot 2023-05-09 at 9 06 05 PM" src="https://github.com/hoppscotch/hoppscotch/assets/10395817/8979dcd2-785e-47b5-9591-baa2ea36f620"> |
The current implementation of rich media types including the new audio and …

feat: add support to audio and video API responses

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components/collections/EditRequest.vue
packages/hoppscotch-common/src/components/collections/index.vue
packages/hoppscotch-common/src/pages/index.vue

🖊️🚀🎨
Added a feature to rename requests in `index.vue`. Users can double-click on a request name and enter a new name in a modal dialog.
*  Add a feature to rename the request name by double-clicking on it ([link](https://github.com/hoppscotch/hoppscotch/pull/3057/files?diff=unified&w=0#diff-fad0a5fd18efa5e20c31a16edf95ad374d774283c5e75a09e7e35fbd7906ea08R26), [link](https://github.com/hoppscotch/hoppscotch/pull/3057/files?diff=unified&w=0#diff-fad0a5fd18efa5e20c31a16edf95ad374d774283c5e75a09e7e35fbd7906ea08R65-R103), [link](https://github.com/hoppscotch/hoppscotch/pull/3057/files?diff=unified&w=0#diff-fad0a5fd18efa5e20c31a16edf95ad374d774283c5e75a09e7e35fbd7906ea08R159-R160), [link](https://github.com/hoppscotch/hoppscotch/pull/3057/files?diff=unified&w=0#diff-fad0a5fd18efa5e20c31a16edf95 …

feat: rename request by double clicking its name on tabs

---

packages/hoppscotch-common/assets/scss/styles.scss
packages/hoppscotch-ui/src/components/smart/Picture.vue

This PR fixes getting the 403:forbidden error when trying to load a Google profile picture from localhost.

fix: 403 forbidden error when trying to load a Google profile picture

---

packages/hoppscotch-common/package.json
packages/hoppscotch-common/src/components/http/RawBody.vue
packages/hoppscotch-common/src/composables/codemirror.ts
packages/hoppscotch-common/src/helpers/curl/sub_helpers/contentParser.ts
pnpm-lock.yaml

Closes #3066 
Closes HP-26
This PR adds the feature to prettify the XML response.
I have used [xml-formatter](https://www.npmjs.com/package/xml-formatter?activeTab=readme) for pretty print the XML.

feat: prettify XML response

---

.env.example

Closes hfe-58
Our environment file currently includes a WSS URL (WebSockets Sequer URL). However, while testing on localhost, this will fail ( none of our subscriptions will work ) because you need to set up certificates and run a WSS server on your local machine. To prevent this, we recommend that the local server URL in the environment file default to using WebSockets instead of the WSS protocol.

chore: update wss url to ws in .env.example

---

packages/hoppscotch-common/src/components/environments/my/Details.vue
packages/hoppscotch-common/src/components/environments/teams/Details.vue
packages/hoppscotch-common/src/components/http/TestResult.vue

Closes HFE-54
This PR adds the option to set an environment from the test and save it as a team environment if the team workspace is selected.
When using the test `pw.env.set("variable", "value");` saves the environment to the 'My Environments' or to the 'Global' even the current workspace is selected as team.
Now when using the `pw.env.set("variable", "value");` sets the environment automatically to the selected team environment and personal environments respectively checking the current workspace status.

fix: set team environment from test

---

packages/hoppscotch-common/src/components/environments/Selector.vue
packages/hoppscotch-common/src/components/environments/index.vue
packages/hoppscotch-common/src/components/environments/my/index.vue
packages/hoppscotch-common/src/components/environments/teams/index.vue
packages/hoppscotch-common/src/pages/index.vue
packages/hoppscotch-ui/src/components/smart/Windows.vue

Closes HFE-64
This is a continuation of reverting the environment selector component back to its original features with the new design language that we follow at Hoppscotch. Users can now switch between "My environments" and "Team environments" on a Tab UI within the Environment selector popover.
TLDR; allows users to switch to personal environments from team workspaces.

chore: environment selector with new ux

---

packages/hoppscotch-common/src/newstore/syncing.ts
packages/hoppscotch-common/src/pages/index.vue

Closes HFE-46
This PR fixes the issue where popup for workspace restoration was firing multiple times when navigating from other pages and returning back to the REST page and on some other occasions.

fix: sync popup firing multiple times

---

packages/hoppscotch-backend/src/team-invitation/team-invitation.service.ts

Closes # HBE-202 - [Bug] - Incorrect Invite Link in Team invitation
Currently if we invite a user to join a team through team invitation the invite link generated points to - `https://hoppscotch.io/join-team?id=##` instead it should point to `https://your-domain/join-team?id=##` based on the config in the `.env` file.
As reported in the issue - https://github.com/hoppscotch/hoppscotch/issues/3078
##Testing Instructions: 
1. Create a team and then invite a user using their email and role in the team
2. Check the mailbox for the invite link it should be in the format `https://your-domain/join-team?id=##` based on env config

Fix: Update team invitation link to domain specified in .env [HBE-202]

---

packages/hoppscotch-common/src/helpers/RESTExtURLParams.ts
packages/hoppscotch-common/src/pages/index.vue

fixes #3098
fixes HFE-71
**Before**
We support loading request properties from URL query params. we have a function `translateExtURLParams` that takes query params and converts it into Hoppscotch request properties, but this function was always adding these properties to the default request. so whenever a query param is present, this function is running, and it overwrites the existing request.
**After**
This function takes an optional `initialRequest` parameter that will be used instead of the defaultRequest if passed.

fix: fix url getting overridden when query params are present

---

packages/hoppscotch-common/locales/vi.json

all in vietnamese should be translated to "tất cả", I fix the typo of this.

vi fix typo in translation of clear_all

---

packages/hoppscotch-backend/src/team-invitation/team-invite-viewer.guard.ts
packages/hoppscotch-backend/src/team-invitation/team-invitee.guard.ts

Closes issue #3090
This PR fixes a bug with the auth guards present in the TeamInvitation module where new users trying to join a team with a valid invitation could not do so and be presented with the *BUG_AUTH_NO_USER_CTX* error instead.
Have a normal running instance of SH running with one valid user account then:
- Create a new team and Invite a new user whose account does not exist in the DB into the team.
- Create the account for the user to whom you sent the invite link in the earlier step.
- Make sure to be logged in as the newly created user click on the button in the email you received before to join the team.
- You should see the error being thrown.
HBE-227
Nil

fix: fixed issue with team-invitations and new user accounts

---

packages/hoppscotch-common/.eslintrc.js
packages/hoppscotch-common/package.json
packages/hoppscotch-common/src/helpers/__tests__/editorutils.spec.js
packages/hoppscotch-common/src/helpers/__tests__/jsonParse.spec.js
packages/hoppscotch-common/src/helpers/__tests__/platformutils.spec.js
packages/hoppscotch-common/src/helpers/curl/__tests__/curlparser.spec.js
packages/hoppscotch-common/src/helpers/curl/__tests__/detectContentType.spec.js
packages/hoppscotch-common/src/helpers/strategies/__tests__/AxiosStrategy-NoProxy.spec.js
packages/hoppscotch-common/src/helpers/strategies/__tests__/AxiosStrategy-Proxy.spec.js
packages/hoppscotch-common/src/helpers/strategies/__tests__/ExtensionStrategy-NoProxy.spec.js
packages/hoppscotch-common/src/helpers/utils/__tests__/b64.spec.js
packages/hoppscotch-common/src/helpers/utils/__tests__/contenttypes.spec.js
packages/hoppscotch-common/src/helpers/utils/__tests__/debounce.spec.js
packages/hoppscotch-common/src/helpers/utils/__tests__/uri.spec.js
packages/hoppscotch-common/src/helpers/utils/__tests__/valid.spec.js
packages/hoppscotch-common/src/newstore/__tests__/DispatchingStore.spec.js
packages/hoppscotch-common/src/setupTests.ts
packages/hoppscotch-common/src/vitest.d.ts
packages/hoppscotch-common/tsconfig.json
packages/hoppscotch-common/vitest.config.ts
pnpm-lock.yaml

Closes HFE-83
This PR reintroduces test runs for `hoppscotch-common` and port the old Jest unit test scripts to work with [Vitest](https://vitest.dev/).
- Add `do-test` entry for `hoppscotch-common` so it can integrate with repo-wide test runs.
- Introduce `test` and `test:watch` scripts to `hoppscotch-common` so we can run vitest for a single run or on watch mode.
- Introduce `vitest` as dev dependency to `hoppscotch-common`
- Introduce `setupTests.ts` where couple of [custom matchers](https://vitest.dev/guide/extending-matchers.html) (pertaining to fp-ts constructs) are added.
- Introduce `vitest.d.ts` to extend the typescript types for the custom matchers.
N/A

refactor: move hoppscotch-common tests to vitest

---

packages/hoppscotch-common/src/components/collections/MyCollections.vue
packages/hoppscotch-common/src/components/collections/TeamCollections.vue

Closes HFE-109
There was a small background color mismatch in the collection tree, this PR fixes this issue.

fix: unified bg color in collection tree

---

packages/hoppscotch-common/src/components/http/Headers.vue
packages/hoppscotch-common/src/components/http/RequestOptions.vue
packages/hoppscotch-common/src/helpers/curl/sub_helpers/url.ts

Fixes #3109 
**Before**
We were not respecting the `--location` parameter when parsing the curl request.
**After** 
Respect the `--location` parameter when parsing the curl request.
**Before**
In component `RequestOptions.vue`, we have a ref `request` which is set to `props.modelValue` in the setup function. but when the component updates with new props, this is not updated. this caused child components that uses this `request` ref to not get updated reactively.
**After**
Added a watcher that updates the `request` ref, when the props change.

fix: use --location param for url when parsing curl

---

.env.example
packages/hoppscotch-backend/src/auth/strategies/microsoft.strategy.ts

Closes #3050 #3139 
The `passReqToCallback=true` alters the arguments passed to `MicrosoftStrategy.validate` such that first argument is a `request` object and other arguments are shifted across one. This meant that actual values for `accessToken` and critically `profile` weren't in the expected arguments and therefore the rest of the method would break. I believe `passReqToCallback` was added in error in 81cb0d43d78e41a3ce1e82260a10fa9baedfbc64. This method could never work in it's current form with this option set to true.
This has been tested (and previously debugged) on a private instance of hopscotch so I can confirm that this method does now indeed work in "production"
Many orgs using Azure AD will be running on their own "tenants" rather than the "common" tenant, and therefore need …

fix: Self-host unable to use Azure oauth

---

packages/hoppscotch-common/src/components/collections/ImportExport.vue
packages/hoppscotch-common/src/components/collections/SaveRequest.vue
packages/hoppscotch-common/src/components/collections/graphql/Add.vue
packages/hoppscotch-common/src/components/collections/graphql/ImportExport.vue
packages/hoppscotch-common/src/components/collections/graphql/index.vue
packages/hoppscotch-common/src/components/collections/index.vue
packages/hoppscotch-common/src/components/environments/ImportExport.vue
packages/hoppscotch-common/src/components/environments/my/Details.vue
packages/hoppscotch-common/src/components/environments/teams/Details.vue
packages/hoppscotch-common/src/components/graphql/Request.vue
packages/hoppscotch-common/src/components/graphql/RequestOptions.vue
packages/hoppscotch-common/src/components/http/CodegenModal.vue
packages/hoppscotch-common/src/components/http/ImportCurl.vue
packages/hoppscotch-common/src/components/http/Request.vue
packages/hoppscotch-common/src/components/teams/Add.vue
packages/hoppscotch-common/src/helpers/realtime/MQTTConnection.ts
packages/hoppscotch-common/src/helpers/realtime/SIOConnection.ts
packages/hoppscotch-common/src/helpers/realtime/SSEConnection.ts
packages/hoppscotch-common/src/helpers/realtime/WSConnection.ts
packages/hoppscotch-common/src/helpers/rest/tab.ts
packages/hoppscotch-common/src/pages/r/_id.vue
packages/hoppscotch-common/src/platform/analytics.ts

Closes HFE-112
This PR introduces more events into the analytics pipeline as outlined by the `analytics.ts` definition.
This PR drops `logHoppRequestRunToAnalytics` in favor of a general `logEvent` function that can accept analytics data.
N/A

feat: introduce more events into the analytics pipeline

---

packages/hoppscotch-common/assets/icons/star-off.svg
packages/hoppscotch-common/src/components/history/graphql/Card.vue
packages/hoppscotch-common/src/components/history/rest/Card.vue

Created a new `star-off.svg` (packages/hoppscotch-common/assets/icons/star-off.svg) icon component to show when history entries are stared and updated the star icons for both REST and GraphQL history cards to use this custom icon. This improves the consistency and appearance of the history cards. [Lucide](https://lucide.dev) icons don't have a filled star icon.

chore: new filled star icon to toggle favorite history entry

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components.d.ts
packages/hoppscotch-common/src/components/app/Shortcuts.vue
packages/hoppscotch-common/src/components/http/Request.vue
packages/hoppscotch-common/src/components/smart/EnvInput.vue

Closes #3087 
Closes HFE-66
This PR adds the autocomplete feature to the SmartEnv component which helps in adding a autocomplete to the URL input bar where the latest 10 history entries are shown.

feat: auto-complete recent history entries in URL bar

---

packages/hoppscotch-ui/package.json
packages/hoppscotch-ui/src/components/smart/Anchor.vue
packages/hoppscotch-ui/vite.config.ts
pnpm-lock.yaml

Closes HFE-57 #2999 
- This PR updates `vite-plugin-dts` packages version to `3.2.0`. The previous version was having issues building the `hoppscotch-ui` package.
- Updated `Anchor.vue` component to `setup` script

fix: update vite-plugin-dts version which fixes build issue on docker/alpine

---

packages/hoppscotch-common/package.json
packages/hoppscotch-selfhost-web/vite.config.ts

**Before**
We were using an workaround with the generateSitemap plugin.
see https://github.com/jbaubree/vite-plugin-pages-sitemap/issues/173 for context.
**After**
thanks to the package authors fixing the need for the workaround in v1.4.5, we have removed the workaround

chore: update generateSitemap usage

---

docker-compose.yml

Run database migration on docker-compose up.
Add docker-compose healthcheck for hoppscotch-backend. 
Remove volume to fix `MODULE_NOT_FOUND` error.
Closes #2999
1. Applies the database migration after the database is ready, and before the `hoppscotch-backend` application starts. 
2. Removes unnecessary volumes which results in `MODULE_NOT_FOUND` and/or permission errors.

fix: Add healthcheck for hoppscotch-db in docker-compose, and more

---

packages/hoppscotch-common/src/helpers/keybindings.ts

- Prioritization of key bindings was preventing to run browser's default shortcuts
- Only available modifier was  `type ModifierKeys = "ctrl" | "alt" | "ctrl-shift" | "alt-shift"`
- Running browser's default shortcuts issue fixed
- Extended modifier to `type ModifierKeys = "ctrl" | "alt" | "ctrl-shift" | "alt-shift" | "ctrl-alt" | "ctrl-alt-shift"`
* Extend `ModifierKeys` type to support more keybindings ([link](https://github.com/hoppscotch/hoppscotch/pull/3163/files?diff=unified&w=0#diff-1739024c7f2b818baf3371ad86dfd3f41e18acfc2da76778f3d545832beb4de6L17-R23))
* Refactor `getActiveModifier` function to use object and filter ([link](https://github.com/hoppscotch/hoppscotch/pull/3163/files?diff=unified&w=0#diff-1739024c7f2b818baf3371ad86dfd3f41e18acfc2da76778f3d545832beb4de6L146-R165)) …

fix: keybinding modifier issue

---

packages/hoppscotch-common/src/components.d.ts
packages/hoppscotch-ui/src/components/smart/Windows.vue

Closes HFE-74
This PR fixes the issue of showing the default `scrollbar-thumb` instead of the custom one on Firefox for HoppUI Windows Scrollbar.

fix: firefox browser scrollbar issue

---

packages/hoppscotch-backend/src/admin/admin.resolver.ts
packages/hoppscotch-backend/src/admin/admin.service.ts

Closes # HBE-233
Currently Admins can view pending invitations for a team, but they can't revoke an invitation. This PR introduces a mutation to revoke a team invite by invite ID that will be used from the admin dashboard.
Testing Instructions:
- Create a team and invite users by email
- get pending invitations for the team by team ID
- use `revokeTeamInviteByAdmin` mutation with a invite ID

[feat] : Allow admins to revoke a team invite (HBE-230)

---

.env.example
packages/hoppscotch-backend/src/auth/helper.ts
packages/hoppscotch-backend/src/errors.ts
packages/hoppscotch-backend/src/utils.ts

Closes HBE-248
Introducing Seamless Dynamic Authentication Provider Selection
Previously, we relied on the `ALLOWED_AUTH_PROVIDERS` environment variable. However, we recognized a challenge: the frontend applications were unable to access or read this vital piece of information.
To ensure a harmonious connection between the frontend and the backend, we've revamped the environment variable nomenclature. Say hello to `VITE_ALLOWED_AUTH_PROVIDERS` – our new, unified identifier that effortlessly synchronizes authentication provider preferences across the board.
Change .env variable `ALLOWED_AUTH_PROVIDERS` -> `VITE_ALLOWED_AUTH_PROVIDERS`

HBE-248 feat: prefix VITE_ added in conditional auth provider env variable 

---

packages/hoppscotch-common/src/components/app/spotlight/entry/GQLRequest.vue
packages/hoppscotch-common/src/components/app/spotlight/entry/RESTRequest.vue
packages/hoppscotch-common/src/components/app/spotlight/index.vue
packages/hoppscotch-common/src/services/spotlight/searchers/collections.searcher.ts

Closes HFE-121
This PR intends to introduce a Spotlight searcher to search against user collections in REST and GraphQL.
- Registered and introduced a spotlight searcher to search user collections.
- Added `RESTRequest` and `GQLRequest` spotlight entry components.

feat: spotlight collection searcher

---

packages/hoppscotch-common/src/components/firebase/Login.vue

Closes HP-78
**Before**
- All the login methods where hard coded and shown on UI
- Login.vue component was using options api
**After**
- We load the allowed login methods from .env and display them only on the UI
- Converted Login.vue to use Composition API

feat: load allowed login methods from .env

---

packages/hoppscotch-common/src/components/smart/EnvInput.vue

fixs HFE-148
**Before**
Suggestions menu was not displayed when the EnvInput was focused. 
We had an `onClickOutside` handler defined for suggestionsMenu, it hides the suggestions menu. 
But the input div was outside of this suggestions menu, causing the onClickOutside handler to run everytime someone clicked on the input div, which infact hid the suggestions menu.
**After**
Suggestions menu is displayed properly. moved the onClickOutside to target the `autoCompleteWrapper` instead of the suggestions menu.

fix: fix issues in displaying the suggestions menu on EnvInput

---

packages/hoppscotch-common/src/pages/index.vue

Closes HFE-189
This PR fixes the issue when a user right-clicks a tab and renames a nonactive tab, the active tab name gets updated.

fix: tab right click rename bug

---

packages/hoppscotch-backend/src/shortcode/shortcode.service.ts

Closes HBE-258
This hotfix PR solves the fetch shortcode issue. When the request comes for fetchUserShortCodes, the `this.prisma.shortcode.findMany` skip the first data (in default). The correct logic should be, the there is cursor parameter in arg (for pagination), only that time `skip: 1` should pass in the findMany() operation.
Nil

HBE-258 hotfix: skip parameter in findMany in shortcode module

---

packages/hoppscotch-common/src/components/graphql/Query.vue

Closes HFE-191
This PR fixes the issue of highlighting GraphQL Operation.
When multiple operations are in the same Tab we can highlight the operation with a cursor to run. If we run the request we basically defocused the cursor from the query editor. And after focusing on the query editor it doesn't update the operation name for the button. This PR fixed that issue.

fix: graphql operation highlight issue on focus changed

---

packages/hoppscotch-common/src/helpers/keybindings.ts

- Closes HFE-219
- Fixes #3322
- Suppressed #3314
This PR focuses on allowing the keyboard shortcuts in the app to support different keyboard layouts by using the unique key code parameter. This has been tested with QWERTY and DVORAK Keyboard Layouts and it works as expected.
- Example: `CMD/CTRL - C` used to reset the request when using DVORAK Layout which has now been resolved. Only `CMD/CTRL - I` resets the request connection on both QWERTY and DVORAK Layouts

refactor: keyboard shortcuts now supports different keyboard layouts including Dvorak

---

packages/hoppscotch-common/src/components/http/Parameters.vue

This PR aims at fixing a broken link to the [REST API Testing docs](https://docs.hoppscotch.io/documentation/features/rest-api-testing) from the `wiki` button in the search bar that was yielding `404` previously.

fix: broken link to `REST API Testing` docs

---

packages/hoppscotch-common/src/components/app/spotlight/Entry.vue
packages/hoppscotch-common/src/components/app/spotlight/index.vue

When we scroll through spotlight entries there is an unusual behavior caused by mouse cursor position. This PR fixes the issue.
https://github.com/hoppscotch/hoppscotch/assets/26295990/84593051-567f-4c38-8444-6c6990e0c08f

fix: unusual behavior while scrolling through spotlight entries

---

packages/hoppscotch-common/src/components/smart/EnvInput.vue
packages/hoppscotch-common/src/composables/codemirror.ts

Closes HFE-212
This PR fixes the issue with the context menu where the position of the menu was not updating when a user selects a text and scrolls the content, the context menu was fixed to the viewport rather than relative to the selected text.

fix: context-menu position fixed while scrolling

---

packages/hoppscotch-common/src/components/app/Footer.vue
packages/hoppscotch-common/src/components/app/Options.vue
packages/hoppscotch-common/src/layouts/default.vue
packages/hoppscotch-common/src/newstore/settings.ts
packages/hoppscotch-common/src/pages/settings.vue

- Closes HFE-137
This PR aims to remove the Zen mode functionality from the Hoppscotch App.

refactor: remove zen mode from the app

---

packages/hoppscotch-common/src/pages/index.vue

Closes HFE-225
This PR fixes the bug when duplicating a tab where when a user makes changes to a duplicated tab the same change is effected on the tab which is duplicated.

fix: duplicate tab reference bug

---

packages/hoppscotch-common/src/pages/index.vue

Closes HFE-226
This PR fixes the issue where when a user clicks the option 'close all other tabs' the unsaved tabs count was wrong.

fix: dirty tab count incorrect when closing tabs

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components/teams/Invite.vue

Closes HFE-141
With this PR failed and successful invitations are now shown separately after sending invites.

feat: differentiation for successful invites and failed invites

---

packages/hoppscotch-cli/package.json
packages/hoppscotch-cli/src/handlers/error.ts

This PR includes a grammatical correction in the error message displayed when a non-existent file is supplied to the `test` command and the `--env / -e` flag.
> Non-existent file supplied to the `test` command
> Non-existent file supplied to the `--env / -e` flag
N/A

chore(cli): update error message

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components/graphql/RequestOptions.vue
packages/hoppscotch-common/src/helpers/graphql/connection.ts

Closes HFE-210
This PR aims to fix the issue where authorisation headers are not being sent when a subscription is invoked using GraphQL.
Since WebSocket connection do not support sending headers, the headers will be sent as part of the payload in ‘connection_init’

fix: authorisation headers not being sent along with subscriptions when using graphql

---

.devcontainer/devcontainer.json

Make devcontainer copy `.env.example` instead of moving it.
This prevents the example from getting destroyed when the container is booted.
This is useful when the devcontainer is used in a workspace or GitHub Codespace as it means that, when a commit is subsequently made, it does not destroy the `.env.example` file.

chore(fix/devcontainer): make devcontainer copy .env.example

---

packages/codemirror-lang-graphql/package.json
packages/hoppscotch-common/src/composables/graphql.ts
pnpm-lock.yaml

Closes HFE-227
- Fixed the bug in `useGQLQuery` composable that used to execute older `request` even when we pass updated vars
- Fixed the issue while running `pnpm i` from `codemirror-lang-graphql` package by bumping dependencies

fix: gql `teamID` is not passed issue

---

packages/hoppscotch-selfhost-web/meta.ts

Currently, the `content` attribute for meta tags with the following name attributes resolves to `undefined` since they don't follow the expected format while referring to the base URL environment variable.
Fixes HFE-258.
- `image`
- `og:image`
- `twitter:image`
- `msapplication-TileImage`
This PR aims at fixing the usage across the meta entry definitions.

fix: environment variables usage in meta tags

---

packages/hoppscotch-cli/package.json
packages/hoppscotch-cli/src/handlers/error.ts
packages/hoppscotch-cli/src/options/test/env.ts
packages/hoppscotch-cli/src/types/errors.ts
packages/hoppscotch-cli/src/types/request.ts
packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components/environments/my/Environment.vue
packages/hoppscotch-common/src/components/environments/teams/Environment.vue
packages/hoppscotch-common/src/helpers/import-export/export/envToJson.ts
packages/hoppscotch-common/src/helpers/import-export/export/environment.ts
packages/hoppscotch-sh-admin/src/components.d.ts
pnpm-lock.yaml

Closes HFE-203
This PR introduces the following features and fixes to the `Hoppscotch App` and `Hoppscotch CLI`
**Features Added:**
- Added the ability to export single environment variables from the `Hoppscotch App` 
- CLI can now accept environment variables from the format in which the `Hoppscotch App` exports.
- Introduced `Zod` package into the `Hoppscotch CLI` to check the validity of the formats for the Environment variables.
- CLI now informs the user that bulk environment export is not supported by the CLI when the file matches the bulk export format.
**Issues Fixes:**
- Fix the malformed environments error when importing a environment file that was exported from the `Hoppscotch App` to the CLI.   
- Fix the issue when there are are no error messages being given when it is a …

feat: introduces ability to export single environment variables and allow CLI to accept the export format used by the app

---

packages/hoppscotch-common/src/components/app/ActionHandler.vue
packages/hoppscotch-common/src/components/app/Header.vue

Closes HFE-193
Warning added for users trying to delete a team from the spotlight if they don't have any permission to delete the team.
https://github.com/hoppscotch/hoppscotch/assets/25279263/3e6bcea6-bfb6-4bdf-ab68-4627b899fefb

feat: no permission warning added for users except owner while deleting team

---

packages/hoppscotch-common/src/helpers/graphql/connection.ts

With #3367, we moved away from helpers for tab-related functionalities to a service. However, there was a stale import that led to the build failure. This PR fixes it by replacing it with the service implementation. It also organizes imports used in the file.

fix(common): use tab service within helpers

---

packages/hoppscotch-backend/src/team-collection/team-collection.service.spec.ts
packages/hoppscotch-backend/src/user-history/user-history.service.spec.ts

Closes HBE-270
In this PR, we fix the broken test cases regarding timestamp mismatch. We encounterd this issue, when GitHub action runs.
Failure GitHub Action: [https://github.com/hoppscotch/hoppscotch/actions/runs/6312305505/job/17138088088](https://github.com/hoppscotch/hoppscotch/actions/runs/6312305505/job/17138088088)
Nil

HBE-270 Test-Case timestamp issue fix in backend

---

docker-compose.yml
packages/hoppscotch-backend/src/team-environments/team-environments.service.spec.ts
packages/hoppscotch-backend/src/team-environments/team-environments.service.ts

Closes HBE-264
In this PR, we remove all known instances of `rejectOnNotFound` parameter in the Prisma queries using it, this is in order to prepare for the Prisma dependency bump.
none

refactor: removed all instances of `rejectOnNotFound` in prisma queries

---

packages/hoppscotch-selfhost-web/vite.config.ts

Set useCredentials: true in Vite PWA options to prevent 401 errors when accessing the app with a basic HTTP auth.
When using a Basic HTTP Authentication, Google Chrome reports 401 errors when trying to fetch the manifest:  
Vite PWA docs FAQ recommend to use the `useCredentials` option: https://vite-pwa-org.netlify.app/guide/faq.html#web-app-manifest-and-401-status-code-unauthorized.  
This PR does only that.  
This should have no impact except avoiding 401 errors for the manifest.  
A workaround is to open the manifest file in a new tab, then reload the UI, but having this option would make it much easier.

fix(self-hosted/web): add "useCredentials: true" to Vite PWA options

---

packages/hoppscotch-sh-admin/src/components.d.ts
packages/hoppscotch-sh-admin/src/components/teams/Details.vue
packages/hoppscotch-sh-admin/src/components/teams/Invite.vue
packages/hoppscotch-sh-admin/src/components/teams/Members.vue
packages/hoppscotch-sh-admin/src/components/teams/PendingInvites.vue
packages/hoppscotch-sh-admin/src/components/teams/Table.vue
packages/hoppscotch-sh-admin/src/components/users/Table.vue
packages/hoppscotch-sh-admin/src/helpers/backend/gql/queries/InvitedUsers.graphql
packages/hoppscotch-sh-admin/src/helpers/backend/gql/queries/Metrics.graphql
packages/hoppscotch-sh-admin/src/helpers/backend/gql/queries/TeamInfo.graphql
packages/hoppscotch-sh-admin/src/helpers/backend/gql/queries/TeamList.graphql
packages/hoppscotch-sh-admin/src/helpers/backend/gql/queries/UserInfo.graphql
packages/hoppscotch-sh-admin/src/helpers/backend/gql/queries/UsersList.graphql
packages/hoppscotch-sh-admin/src/pages/dashboard.vue
packages/hoppscotch-sh-admin/src/pages/teams/_id.vue
packages/hoppscotch-sh-admin/src/pages/teams/index.vue
packages/hoppscotch-sh-admin/src/pages/users/_id.vue
packages/hoppscotch-sh-admin/src/pages/users/index.vue
packages/hoppscotch-sh-admin/src/pages/users/invited.vue

- Closes HFE-286
- Dependent on #3445 
This PR focuses on updating the backend gql queries and the components used in the Admin Dashboard to now use `infra` type instead of the previously used `admin` type because of the new schema change in the backend.

refactor: updated dashboard gql queries and components to use the new infra type of the updated schema

---

packages/hoppscotch-ui/package.json
pnpm-lock.yaml

**Before**
Our graphql page was crashing and syntax highlighting was not working properly. The error was due to having multiple  versions of `@lezer/highlight` package being installed. `hoppscotch-ui`  uses `^1.0.0`  and `hoppscotch-common`  uses `^1.1.6`
**After**
We can fix the problem by bumping `@lezer/highlight` to `1.1.6`, but since `@lezer/highlight` is an unused dependency in `hoppscotch-ui`, we decided to remove it.

fix: graphql page crashing and broken syntax highlighting 

---

packages/hoppscotch-data/package.json
pnpm-lock.yaml

Bump dependencies for `@hoppscotch/data`.
- Vite → v3 - v4
- TypeScript → v4 - v5
Closes HFE-266.

chore(data): bump dependencies

---

packages/hoppscotch-common/src/components/http/Headers.vue
packages/hoppscotch-common/src/helpers/actions.ts

`RESTOptionTabs` is being imported as `RequestOptionTabs` in two files. This PR fixes the issue

chore: fix spelling mistake on type import

---

packages/hoppscotch-common/src/components/app/Banner.vue
packages/hoppscotch-common/src/components/app/Header.vue
packages/hoppscotch-common/src/services/__tests__/banner.service.spec.ts
packages/hoppscotch-common/src/services/banner.service.ts

Closes HFE-317
This PR focuses on allowing the banner service to handle multiple banners. Currently, the service can hold only one banner at a time. However, there can be instances where multiple services or components may access the banner at the same time. This is solved by allowing the banner service to hold multiple banners and display the banner which has the highest priority score.

refactor: allow banner service to hold multiple banners and display the banner with the highest score

---

packages/hoppscotch-common/src/composables/codemirror.ts

Fixes HFE-213
Closes #3236 
**Before**
When formatting/parsing XML files, if the xml is invalid, request body disappeares. We were not catching the error thrown by the XMLFormatter function.
**After**
We capture and handle the thrown error with a try-catch. Also wrapped the try catch in a utility function that returns an Either to make it a little bit tidy.

fix: XML body disappearing with invalid XML

---

packages/hoppscotch-common/src/helpers/curl/sub_helpers/url.ts

Closes #3485 
Added parentheses and single quotes support to importing from curl. Changed the regex to include the parentheses and single quotes. Before that the single quotes existing at the start and end of URL are removed using `replace(/^'|'$/g, "")`. Also ran a lint fix.
[Screencast from 08-11-23 09:45:44 PM IST.webm](https://github.com/hoppscotch/hoppscotch/assets/55492635/106f9057-24e1-48b2-a70d-ba98615d3674)

fix(common): parentheses and single quotes support to curl imports

---

docker-compose.yml
packages/hoppscotch-backend/prisma/migrations/20231130082054_collection_headers/migration.sql
packages/hoppscotch-backend/prisma/schema.prisma
packages/hoppscotch-backend/src/errors.ts
packages/hoppscotch-backend/src/pubsub/topicsDefs.ts
packages/hoppscotch-backend/src/team-collection/input-type.args.ts
packages/hoppscotch-backend/src/team-collection/team-collection.model.ts
packages/hoppscotch-backend/src/team-collection/team-collection.resolver.ts
packages/hoppscotch-backend/src/team-collection/team-collection.service.spec.ts
packages/hoppscotch-backend/src/team-collection/team-collection.service.ts
packages/hoppscotch-backend/src/team-request/team-request.service.spec.ts
packages/hoppscotch-backend/src/types/CollectionFolder.ts
packages/hoppscotch-backend/src/user-collection/input-type.args.ts
packages/hoppscotch-backend/src/user-collection/user-collection.resolver.ts
packages/hoppscotch-backend/src/user-collection/user-collection.service.spec.ts
packages/hoppscotch-backend/src/user-collection/user-collection.service.ts
packages/hoppscotch-backend/src/user-collection/user-collections.model.ts

Closes HBE-329
In this PR we introduce a new column in the `TeamCollection` and `UserCollection` table called `data`. Along with the `TeamCollection` and `UserCollection` GQL type has a new field called `data` which is given below.
```
type TeamCollection {
id: ID!
title: String!
data: String
parentID: ID
team: Team!
parent: TeamCollection
children: [TeamCollection!]!
}
type UserCollection {
id: ID!
title: String!
data: String
type: ReqType!
requests: [UserRequest!]!
user: User!
parent: UserCollection
childrenREST: [UserCollection!]!
childrenGQL: [UserCollection!]!
}
```
In addition to the aforementioned changes, mutations responsible for renaming `TeamCollection` and `UserCollection` titles `renameCollection` and `renameUserCollection` have been deprecated and it is preferred if the …

feat: addition of `data` field into User and Team Collections

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components.d.ts
packages/hoppscotch-common/src/components/embeds/index.vue
packages/hoppscotch-common/src/components/http/RequestOptions.vue
packages/hoppscotch-common/src/components/http/Response.vue
packages/hoppscotch-common/src/components/http/ResponseMeta.vue
packages/hoppscotch-common/src/components/share/CreateModal.vue
packages/hoppscotch-common/src/components/share/CustomizeModal.vue
packages/hoppscotch-common/src/components/share/Modal.vue
packages/hoppscotch-common/src/components/share/Request.vue
packages/hoppscotch-common/src/components/share/index.vue
packages/hoppscotch-common/src/components/share/templates/Button.vue
packages/hoppscotch-common/src/components/share/templates/Embeds.vue
packages/hoppscotch-common/src/components/share/templates/Link.vue
packages/hoppscotch-common/src/helpers/backend/gql/mutations/CreateShortcode.graphql
packages/hoppscotch-common/src/helpers/backend/gql/mutations/UpdateEmbedProperties.graphql
packages/hoppscotch-common/src/helpers/backend/gql/queries/ResolveShortcode.graphql
packages/hoppscotch-common/src/helpers/backend/gql/subscriptions/ShortcodeUpdated.graphql
packages/hoppscotch-common/src/helpers/backend/mutations/Shortcode.ts
packages/hoppscotch-common/src/helpers/shortcode/Shortcode.ts
packages/hoppscotch-common/src/helpers/shortcode/ShortcodeListAdapter.ts
packages/hoppscotch-common/src/pages/e/_id.vue
packages/hoppscotch-ui/src/components/smart/Checkbox.vue

Closes HFE-250
This feature adds the ability to embed hoppscotch app as iframe on any place like blogs, personal websites etc, by creating a shared request as type embed.

feat: embeds

---

packages/hoppscotch-common/src/components/http/TestResult.vue
packages/hoppscotch-common/src/components/profile/UserDelete.vue

Banner color classes were updated in #3497. The old set of classes was referred to in a few places, and the banner color wasn't displayed correctly. This PR updates all the instances with the updated class names. It also includes fixes for errors raised by ESLint across the package.

fix(common): ensure banner colors are displayed correctly

---

packages/hoppscotch-ui/src/components/smart/Modal.vue

Modal max height is set based on view port size instead of using hard coded value
Closes #3642 
Used `60vh` as body height of modal instead of `lg`
[Screencast from 12-12-23 01:18:44 PM IST.webm](https://github.com/hoppscotch/hoppscotch/assets/55492635/6c66bb13-2ea3-4197-8929-6d18cfcb5528)

fix: overflowing modal fix on small screens

---

packages/hoppscotch-common/src/components/embeds/index.vue
packages/hoppscotch-common/src/components/history/index.vue
packages/hoppscotch-common/src/components/http/Request.vue
packages/hoppscotch-common/src/components/share/CustomizeModal.vue
packages/hoppscotch-common/src/components/share/index.vue
packages/hoppscotch-common/src/components/share/templates/Link.vue
packages/hoppscotch-ui/src/components/button/Primary.vue

- Use `env.VITE_SHORTCODE_BASE_URL` instead of hardcoded value for shared requests.
- Minor UI improvements.

fix: use base url instead of hardcoded url

---

packages/hoppscotch-sh-admin/locales/en.json
packages/hoppscotch-sh-admin/src/components.d.ts
packages/hoppscotch-sh-admin/src/components/app/Login.vue

Closes HFE-349
This PR fixes an issue where users where not notified that he/she is trying to login into the admin dashboard with a non admin account.

fix: notify that the user is not an admin when trying to login with a non admin account in admin dashboard

---

packages/hoppscotch-cli/src/__tests__/commands/test.spec.ts
packages/hoppscotch-cli/src/__tests__/samples/collection-level-headers-auth.json
packages/hoppscotch-cli/src/__tests__/utils.ts
packages/hoppscotch-cli/src/utils/collections.ts
packages/hoppscotch-cli/src/utils/request.ts

This PR includes the necessary changes to the CLI for processing the updated export format with authorization and headers set at the collection level.
- For `auth` fields for folders/requests, the value at the current level is updated to be based on the immediate parent.
- For `header` fields, the value at the current level is extended based on the immediate parent. If there are header entries with keys under the same name, the value set at the child level takes precedence.
> The test suite has been updated with a relevant test case to verify the new behavior. Along with that, the `execAsync` helper function has been modified to maintain the CLI path locally and construct the command structure based on the received arguments, and renamed to `runCLI`.
Depends on #3505.
Closes HFE-295. …

feat(cli): support collection level authorization and headers

---

packages/hoppscotch-common/src/components/share/templates/Embeds.vue

Closes HFE-335
This PR fixes the UI issue in embeds light mode preview when sharing a request.

refactor: embeds preview theme

---

packages/hoppscotch-common/src/components/share/templates/Embeds.vue
packages/hoppscotch-common/src/pages/e/_id.vue

Closes HFE-355
This PR fixes the issue in embeds where the 'system' theme choosed the app colour theme rather than the actual system theme

fix: embeds system theme

---

packages/hoppscotch-common/src/components/importExport/ImportExportList.vue

The GQL collections importer section in the import/export modal only had two options, and showing the expand widget isn't necessary. This PR updates the `ImportExportList` component to show the expand widget only if there are `4` or more import options.
Closes HFE-340.
> #### Before
> #### After

chore: remove expand widget from the GQL collections import/export modal

---

packages/hoppscotch-common/src/components/environments/index.vue

When opened via the inspector, the add environment modal showed the value associated with the previous attempt to set an environment via the context menu. This PR aims to fix this behavior by removing the truthy check before assigning environment values at the parent environments component, thereby permitting empty strings.
https://github.com/hoppscotch/hoppscotch/assets/25279263/9dd2e560-bfb8-4152-819c-90a0e07f84ce
Closes HFE-347.

fix(common): ensure the add-environment modal value field is empty when opened via the inspector

---

packages/hoppscotch-common/src/components/app/PaneLayout.vue

Fixes HFE-357
**Before**
If the sidebar is hidden, actions from components inside the sidebar are not working.
this is caused by the Sidebar Pane unmounting, resulting in the components which houses these environment models unmounting, which results in the actions defined by the defineActionHandlers unbinding, which when triggered does nothing.
this is also affecting entires in the spotlight,
1. New Collection
2. Create New Environment
3. Delete Current Environment
4. Edit Environment
5. Edit Global Environment
etc.
**After**
First idea was to just use v-show instead of v-if for the pane. which will just hide the pane instead of unmounting it. this will fix our problem. but the library we use 'splitpanes' is not working properly with 'v-show'. But we simulate the behaviour by setting the …

fix: actions not working when sidebar is hidden

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/newstore/collections.ts

Closes HFE-362
This PR fixes the issue in the header-auth feature where the request failed to inherit properties in some cases, also updated i18n string.

fix: auth-header not inheriting properties

---

packages/hoppscotch-common/src/services/persistence/index.ts
packages/hoppscotch-common/src/services/persistence/validation-schemas/index.ts

This PR aims at updating a few schemas under the persistence service that were found to differ from the incoming data at runtime.
- Removes the empty object fallback for settings and makes it fallback to the default set of values if the key is not present in `localStorage`. The corresponding schema has also been updated.
- Marks the `clientID` field as optional for the MQTT request schema and the `oauth2Token` field under `URL_EXCLUDES` for `settings`.

fix(persistence-service): update schemas found to differ in runtime

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/pages/e/_id.vue

This PR adds a fallback section for embeds if the link is invalid.

fix: fallback section for embeds if invalid link

---

packages/hoppscotch-cli/package.json
packages/hoppscotch-cli/src/__tests__/commands/test.spec.ts
packages/hoppscotch-cli/src/__tests__/samples/req-body-env-vars-coll.json
packages/hoppscotch-cli/src/__tests__/samples/req-body-env-vars-envs.json
packages/hoppscotch-cli/src/__tests__/utils.ts
packages/hoppscotch-cli/src/options/test/env.ts

This PR fixes an issue with the CLI where the [single environment entry export format](https://docs.hoppscotch.io/documentation/clients/cli#_1-single-environment-entry-export-format) omits the variables except the first. This led to the `ENV_EXPAND_LOOP` state when multiple environment variable entries were referred from a collection. For instance, in the request body, as mentioned in the below issue. A corresponding test case is added to verify the behavior.
https://github.com/hoppscotch/hoppscotch/blob/7db7b9b0683424a594b85ac5265c4a5ff749586b/packages/hoppscotch-data/src/environment/index.ts#L34-L55
Fixes #3675.
Closes HFE-370.

fix(cli): environment resolution in the single-entry export format

---

packages/hoppscotch-backend/src/errors.ts
packages/hoppscotch-backend/src/infra-config/helper.ts
packages/hoppscotch-backend/src/infra-config/infra-config.service.ts
packages/hoppscotch-backend/src/main.ts
packages/hoppscotch-backend/src/utils.ts

Closes HBE-343
This PR fixed the following issues in `hoppscotch-backend` package
1. Improve SMTP email validation by allowing a total of 3 formats that the nodemailer npm package allows. https://nodemailer.com/message/addresses.
This error encountered when `updateInfraConfigs` mutation called.
2. To resolve error on `enableAndDisableSSO` mutation, introduced Database call `findMany()` instead of `configService.get()` to get latest data
1. Regarding the SMTP email format
The npm Nodemailer package has 3 acceptable formats where `hoppscotch-backend` previously accepts only email as `MAILER_ADDRESS_FROM`.
```
Backend Server | [Nest] 65  - 12/19/2023, 5:46:40 PM   ERROR [ExceptionsHandler] infra_config/invalid_input 
Backend Server | Error: infra_config/invalid_input 
Backend Server |     at …
```

HBE-343 hotfix: improve smtp email validation and fix enableAndDisableSSO mutation

---

packages/hoppscotch-common/src/helpers/import-export/import/openapi.ts

Closes #3743
Fixes HFE-395
**Before**
in function `convertPathToHoppReqs`, when calculating the endpoint, if the value returned from the `parseOpenAPIUrl` has a trailing slash and `replaceOpenApiPathTemplating` has a leading slash, it will cause the endpoint to have a double slash in the middle.
**After**
We handle the above case by removing the extra slash.

fix: fix unwanted double slashes when importing from openapi

---

packages/hoppscotch-selfhost-web/src/platform/auth/auth.platform.ts

Closes #3701
This PR fixes the bug found in refresh token feature
- Fix problem with refreshToken method when backend returns 401 code
- When refreshToken returns false then completing the user session

fix(selfhost-web): perform logout if the silent refresh attempt fails

---

packages/hoppscotch-common/src/components/graphql/Sidebar.vue
packages/hoppscotch-common/src/components/graphql/TypeLink.vue
packages/hoppscotch-common/src/helpers/graphql/connection.ts

Closes HFE-380
Updated the `resolveRootType` function to correctly handle GraphQL types that do not have an `ofType` property. The function now uses a while loop to traverse the `ofType` chain until it reaches a type that does not contain any other types (i.e., its ofType property is null). This ensures that the function always returns the correct root type for any given GraphQL type.

fix: documentation is not being generated on GQL

---

packages/hoppscotch-common/src/components/http/PreRequestScript.vue
packages/hoppscotch-common/src/components/http/Tests.vue
packages/hoppscotch-common/src/components/smart/EnvInput.vue
packages/hoppscotch-common/src/composables/codemirror.ts

Closes HFE-381
This PR removes the context menu from test and pre-request script fields, also closes a context menu in input fields if the text is updated.

refactor: add option to disable context menu

---

packages/hoppscotch-common/src/components/http/Request.vue
packages/hoppscotch-common/src/helpers/RequestRunner.ts

Closes HFE-384
This PR introduces a feature that empowers tabs to continue executing their respective requests seamlessly even during tab-switching scenarios, preventing premature cancellations that were occurring previously.

refactor: persist running requests while switching tabs

---

packages/hoppscotch-common/src/components/http/TestResult.vue
packages/hoppscotch-common/src/helpers/terndoc/ecma.json
packages/hoppscotch-common/src/helpers/terndoc/pw-pre.json
packages/hoppscotch-common/src/helpers/terndoc/pw-test.json
packages/hoppscotch-js-sandbox/src/__tests__/preRequest.spec.ts
packages/hoppscotch-js-sandbox/src/__tests__/testing/envs/unset.spec.ts
packages/hoppscotch-js-sandbox/src/__tests__/testing/test-runner.spec.ts
packages/hoppscotch-js-sandbox/src/utils.ts

We can unset variables using unset function in pre-request script and test script
Closes #3398 
Unset function is added to the Javascript Sandbox. It will work on both pre-request scripts and test scripts. An associated test suite was added. Also, the test results UI will now show deletions for the global environment.

feat(js-sandbox): add `pw.env.unset` method

---

packages/hoppscotch-cli/bin/hopp
packages/hoppscotch-cli/bin/hopp.js
packages/hoppscotch-cli/package.json
packages/hoppscotch-cli/src/index.ts
packages/hoppscotch-cli/src/utils/collections.ts
packages/hoppscotch-cli/src/utils/display.ts
packages/hoppscotch-cli/src/utils/functions/array.ts
packages/hoppscotch-cli/src/utils/getters.ts
packages/hoppscotch-cli/tsconfig.json
packages/hoppscotch-cli/tsup.config.ts
pnpm-lock.yaml

This PR brings the necessary updates to the build system for the CLI to emit an ESM-only bundle. Along with that, the dependencies are bumped, and the following are removed:
- [esm](https://www.npmjs.com/package/esm)
- [io-ts](https://www.npmjs.com/package/io-ts)
Follow up of #3441.
Closes HFE-278.
The dependencies, while inlined in the bundle, caused issues relating to the usage of `require` in the ESM context; hence they're no longer inlined ([officially recommended](https://tsup.egoist.dev/#excluding-all-packages)) and moved under `dependencies`. For `fp-ts`, it's inlined as part of the bundle and kept under `devDependencies` since the import paths were expected to specify the extensions `import * as TE from fp-ts/lib/TaskEither.js`.

chore(cli): emit bundle in ESM format

---

packages/hoppscotch-common/src/components/http/Request.vue

Closes HFE-421
This PR fixes the unnecessary HTTP protocol append issue with the endpoint. Because the endpoint was not being trimmed before. Now the issue is fixed by trimming the endpoint before appending the protocol.

fix: request endpoint heading

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components/http/TabHead.vue
packages/hoppscotch-common/src/components/share/Request.vue
packages/hoppscotch-common/src/components/share/index.vue
packages/hoppscotch-common/src/pages/index.vue

Closes HFE-407
This PR add the following updates to the shared request flow - 
- Added a + icon, on clicking the user will see the share request modal pop up for a the request currently open in the tab
- Upon clicking on an existing shared request, opens the customize modal instead of opening the request in a new tab
- When right clicking on tab shows the option to share request.

refactor: update share request flow

---

packages/hoppscotch-common/src/components/http/OAuth2Authorization.vue
packages/hoppscotch-common/src/helpers/oauth.ts
packages/hoppscotch-common/src/platform/std/interceptors/extension.ts

Fixes HFE-382
**Changes**
1. Disable the OpenID Connect Discovery URL when Authorization/Access Token URLs are present.
2. Disable Authorization/Access Token URLs when the OpenID Connect Discovery URL is present.
3. Implement OAuth fetch calls through interceptors.
4. Fix an if statement that made OpenID Connect discovery URLs mandatory
**Note**
We will be removing OpenID Connect Discovery URL very soon. this is temporary solution till then.

chore: Oauth temporary ux improvements

---

packages/hoppscotch-sh-admin/src/components/app/Sidebar.vue

This PR ensures the active selection in the sidebar for the Admin dashboard is persisted across page reloads. A new property, `baseRouteName` is introduced under `primaryNavigations` in the `AppSidebar` component that defines the base route names corresponding to each nav item and checks against the route name to decide whether to apply the classes for active selection or not.
Closes HFE-424.
https://github.com/hoppscotch/hoppscotch/assets/25279263/790ed666-d5a0-405d-8bb2-bd5a9a3cc10d

fix(sh-admin): persist active selection in the sidebar

---

packages/hoppscotch-common/src/components/http/Request.vue
packages/hoppscotch-common/src/platform/analytics.ts

Fixes HFE-427
**Changes**
This PR adds the `workspaceType` property in `HOPP_REQUEST_RUN` event. the possible values are `team` and `personal`.

chore: add workspace type property in request run analytics event

---

packages/hoppscotch-common/src/components/environments/teams/Details.vue
packages/hoppscotch-common/src/helpers/editor/extensions/HoppEnvironment.ts
packages/hoppscotch-common/src/services/persistence/validation-schemas/index.ts

Closes HFE-426
This PR fixes a bug where a hovered environment tooltip failed to update its state when a secret environment is updated.
Also fixes a issue in schema validation for restTab testResult type.

fix: environment tooltip update bug

---

packages/hoppscotch-common/src/components/http/OAuth2Authorization.vue

Fixes HFE-428
**Changes**
Fix accessing undefined property `selected.variables`. `selected` is already the list of variables, we do not need to access the `variables` property.

fix: fix accessing undefined property `variables`

---

packages/hoppscotch-common/src/components/share/Request.vue
packages/hoppscotch-common/src/components/share/index.vue

This PR fixes an exception with the open shared request in a new tab action where the handler was not in place previously, leading to exceptions.
Fixes HFE-431.
https://github.com/hoppscotch/hoppscotch/assets/25279263/2b62ad20-3197-4167-ad7a-557723858498

fix(common): prevent exceptions with open shared requests in new tab action

---

packages/hoppscotch-common/assets/scss/styles.scss
packages/hoppscotch-common/src/components/graphql/RequestOptions.vue
packages/hoppscotch-common/src/components/graphql/Response.vue
packages/hoppscotch-common/src/components/graphql/Sidebar.vue
packages/hoppscotch-common/src/components/graphql/Variable.vue
packages/hoppscotch-common/src/components/http/Headers.vue
packages/hoppscotch-common/src/components/http/Parameters.vue
packages/hoppscotch-common/src/components/http/PreRequestScript.vue
packages/hoppscotch-common/src/components/http/RawBody.vue
packages/hoppscotch-common/src/components/http/RequestTab.vue
packages/hoppscotch-common/src/components/http/Tests.vue
packages/hoppscotch-common/src/components/http/URLEncodedParams.vue
packages/hoppscotch-common/src/components/lenses/renderers/HTMLLensRenderer.vue
packages/hoppscotch-common/src/components/lenses/renderers/JSONLensRenderer.vue
packages/hoppscotch-common/src/components/lenses/renderers/RawLensRenderer.vue
packages/hoppscotch-common/src/components/lenses/renderers/XMLLensRenderer.vue
packages/hoppscotch-common/src/components/realtime/Communication.vue
packages/hoppscotch-common/src/helpers/editor/themes/baseTheme.ts

Closes HFE-433
The overall performance in Safari especially when the response section is rendered was bad and laggy.
The performance of the app in safari was bad for the following reasons
- The codemirror didn't have a parent container which leads to attain the height of the next parent element which inherited the height of the splitpanes which lead to lag while changing the height of the splitpanes
- The browser was unaware (mostly safari) of the layout paint areas due to splitpanes height/width changes rapidly, adding will-change property and changing the splitpanes to a new layer reduced the Cumulative Layout Shift and Total Blocking Time to half

fix: perfomance in safari

---

packages/hoppscotch-common/src/helpers/oauth.ts

**Before**
In the last oauth update, we used `application/json` as content type for token exchange requests in auth code flow. but most oauth token exchange endpoints works with `application/x-www-form-urlencoded` content type.  
**After**
use `application/x-www-form-urlencoded` content type for token exchange requests.

fix: use x-www-form-urlencoded for token exchange requests in oauth

---

packages/hoppscotch-common/src/components/collections/index.vue
packages/hoppscotch-common/src/components/graphql/Authorization.vue
packages/hoppscotch-common/src/components/http/Authorization.vue
packages/hoppscotch-common/src/helpers/curl/__tests__/curlparser.spec.js
packages/hoppscotch-common/src/helpers/graphql/default.ts
packages/hoppscotch-common/src/helpers/rest/default.ts
packages/hoppscotch-data/src/graphql/index.ts
packages/hoppscotch-data/src/rest/index.ts

Closes HFE-422 #3713
This pull request resolves the issue of collection-level authorization inheritance in its requests. Currently, when we create a request in a collection that is supposed to inherit the auth from collection properties, we have to manually choose an auth-type called "inherit" to inherit authorization from the collection. 
Although it works when we select the option manually, it should by default inherit the auth options from the collection and prioritize request auth over collection auth without creating or selecting any auth-type called "inherit". This PR addresses the issue and changes the flow to achieve this.

fix: collection level authorization inheritance issue

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components/collections/ImportExport.vue
packages/hoppscotch-common/src/components/collections/MyCollections.vue
packages/hoppscotch-common/src/components/environments/ImportExport.vue
packages/hoppscotch-common/src/components/importExport/ImportExportSteps/FileImport.vue
packages/hoppscotch-common/src/helpers/functional/json.ts
packages/hoppscotch-common/src/helpers/import-export/import/hopp.ts
packages/hoppscotch-common/src/helpers/import-export/import/hoppEnv.ts
packages/hoppscotch-common/src/helpers/import-export/import/hoppGql.ts
packages/hoppscotch-common/src/helpers/import-export/import/import-sources/FileSource.ts
packages/hoppscotch-common/src/helpers/import-export/import/import-sources/GistSource.ts
packages/hoppscotch-common/src/helpers/import-export/import/insomnia.ts
packages/hoppscotch-common/src/helpers/import-export/import/insomniaEnv.ts
packages/hoppscotch-common/src/helpers/import-export/import/openapi.ts
packages/hoppscotch-common/src/helpers/import-export/import/postman.ts
packages/hoppscotch-common/src/helpers/import-export/import/postmanEnv.ts
packages/hoppscotch-common/src/newstore/collections.ts

This PR adds support for importing multiple collection and environment files simultaneously for all import formats, including import from Gist. Also, the environment values are converted to strings while importing from Hoppscotch (via Gist/file) & Postman. We're also introducing a file size limit of `10 MB`.
Closes HFE-386 HFE-389.
- The collection tree appears broken while importing REST/GQL collections in the personal workspace, with the requests appearing outside folders where they should reside. This is an issue that already exists related to syncing tracked separately. Safeguards are added with this PR to prevent exceptions observed while importing collections with many requests.
- If the user mixes files of other types while importing, it will result in an error toast if the …

feat(common): support simultaneous imports of collections and environment files

---

docker-compose.yml
packages/hoppscotch-backend/prisma/migrations/20240226053141_full_text_search_additions/migration.sql
packages/hoppscotch-backend/prisma/schema.prisma
packages/hoppscotch-backend/src/auth/auth.controller.ts
packages/hoppscotch-backend/src/auth/auth.service.ts
packages/hoppscotch-backend/src/auth/guards/github-sso.guard.ts
packages/hoppscotch-backend/src/auth/guards/google-sso.guard.ts
packages/hoppscotch-backend/src/auth/guards/microsoft-sso-.guard.ts
packages/hoppscotch-backend/src/auth/helper.ts
packages/hoppscotch-backend/src/errors.ts
packages/hoppscotch-backend/src/infra-config/infra-config.controller.ts
packages/hoppscotch-backend/src/team-collection/helper.ts
packages/hoppscotch-backend/src/team-collection/team-collection.controller.ts
packages/hoppscotch-backend/src/team-collection/team-collection.module.ts
packages/hoppscotch-backend/src/team-collection/team-collection.service.ts
packages/hoppscotch-backend/src/team/guards/rest-team-member.guard.ts
packages/hoppscotch-backend/src/types/CollectionSearchNode.ts
packages/hoppscotch-backend/src/types/RESTError.ts
packages/hoppscotch-backend/src/utils.ts

Closes HSB-322
In this PR we introduce a new route that allows for full-text search to be performed over saved team collections and requests. 
`GET http://localhost:3170/v1/team-collection/search/:teamID/:searchQuery?take=5&skip=2`
We also have simple offset pagination available using the `take` and `skip` query params.
An example response to the above query may be like the following:
```
{
"data": [
.........,
{
"type": "collection",
"title": "Get Started for BSPs",
"id": "clt1k7d6u02h9ioerkkia6b7h",
"path": [
{
"id": "clt1k7d6p02goioeri3f85nju",
"title": "Cloud API",
"type": "collection",
"path": []
}
]
},
.........,
{
"type": "request",
"title": "get request",
"method": "GET",
"id": "clt1k7cm9000hioerpzpfpmb0",
"path": [
{
"id": "clt1k7cm9000fioer57bl0n9d",
"title": "child collection", …
```

feat: full text search for `TeamCollections` and `TeamRequests`

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/modules/index.ts
packages/hoppscotch-common/src/modules/router.ts
packages/hoppscotch-common/src/pages/enter.vue

Fixs HFE-410
**Changes**
1. make router beforeEach guard wait for the modules returning promises to resolve before going to the target route
2. allow guest only access for enter.vue, this is a requirement to prevent getting redirected to login-required page if site protection is enabled, because we use enter for verifying the magic link
3. add i18n entries for site protection related texts

feat: common changes for site protection

---

packages/hoppscotch-common/src/helpers/import-export/import/hopp.ts
packages/hoppscotch-data/src/collection/index.ts
packages/hoppscotch-data/src/rest/v/2.ts
packages/hoppscotch-selfhost-desktop/src/platform/collections/collections.platform.ts
packages/hoppscotch-selfhost-web/src/platform/collections/collections.platform.ts

Closes HFE-443
This PR fixed the issue with request variable where the app crashes since the request schema failed to upgrade version while syncing returning a undefined value.

hotfix: request variable version syncing bug

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components/app/Header.vue
packages/hoppscotch-common/src/components/workspace/Current.vue
packages/hoppscotch-common/src/components/workspace/Selector.vue

Closes HFE-444
Show `personal workspace` as workspace selector text even if the user has provided their name.

refactor: personal workspace nomenclature update

---

packages/hoppscotch-sh-admin/src/components.d.ts
packages/hoppscotch-sh-admin/src/components/settings/AuthProvider.vue
packages/hoppscotch-sh-admin/src/components/settings/DataSharing.vue
packages/hoppscotch-sh-admin/src/components/settings/SmtpConfiguration.vue
packages/hoppscotch-sh-admin/src/components/setup/DataSharingAndNewsletter.vue

Closes HFE-445
This PR updates the documentation links related to Data Sharing in the Admin Dashboard. It also introduces a refactor where all inputs in configurations tab under settings page will not be disabled by default. Admins can update the input-boxes without unmasking the inputs.

refactor(sh-admin): updated data sharing doc links + remove disabled property from all inputs in configurations

---

packages/hoppscotch-common/src/components/environments/my/Details.vue
packages/hoppscotch-common/src/components/environments/teams/Details.vue
packages/hoppscotch-common/src/helpers/import-export/import/insomniaEnv.ts
packages/hoppscotch-common/src/helpers/import-export/import/postmanEnv.ts
packages/hoppscotch-common/src/helpers/utils/uniqueID.ts
packages/hoppscotch-common/src/newstore/environments.ts
packages/hoppscotch-data/src/environment/index.ts
packages/hoppscotch-data/src/environment/v/1.ts

Closes HFE-440
This PR fixes the issue in secret environment feature where when pushing the environment with `undefined` value failed, resulting in empty secret env's.
Also add id while upgrading env version.

fix: secret env bug in firebase due to undefined value

---

docker-compose.yml
packages/hoppscotch-backend/src/infra-config/infra-config.service.ts

Closes HSB-375
This in PR we add a fix to an bug identified in the method responsible for resetting the infra-configs and we also exclude some infra-configs from getting reset too.

hotfix: reset infra-config bug

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components/app/spotlight/entry/RESTTeamRequestEntry.vue
packages/hoppscotch-common/src/components/app/spotlight/index.vue
packages/hoppscotch-common/src/components/collections/TeamCollections.vue
packages/hoppscotch-common/src/components/collections/index.vue
packages/hoppscotch-common/src/helpers/teams/TeamsSearch.service.ts
packages/hoppscotch-common/src/services/spotlight/searchers/teamRequest.searcher.ts

This PR introduces searching team collections & requests from the workspace sidebar and spotlight search.

feat: team search in workspace search and spotlight

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components/firebase/Login.vue

Closes HFE-453
This PR adds Github Enterprise as one of the auth providers. This PR also add the OIDC auth addition to the additionalLoginItems.

feat: github enterprise SSO provider addition

---

packages/hoppscotch-common/src/pages/import.vue

**Before**
The importers now takes an array instead of just the import content. this update was not made in the `import.vue` file. because of this imports will fail. (test in staging server to repro.)
`https://hoppscotch.io/import?url=https://raw.githubusercontent.com/openai/openai-openapi/master/openapi.yaml&type=openapi`
**After**
Imports from `import.vue` also passes the contents as an array.

fix: fix direct import from url failing

---

packages/hoppscotch-common/src/components/share/index.vue

This PR aims at adding a safeguard to prevent an exception that can arise while attempting to initialize the `ShortCodeListAdapter` where the adapter is already initialized. This can happen while logging in on cloud with `Shared Requests` as the active tab.
Closes HFE-454.

fix(common): prevent exception with `ShortcodeListAdapter` initialization

---

packages/hoppscotch-common/src/helpers/teams/TeamsSearch.service.ts

**Before**
The url for the team search endpoint had an extra '}'
**After**
The typo is fixed.

fix: fix typo in team search url

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/services/inspection/inspectors/header.inspector.ts

Changed copy for header inspection as the Hoppscotch Desktop app is now available
Before: The browser doesn't allow Hoppscotch to set the Cookie Header. While we're working on the Hoppscotch Desktop App (coming soon), please use the Authorization Header instead.
After: The browser doesn't allow Hoppscotch to set Cookie Headers. Please use Authorization Headers instead. However, our Hoppscotch Desktop App is live now and supports Cookies.

chore: update copy for header inspection

---

packages/hoppscotch-common/src/helpers/teams/TeamsSearch.service.ts
packages/hoppscotch-common/src/platform/auth.ts
packages/hoppscotch-selfhost-web/src/platform/auth/auth.platform.ts

**Changes**
This PR introduces a new property `axiosPlatformConfig` to auth platform definition. this allows us to pass different axios configs based on the platform.
eg: Central uses Bearer Token to authenticate with the backend, while the SH uses Cookies, the configs for these can now belong in the respective platforms. 
we already do this for our Gql Client, this PR adds the same for axios configs to be used for requests sent outside of the graphql client.

chore: split axios request options into platform

---

packages/hoppscotch-sh-admin/locales/en.json
packages/hoppscotch-sh-admin/src/components.d.ts
packages/hoppscotch-sh-admin/src/pages/users/index.vue
packages/hoppscotch-sh-admin/src/pages/users/invited.vue

Closes HFE-456
This PR focuses on improving pending invites page in admin dashboard. Admin ID is removed from the table and `Admin Email` is renamed to `Invited By`.

refactor(sh-admin): improvements to pending invites page in dashboard

---

packages/hoppscotch-common/src/components/teams/Team.vue
packages/hoppscotch-common/src/components/teams/index.vue

Closes HFE-458
This PR fixes the bugs in workspace section in profile page
- Add loading spinner while deleting a workspace
- Refetch workspace list after deleting a workspace rather waiting for the workspace list fetch poll to effect the list
- Switch to personal workspace if the current selected workspace is same as that deleted.

fix: workspace list section bugs

---

packages/hoppscotch-common/src/helpers/utils/EffectiveURL.ts
packages/hoppscotch-data/package.json

When choosing the content-type as `application/x-www-form-urlencoded`, `application/multipart-formdata` and sending the request, an error appears in the console. This PR fixes the issue

fix: request failing on change content type to multipart-formdata

---

packages/hoppscotch-common/src/components/http/ImportCurl.vue
packages/hoppscotch-common/src/composables/codemirror.ts

This PR introduces new changes to enhance user experience within the ImportCurl component. With this update, when the ImportCurl component is launched, the CodeMirror view automatically receives focus.

feat: focus codemirror view when ImportCurl component launched

---

packages/hoppscotch-common/src/services/spotlight/searchers/collections.searcher.ts
packages/hoppscotch-common/src/services/spotlight/searchers/teamRequest.searcher.ts

Fixs HFE-460
**Changes**
1. Results from the personal workspace are not shown when searching from team workspaces
2. Instead of `Team Requests`, spotlight section title will be the name of the Team Workspace

chore: spotlight improvements for team requests search

---

packages/hoppscotch-common/src/helpers/import-export/import/hopp.ts
packages/hoppscotch-common/src/helpers/teams/TeamsSearch.service.ts

This PR ensures requests are validated against the `HoppRESTRequest` versioned entity and translated to the latest version before consuming preventing any exceptions under the following scenarios.
- Importing a collection with requests conforming to an old schema followed by an attempt to open one among them via spotlight.
- Searching for a request in the collection tree with the above state (one or more requests not as per the latest schema) and selecting the request from the search results.
Fixes HFE-461.

fix(common): ensure requests are translated to the latest version during import and search actions

---

packages/hoppscotch-cli/src/utils/pre-request.ts
packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components/graphql/Headers.vue
packages/hoppscotch-common/src/components/http/authorization/ApiKey.vue
packages/hoppscotch-common/src/helpers/graphql/connection.ts
packages/hoppscotch-common/src/helpers/import-export/import/openapi.ts
packages/hoppscotch-common/src/helpers/import-export/import/postman.ts
packages/hoppscotch-common/src/helpers/utils/EffectiveURL.ts
packages/hoppscotch-data/src/graphql/index.ts
packages/hoppscotch-data/src/graphql/v/4.ts
packages/hoppscotch-data/src/rest/index.ts
packages/hoppscotch-data/src/rest/v/4.ts

FIXES HFE-466
Closes #3963
**Changes**
Previously when the auth type was `api-key`, the `addTo` field values where "Headers" or "Query params", and the type was a string.
This PR updates the `addTo` field to be an enum with the values `HEADERS` and `QUERY_PARAMS`. this is consistent with the OAuth `addTo` values, and also allows the type system to catch bugs that were previously not caught because any string value was accepted as a valid `addTo` value.
The issue [#3963](https://github.com/hoppscotch/hoppscotch/issues/3963) is coming from this inconsistency, and this PR fixes it.
We could have kept the "Headers" and "Query params" and updated some checks. but i think this is a good time to make the values consistent and better typed, hence this PR.

fix: use proper values for `addTo` field when auth type is `api-key`

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components/app/Header.vue
packages/hoppscotch-common/src/components/app/SpotlightSearch.vue
packages/hoppscotch-common/src/components/collections/graphql/index.vue
packages/hoppscotch-common/src/components/collections/index.vue
packages/hoppscotch-common/src/helpers/actions.ts
packages/hoppscotch-common/src/layouts/default.vue
packages/hoppscotch-common/src/newstore/settings.ts
packages/hoppscotch-common/src/services/persistence/validation-schemas/index.ts
packages/hoppscotch-common/src/services/spotlight/searchers/collections.searcher.ts
packages/hoppscotch-common/src/services/spotlight/searchers/teamRequest.searcher.ts

Closes HFE-476
This PR adds animation to the spotlight search component. This will only be visible to first time user who hasn't opened the spotlight yet. Also adds "Import Collection" option in the spotlight.
https://github.com/hoppscotch/hoppscotch/assets/53208152/efbbb320-1d5d-4711-9dcb-a8dd7dcca664

feat: first time user spotlight animation

---

package.json
packages/hoppscotch-common/package.json
pnpm-lock.yaml

Closes #4008
This PR fixes the issue where the Generate Code Modal errors out when opened.
The issue is mostly caused by `ajv` a dependency of `httpsnippet` (the library we use to power the Generate Code feature) not being kept properly up-to-date by the source package and needs to be pinned to an older version. We had this going in an earlier fix, but our fix was not solid, we just declared that `httpsnippet` has a peer dependency that is set to a specific version that works. But since its a peer dependency we are expected to have it installed as well. For some reason in `pnpm` v8, `pnpm` resolved it properly to load the version asked in peer dependencies, but this behaviour changed in v9. The fix here just adds `ajv` of the requested version added as a dependency to the users of …

fix: code generate modal erroring out

---

packages/hoppscotch-common/src/components/collections/ImportExport.vue
packages/hoppscotch-common/src/components/collections/SaveRequest.vue
packages/hoppscotch-common/src/components/collections/TeamCollections.vue
packages/hoppscotch-common/src/components/collections/graphql/index.vue
packages/hoppscotch-common/src/components/collections/index.vue
packages/hoppscotch-common/src/components/environments/Selector.vue
packages/hoppscotch-common/src/components/environments/index.vue
packages/hoppscotch-common/src/components/environments/teams/index.vue
packages/hoppscotch-common/src/components/teams/Add.vue
packages/hoppscotch-common/src/components/workspace/Selector.vue
packages/hoppscotch-common/src/services/workspace.service.ts

Closes HFE-483
This PR add's a improvement in the workspace creation flow where the workspace is automatically switched to the created one.

refactor: switch workspace after creation

---

packages/hoppscotch-common/src/pages/index.vue

I noticed that you can't cancel modal window when saving a request. 
I suggest adding a third "cancel" button, which will close the window without performing an action.

Added new button to save request modal

---

packages/hoppscotch-common/src/newstore/settings.ts
packages/hoppscotch-selfhost-web/src/main.ts

Closes HFE-496
This PR set's the default interceptor to "proxy" instead of "browser".

refactor: Set default interceptor to "proxy"

---

packages/hoppscotch-backend/src/admin/admin.service.spec.ts
packages/hoppscotch-backend/src/admin/admin.service.ts
packages/hoppscotch-backend/src/shortcode/shortcode.service.ts
packages/hoppscotch-backend/src/team-invitation/team-invitation.service.ts
packages/hoppscotch-backend/src/user/user.service.spec.ts
packages/hoppscotch-backend/src/user/user.service.ts

Closes HSB-431
Closes #4027 
This pull request addresses a problem where user emails are treated as case-sensitive during signup. This means that signing up with `user@gmail.com` and `USER@gmail.com` would create two separate user entries in the database.
This PR implements logic to convert all email addresses to lowercase before saving them in the database. This ensures that regardless of the case used during signup, only one user entry will be created for the same email address.
Nil

HSB-431 fix: email case sensitive in email provider

---

packages/hoppscotch-backend/prisma/migrations/20240519093155_add_last_logged_on_to_user/migration.sql
packages/hoppscotch-backend/prisma/schema.prisma
packages/hoppscotch-backend/src/admin/admin.service.spec.ts
packages/hoppscotch-backend/src/auth/auth.controller.ts
packages/hoppscotch-backend/src/auth/auth.service.spec.ts
packages/hoppscotch-backend/src/auth/auth.service.ts
packages/hoppscotch-backend/src/interceptors/user-last-login.interceptor.ts
packages/hoppscotch-backend/src/shortcode/shortcode.service.spec.ts
packages/hoppscotch-backend/src/team-collection/team-collection.service.spec.ts
packages/hoppscotch-backend/src/user-collection/user-collection.service.spec.ts
packages/hoppscotch-backend/src/user-request/user-request.service.spec.ts
packages/hoppscotch-backend/src/user-settings/user-settings.service.spec.ts
packages/hoppscotch-backend/src/user/user.model.ts
packages/hoppscotch-backend/src/user/user.service.spec.ts
packages/hoppscotch-backend/src/user/user.service.ts

Closes HSB-444
This PR introduces the ability to store the user's last login timestamp in `hoppscotch-backend` package (in the `user` table). `lastLoggedOn` is the property to access the data. This value can be nullable for previous data.
Nil

HSB-445 feature: storing user last login timestamp

---

packages/hoppscotch-common/src/components/app/Interceptor.vue
packages/hoppscotch-common/src/components/settings/Extension.vue
packages/hoppscotch-common/src/components/settings/Proxy.vue
packages/hoppscotch-common/src/newstore/settings.ts
packages/hoppscotch-common/src/pages/settings.vue

Closes HFE-508 #4059 
This PR fixes the the bug where a logged out user's interceptor option did not get persisted while refreshing. Also added interceptor option in settings page.

fix: persist interceptor state for logged out user

---

packages/hoppscotch-common/src/services/persistence/validation-schemas/index.ts

Closes HFE-512
This PR fixes the issue where the schema validation failed for some restTab where the envDiff missed previousValue so made it a optional field.

fix: add previous value as optional in test schema env diff

---

packages/hoppscotch-common/src/components/http/RawBody.vue

Closes #4083 #3919 HFE-516
When JSON is beautified, the precision of long integer values ​​are lost this PR fixes this buy using lossless-json

fix: precision lost when json is beautified

---

packages/hoppscotch-common/src/components/http/OAuth2Authorization.vue
packages/hoppscotch-common/src/services/oauth/flows/authCode.ts
packages/hoppscotch-common/src/services/persistence/__tests__/__mocks__/index.ts
packages/hoppscotch-data/src/graphql/index.ts
packages/hoppscotch-data/src/graphql/v/5.ts
packages/hoppscotch-data/src/rest/index.ts
packages/hoppscotch-data/src/rest/v/5.ts

Closes #3784
Fixes HFE-517
**Changes**
This PR makes the `clientSecret` optional for authcode + pkce flow. since this is a schema change, we introduce new version 5 for our rest and graphql auth schema in `hoppscotch-data`.
Note: if you're reviewing and need credentials to test. hit me up on slack.

fix: make client credential optional in authcode + pkce flow

---

packages/hoppscotch-common/src/components/lenses/renderers/JSONLensRenderer.vue
packages/hoppscotch-common/src/components/lenses/renderers/RawLensRenderer.vue
packages/hoppscotch-common/src/composables/codemirror.ts

Closes #4050, #4007
https://github.com/hoppscotch/hoppscotch/assets/53208152/38d7d4c9-dad1-4c29-ba90-0481f035fe8c
This PR fixes the issue in CodeMirror where content was not loading correctly on scroll when we had large request bodies. Parts of the body were not rendered and would only render when clicked.
[4106](https://github.com/hoppscotch/hoppscotch/pull/4106) fixes the issue, but the CodeMirror component was not filling the parent container. Therefore, a hack fix `view.requestMeasure()` is used. This function re-measures the CodeMirror layout.
Added a function inside the CodeMirror scroll listener that re-measures the CodeMirror layout while scrolling.
Also added CodeMirror scroll for response lenses.
To check the bug, select the option application/json from the body content-type and …

fix: large content scroll bug in codemirror editor

---

packages/hoppscotch-common/src/helpers/import-export/import/insomnia.ts

This hotfix addresses an issue where `json` body were being wrapped in unnecessary `<<{json}>>` when importing from Insomnia.

hotix: prevent unwanted variable wrapping during Insomnia import

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components.d.ts
packages/hoppscotch-common/src/components/collections/Collection.vue
packages/hoppscotch-common/src/components/collections/Properties.vue
packages/hoppscotch-common/src/components/collections/Runner.vue
packages/hoppscotch-common/src/components/collections/TeamCollections.vue
packages/hoppscotch-common/src/components/collections/index.vue
packages/hoppscotch-common/src/components/environments/Properties.vue
packages/hoppscotch-common/src/components/environments/teams/Environment.vue
packages/hoppscotch-common/src/components/environments/teams/index.vue
packages/hoppscotch-common/src/vite-envs.d.ts

#4095 adds support for accessing collections/environments from a team workspace straightaway via the CLI by supplying the respective IDs without having to obtain an export. This PR includes UI flow updates to support the same where the CLI command to run a certain collection with the ID can be obtained (optionally including the active environment) via the context menu.
Closes HFE-520.
- Fixes the case about dismissing the environment context menu (opened via pressing the `More` kebab menu) via pressing `Escape`, which results in an exception.
- Made `editingProperties` a required prop for the `CollectionsProperties` component with `null` removed from the types since the existing usages guarantee the above prop to be an object.
> The below additions apply only to team workspaces.
- New …

feat: CLI collection runner command generation UI flow

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components/teams/Invite.vue
packages/hoppscotch-common/src/platform/index.ts
packages/hoppscotch-common/src/platform/infra.ts
packages/hoppscotch-selfhost-web/src/api/queries/GetSMTPStatus.graphql
packages/hoppscotch-selfhost-web/src/main.ts
packages/hoppscotch-selfhost-web/src/platform/infra/infra.platform.ts

**Changes**
1. Now you can copy invite links to share manually instead of relaying on email only.
2. Since the SMTP check is only available in `selfhost-web`, this PR adds an optional `infra` platform config
3. Minor improvements like, different copy for when email is enabled v/s disabled

feat: copyable invite links

---

packages/hoppscotch-common/src/components/lenses/renderers/JSONLensRenderer.vue
packages/hoppscotch-common/src/composables/codemirror.ts

Closes #4148
This PR fixes the issue in codemirror when user uses the JSON filter the JSON response section crashed sometimes.
The issue was the codemirror cursor did not get updated w.r.t to the content, i.e the total charecter lenght line < the cursor position which should not happen.
https://github.com/hoppscotch/hoppscotch/assets/53208152/17d9103f-6f2e-437e-871d-3271202fb897

fix: codemirror crashing due to cursor not updating

---

packages/hoppscotch-common/src/composables/codemirror.ts

Closes #4029, #3788
Ctrl+Enter is a keybind for running requests. But using that from codemirror can create a new line along with running the request, so I've overridden the default behaviour of codemirror. Precedence highest is used to override the default ones
[screen-capture (1) (1).webm](https://github.com/hoppscotch/hoppscotch/assets/55492635/f391eedc-0fde-4609-8ddc-1d62cabb64da)

fix: ctrl+enter inserting newline in code

---

packages/hoppscotch-common/locales/af.json
packages/hoppscotch-common/locales/ar.json
packages/hoppscotch-common/locales/ca.json
packages/hoppscotch-common/locales/cn.json
packages/hoppscotch-common/locales/cs.json
packages/hoppscotch-common/locales/da.json
packages/hoppscotch-common/locales/de.json
packages/hoppscotch-common/locales/el.json
packages/hoppscotch-common/locales/es.json
packages/hoppscotch-common/locales/fi.json
packages/hoppscotch-common/locales/fr.json
packages/hoppscotch-common/locales/he.json
packages/hoppscotch-common/locales/hu.json
packages/hoppscotch-common/locales/id.json
packages/hoppscotch-common/locales/it.json
packages/hoppscotch-common/locales/ja.json
packages/hoppscotch-common/locales/ko.json
packages/hoppscotch-common/locales/nl.json
packages/hoppscotch-common/locales/no.json
packages/hoppscotch-common/locales/pl.json
packages/hoppscotch-common/locales/pt-br.json
packages/hoppscotch-common/locales/pt.json
packages/hoppscotch-common/locales/ro.json
packages/hoppscotch-common/locales/ru.json
packages/hoppscotch-common/locales/sr.json
packages/hoppscotch-common/locales/sv.json
packages/hoppscotch-common/locales/tr.json
packages/hoppscotch-common/locales/tw.json
packages/hoppscotch-common/locales/uk.json
packages/hoppscotch-common/locales/vi.json

Closes HFE-528, #4165
This PR purges the en.js with all other locale files
Adds the missing keys in locale files

chore: cleanup i18n translations

---

packages/hoppscotch-common/src/components.d.ts
packages/hoppscotch-common/src/components/app/PaneLayout.vue
packages/hoppscotch-common/src/components/embeds/Header.vue
packages/hoppscotch-common/src/components/embeds/Request.vue
packages/hoppscotch-common/src/components/embeds/index.vue
packages/hoppscotch-common/src/components/http/Headers.vue
packages/hoppscotch-common/src/components/http/Parameters.vue
packages/hoppscotch-common/src/components/http/RawBody.vue
packages/hoppscotch-common/src/components/http/RequestVariables.vue
packages/hoppscotch-common/src/components/http/URLEncodedParams.vue
packages/hoppscotch-common/src/components/lenses/renderers/JSONLensRenderer.vue
packages/hoppscotch-common/src/components/lenses/renderers/RawLensRenderer.vue
packages/hoppscotch-common/src/pages/e/_id.vue

Closes HFE-539, #4170 
This PR fixes the UI bug in embeds where the response and some request option codemirror instance was hidden.
https://github.com/hoppscotch/hoppscotch/assets/53208152/1ecf44a8-011a-4997-a58b-949f511830d7
The embeds structure have been updated by using `PaneLayout` for the view, now the user can set their prefered height, also some code refactor has been done for the `Embeds` component.

fix: embeds response and request option section getting hidden bug

---

packages/hoppscotch-common/src/components/graphql/Headers.vue
packages/hoppscotch-common/src/components/http/Headers.vue
packages/hoppscotch-common/src/components/http/RequestVariables.vue

Closes HFE-543
This PR fixes the inconsistency in showing the wrap lines button in Headers in REST and GraphQl, Request Variable in REST  section. Now it only shows when Bulk mode is active.

fix: wrap line button showing inconsistency bug

---

packages/hoppscotch-common/src/components/http/ResponseMeta.vue
packages/hoppscotch-common/src/components/lenses/renderers/HTMLLensRenderer.vue
packages/hoppscotch-common/src/composables/lens-actions.ts
packages/hoppscotch-common/src/helpers/lenses/lenses.ts

Closes HFE-532
This pull request adds functionality to persist the HTML preview configuration. Previously, the configuration was not saved and had to be set every time the application was launched. With this change, the configuration will be saved locally, allowing the user's preference to persist.

feat: persist HTML response preview preference

---

packages/hoppscotch-common/src/components.d.ts
packages/hoppscotch-common/src/components/graphql/Response.vue
packages/hoppscotch-common/src/components/lenses/renderers/JSONLensRenderer.vue
packages/hoppscotch-common/src/components/lenses/renderers/RawLensRenderer.vue
packages/hoppscotch-common/src/components/realtime/Communication.vue
packages/hoppscotch-common/src/pages/realtime/socketio.vue
packages/hoppscotch-common/src/pages/realtime/websocket.vue

Closes #4201 
This PR fixes the issue with search bar in codemirror misaligning.

fix: codemirror search bar misaligned

---

packages/hoppscotch-common/src/helpers/utils/EffectiveURL.ts
packages/hoppscotch-selfhost-desktop/src-tauri/src/interceptor.rs
packages/hoppscotch-selfhost-desktop/src/platform/interceptors/native/index.ts

Closes #4162 
This PR is fixing some issues on sending file data:
1. Fix data variable type that sending to interceptor.rs 
2. Fix parameter filter for unsetted file
3. Add mime type for sending file
4. Fix double Content-Type header
5. Fix Cookie header. Removing it if not present 
This PR is tested on web and desktop app. Not for CLI

fix: fix issue for multipart/form-data and cookie header (#4162)

---

docker-compose.yml
packages/hoppscotch-backend/src/team-collection/team-collection.resolver.ts
packages/hoppscotch-backend/src/team-collection/team-collection.service.ts
packages/hoppscotch-backend/src/user-collection/user-collection.resolver.ts
packages/hoppscotch-backend/src/user-collection/user-collection.service.ts

Closes HSB-425
In this PR we are adding a new mutation to duplicate team and user collections.
```
For TeamCollections,
duplicateTeamCollection(collectionID: string) : Boolean
For UserCollections,
duplicateUserCollection(collectionID: string, reqType: ReqType) : Boolean
```
none

feat: duplicate team and user collections

---

packages/hoppscotch-cli/package.json
packages/hoppscotch-cli/src/__tests__/e2e/commands/__snapshots__/test.spec.ts.snap
packages/hoppscotch-cli/src/__tests__/e2e/commands/test.spec.ts
packages/hoppscotch-cli/src/__tests__/e2e/fixtures/collections/test-junit-report-export-coll.json
packages/hoppscotch-cli/src/commands/test.ts
packages/hoppscotch-cli/src/handlers/error.ts
packages/hoppscotch-cli/src/index.ts
packages/hoppscotch-cli/src/types/commands.ts
packages/hoppscotch-cli/src/types/errors.ts
packages/hoppscotch-cli/src/utils/collections.ts
packages/hoppscotch-cli/src/utils/pre-request.ts
packages/hoppscotch-cli/src/utils/reporters/junit.ts
packages/hoppscotch-cli/src/utils/request.ts
packages/hoppscotch-cli/tsconfig.json
pnpm-lock.yaml

Closes HFE-536, #4085.
This PR adds the ability to create JUnit report export for collection runs in the CLI via a newly added `--reporter-junit [path]` flag.  The report gets generated under the name `hopp-junit-report.xml` in the current path if the path is not specified.
```sh
hopp test <file_path_or_id> --env <file_path_or_id> --reporter-junit [path]
```
Consider [a collection](https://gist.github.com/jamesgeorge007/90c90ff4b8a49a756e68cc32638722e7) with two requests:
- Sends a `post` request to `echo.hoppscotch.io`.
- Content type set to `application/json`.
- Raw body specified as
```json
{
"key": "raw-body-value"
}
```
```js
// Test script
pw.test("Status code is 200", () => {
const { status } = pw.response;
pw.expect(status).toBe(200);
pw.expect(status).toBeLevel2xx();
}); …
```

feat(cli): add support for JUnit reporter

---

packages/hoppscotch-backend/src/team-collection/team-collection.service.ts
packages/hoppscotch-backend/src/user-collection/user-collection.service.ts
packages/hoppscotch-backend/src/utils.ts
packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components/collections/Collection.vue
packages/hoppscotch-common/src/components/collections/ImportExport.vue
packages/hoppscotch-common/src/components/collections/MyCollections.vue
packages/hoppscotch-common/src/components/collections/Request.vue
packages/hoppscotch-common/src/components/collections/TeamCollections.vue
packages/hoppscotch-common/src/components/collections/graphql/Collection.vue
packages/hoppscotch-common/src/components/collections/graphql/Folder.vue
packages/hoppscotch-common/src/components/collections/graphql/index.vue
packages/hoppscotch-common/src/components/collections/index.vue
packages/hoppscotch-common/src/helpers/backend/gql/mutations/DuplicateTeamCollection.graphql
packages/hoppscotch-common/src/helpers/backend/helpers.ts
packages/hoppscotch-common/src/helpers/backend/mutations/TeamCollection.ts
packages/hoppscotch-common/src/helpers/teams/TeamCollectionAdapter.ts
packages/hoppscotch-common/src/newstore/collections.ts
packages/hoppscotch-common/src/platform/index.ts
packages/hoppscotch-common/src/services/persistence/validation-schemas/index.ts
packages/hoppscotch-selfhost-web/src/api/mutations/DuplicateUserCollection.graphql
packages/hoppscotch-selfhost-web/src/main.ts
packages/hoppscotch-selfhost-web/src/platform/collections/collections.api.ts
packages/hoppscotch-selfhost-web/src/platform/collections/collections.platform.ts
packages/hoppscotch-selfhost-web/src/platform/collections/collections.sync.ts
packages/hoppscotch-selfhost-web/src/platform/collections/gqlCollections.sync.ts

This PR includes the UI changes adding the ability to duplicate REST/GraphQL collections. The context menu for collections (root/child) from the tree will include a new option labelled `Duplicate collection`. This will result in a new collection entry within the same hierarchy, effectively cloning the children and retaining the collection level authorization/header properties. Additionally, while the context menu is open, the duplication action can be initiated by pressing the `d` key.
> The duplication action is disabled under personal workspace in SH for now due to a known issue with syncing and will be revisited in a later iteration.
Closes HFE-491 HFE-545 HFE-547 #2475.
> The BE changes were implemented in #4207.
Apart from that, the following issues are patched:
- The …

feat: duplicate REST/GraphQL collections

---

packages/hoppscotch-backend/src/guards/infra-token.guard.ts

This PR resolves an bug on `infra-token.guard.ts` while checking the token is expire or not. `expiryOn` value can be `null`. So, this PR cover that conditions as well.
Nil

fix: infra token expriry check on guard

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components/collections/EditRequest.vue
packages/hoppscotch-common/src/components/collections/graphql/EditRequest.vue
packages/hoppscotch-common/src/components/collections/graphql/index.vue
packages/hoppscotch-common/src/components/collections/index.vue
packages/hoppscotch-common/src/newstore/settings.ts
packages/hoppscotch-common/src/pages/graphql.vue
packages/hoppscotch-common/src/pages/index.vue
packages/hoppscotch-common/src/pages/settings.vue
packages/hoppscotch-common/src/platform/experiments.ts
packages/hoppscotch-common/src/platform/index.ts
packages/hoppscotch-common/src/services/persistence/validation-schemas/index.ts

**Changes**
1. This PR adds a new platform definition entry `Experiments` to add support for bringing ai experiments into hoppscotch platforms. right now the features are enabled only for our cloud instance. but these changes enable ai experiments to be enabled when needed across platforms.
2. The initial feature we bring as part of our AI experiments is the ability to generate automatic names for any request. this PR also adds code that enables this feature to corresponding components.
note: there's duplication between the GQL & REST components currently. we could move the request rename logic into a seperate service. but differing this for now.

feat: hoppscotch-common & platform additions for ai experiments

---

packages/hoppscotch-common/src/components/collections/EditRequest.vue
packages/hoppscotch-common/src/components/collections/graphql/EditRequest.vue
packages/hoppscotch-common/src/platform/analytics.ts

**Changes**
This PR introduces a new analytics event `EXPERIMENTS_GENERATE_REQUEST_NAME_WITH_AI` to track the usage of renaming requests with AI.

chore: add analytics event for ai experiments

---

packages/hoppscotch-cli/package.json

An attempt to install the CLI was halted due to the addition of the `postinstall` script. This PR removes the same and resolves this behaviour. Follow up of #4189.
The `pretest` script executing `pnpm run build` has been removed and the same is achieved via clubbing it with the `test` script since the `pretest` script was found not to be executed in the CI environment.
CLI version is bumped to `v0.10.1`.
Closes #4227.

fix(cli): remove `postinstall` script

---

packages/hoppscotch-common/src/services/context-menu/menu/parameter.menu.ts

Closes #4234
- The regex for parsing parameters has changed to support more valid url parameters
- It is able to parse more complicated key values like a lot of online parsers
The key can contain any character expect  '&' and a '='
A value can contain any character expect a '&' (which will start the next key) - it can include a '='
Reference: https://semalt.tools/en/url-parser

fix: add to parameters regex

---

packages/hoppscotch-common/src/helpers/realtime/SIOClients.ts
packages/hoppscotch-common/src/helpers/realtime/SIOConnection.ts

Socket.IO connection was failing for the server deployed on a custom path.
The reason being that path was not passed to the client implementations unless there was bearer token configured.
The bug appeared in https://github.com/hoppscotch/hoppscotch/pull/2228 when for some reason path option was not handed over to the `SIOClient` anymore after the refactor
| Before https://github.com/hoppscotch/hoppscotch/pull/2228 |      After https://github.com/hoppscotch/hoppscotch/pull/2228   |
|----------|:-------------:|
| ![Code_QWfE1zRfaJ](https://github.com/user-attachments/assets/2832b605-be82-4844-b7d3-52f29d3bd707) | ![Code_AGgl6wthbA](https://github.com/user-attachments/assets/a71e4b70-2e52-4e0c-991e-8882a2b6e790) |

fix: path not taken into account for socket.io connection without token auth

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components/environments/index.vue
packages/hoppscotch-common/src/components/environments/my/Environment.vue

Duplicating the `Global environment` is an action specific to the personal workspace. The above context isn't conveyed while attempting the action from a team workspace. New environment entries are added under the personal workspace with a success toast. This PR hides the `Global environment` duplicate action while at a team workspace. The same action via spotlight is enabled regardless of the active workspace.
https://github.com/user-attachments/assets/0b16eb2c-6c91-446d-9302-13377ec0ef2c
- A new prop `showDuplicateActions` added under the `EnvironmentsMyEnvironment` component that defaults to `true`. It is set based on the active workspace type for the `Global environment` entry.
- Compile repeated checks in computed properties.
- Resolves a few pre-existing type errors found in scope. …

chore: hide duplicate `Global environment` action for a team workspace

---

packages/hoppscotch-common/src/components/collections/AddRequest.vue
packages/hoppscotch-common/src/components/collections/EditRequest.vue
packages/hoppscotch-common/src/components/collections/SaveRequest.vue
packages/hoppscotch-common/src/components/collections/graphql/AddRequest.vue
packages/hoppscotch-common/src/components/collections/graphql/EditRequest.vue
packages/hoppscotch-common/src/components/collections/graphql/index.vue
packages/hoppscotch-common/src/components/collections/index.vue
packages/hoppscotch-common/src/composables/ai-experiments.ts
packages/hoppscotch-common/src/helpers/import-export/import/insomnia.ts

1. move the rename logic to a composable `useRequestNameGeneration` to remove duplication among multiple components having the rename logic
2. adds rename with ai sparkle icons to
- adding a new request from the sidebar
- save as request modal
3. detect if the rename is triggered from graphql / rest  using the current route the user is in

chore: add ai renames at more places

---

packages/hoppscotch-common/locales/de.json

In #4195 I already fixed this translation.
I don't know why, but in #4196 I somehow overwrote it with the old (wrong) translation.
So now I would like to fix this translation (again).

i18n: Fix german translation for "label"

---

.env.example
packages/hoppscotch-backend/prisma/migrations/20240725043411_infra_config_encryption/migration.sql
packages/hoppscotch-backend/prisma/schema.prisma
packages/hoppscotch-backend/src/infra-config/helper.ts
packages/hoppscotch-backend/src/infra-config/infra-config.service.spec.ts
packages/hoppscotch-backend/src/infra-config/infra-config.service.ts
packages/hoppscotch-backend/src/user/user.service.ts
packages/hoppscotch-backend/src/utils.ts

Closes HSB-473
This PR introduces data encryption before storing sensitive data in the database. For example, previously we stored SSO's secret key as plain text in the infraConfig table. From now on, before saving to DB, the value will be encrypted.
Also, after fetching the data from the DB, we decrypt it to the original value to use.
In `Account` and `InfraConfig` tables, we added encryption and decryption logic to store/ fetch sensitive data.
Nil

HSB-473 feat: encrypt sensitive data before storing in db

---

packages/hoppscotch-common/src/components/environments/index.vue
packages/hoppscotch-common/src/services/secret-environment.service.ts

Closes HFE-560
This PR fixes the a bug in the environment selector where the current environment was not getting invalidated while switching shared workspaces.
The current environment flow will be as following - 
- user has a personal env selected, changes to a shared workspace - selected env does not change
- user has a team env selected, changes to another shared workspace or personal workspace- change current env to `NO_ENV_SELECTED`
Current selected environment switches to `NO_ENV_SELECTED` if there is switch in shared workspace.

fix: reset currentEnv if there is a shared workspace change

---

packages/hoppscotch-common/src/components/app/WhatsNewDialog.vue
packages/hoppscotch-common/src/composables/whats-new.ts

This PR updates the WhatsNewDialog style to position it at the bottom of the main window (excluding the app footer) rather than the viewport including the footer. This is achieved by adjusting the bottom offset of the toaster.

chore: update WhatsNewDialog UI and position

---

packages/hoppscotch-selfhost-desktop/src/lib/sync/index.ts
packages/hoppscotch-selfhost-desktop/src/platform/settings/settings.sync.ts
packages/hoppscotch-selfhost-web/src/lib/sync/index.ts
packages/hoppscotch-selfhost-web/src/platform/settings/settings.sync.ts

Previously, the following settings were not getting synced in SH:
- `Expand navigation` & `Sidebar on left` under `Experiments`.
- Spotlight open status.
- Wrap lines preference under request params, headers in bulk mode, etc.
- `Collections`, `Environments` & `History` synchronization settings under the profile page.
This was the case since the relevant store dispatcher methods were not present under the store sync definition maintained at the platform level. This PR resolves this behaviour by extending the above definition accordingly. There was also a known issue with toggling the synchronization settings (Collections, Environments & History) under the profile page resulting in an exception which is fixed by adding safeguards with the usage of `startSubscriptions()` & …

fix: sync all settings actions in SH

---

aio-multiport-setup.Caddyfile
aio-subpath-access.Caddyfile
packages/hoppscotch-backend/backend.Caddyfile
packages/hoppscotch-selfhost-web/Caddyfile
packages/hoppscotch-selfhost-web/selfhost-web.Caddyfile
packages/hoppscotch-sh-admin/Caddyfile
packages/hoppscotch-sh-admin/sh-admin-multiport-setup.Caddyfile
packages/hoppscotch-sh-admin/sh-admin-subpath-access.Caddyfile
prod.Dockerfile

Closes #4257 #4264 
This PR aims to fix the issues caused due to the introduction of non-root users in the selfhost containers introduced in #4233. The removal of the root user from the container execution scope is still something we will try to pursue later on once we have more understanding of the implications.
1. Revert the docker commands to make a non-root user that executes the container and returns it back to the default.
2. Remove Caddy Admin Endpoint (this endpoint is not exposed so shouldn't affect anyways) and config persistence
N/A

fix: issues with port binding in different container runtimes

---

packages/hoppscotch-common/src/components/http/Request.vue
packages/hoppscotch-common/src/helpers/rest/document.ts
packages/hoppscotch-common/src/services/persistence/validation-schemas/index.ts

Closes #4271 HFE-565
This PR fixes the bug where when sending a request in tab1, the button `send` changes to `cancel`. Before the request finishes switching to tab2 and back to tab1, the `cancel` button disappears.
The text now depends on the tab response loading state rather than a component-level loading value. Also, a new field `cancelFunction` is added under the tab document `HoppRESTDocument` to keep a reference to the cancel function to cancel the current request in execution.

fix: persist request execution context between tabs

---

.env.example

Closes #4205
In the official Hoppscotch documentation or the `.env.example` file in the GitHub repo, only these two variables had inline comments:
```
REFRESH_TOKEN_VALIDITY=604800000 # Default validity is 7 days (604800000 ms) in ms
ACCESS_TOKEN_VALIDITY=86400000 # Default validity is 1 day (86400000 ms) in ms
```
But environment variables can’t use inline comments.
Some people who are not familiar with this common sense including me, maybe troubled by this problem when copying the contents of an env file from the github repo.

bug: .env.example fix comments formatting

---

packages/hoppscotch-cli/package.json
packages/hoppscotch-cli/src/__tests__/e2e/commands/test.spec.ts
packages/hoppscotch-cli/src/__tests__/e2e/fixtures/collections/request-vars-coll.json
packages/hoppscotch-cli/src/__tests__/e2e/fixtures/environments/request-vars-envs.json
packages/hoppscotch-cli/src/__tests__/unit/getters.spec.ts
packages/hoppscotch-cli/src/utils/getters.ts
packages/hoppscotch-cli/src/utils/pre-request.ts
packages/hoppscotch-cli/src/utils/request.ts

This PR adds support for request variables in the CLI. Request variables will have the topmost priority, meaning they will be preferred over any environment variables sharing the same name.
Closes HFE-552.
- New `getResolvedVariables()` helper function added under [~/utils/getters.ts](https://github.com/hoppscotch/hoppscotch/pull/4275/files#diff-484af5d66255ca92b321d69e2ad27f54a0323413d566793f2a117e15cceb3261) that takes in the list of request variables and environment variables for a session and returns a resolved list of variables where keys sharing the same name from environment variables are removed ensuring request variables take priority.
- Relevant instances are updated to account for request variables, alongside environment variables via the above helper function.
- Relevant test …

feat(cli): add support for request variables

---

.github/workflows/tests.yml
packages/hoppscotch-cli/src/__tests__/e2e/fixtures/collections/multiple-child-collections-auth-headers-coll.json
packages/hoppscotch-cli/src/__tests__/unit/fixtures/workspace-access.mock.ts
packages/hoppscotch-cli/src/__tests__/unit/getters.spec.ts
packages/hoppscotch-cli/src/__tests__/unit/workspace-access.spec.ts
packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components.d.ts
packages/hoppscotch-common/src/components/collections/Properties.vue
packages/hoppscotch-common/src/components/graphql/Headers.vue
packages/hoppscotch-common/src/components/http/Body.vue
packages/hoppscotch-common/src/components/http/Headers.vue
packages/hoppscotch-common/src/components/http/KeyValue.vue
packages/hoppscotch-common/src/components/http/Parameters.vue
packages/hoppscotch-common/src/helpers/curl/__tests__/curlparser.spec.js
packages/hoppscotch-common/src/helpers/curl/curlparser.ts
packages/hoppscotch-common/src/helpers/curl/sub_helpers/headers.ts
packages/hoppscotch-common/src/helpers/curl/sub_helpers/queries.ts
packages/hoppscotch-common/src/helpers/import-export/import/insomnia.ts
packages/hoppscotch-common/src/helpers/import-export/import/openapi.ts
packages/hoppscotch-common/src/helpers/import-export/import/postman.ts
packages/hoppscotch-common/src/helpers/utils/EffectiveURL.ts
packages/hoppscotch-common/src/services/context-menu/menu/parameter.menu.ts
packages/hoppscotch-common/src/services/persistence/__tests__/__mocks__/index.ts
packages/hoppscotch-data/src/collection/index.ts
packages/hoppscotch-data/src/collection/v/2.ts
packages/hoppscotch-data/src/collection/v/3.ts
packages/hoppscotch-data/src/graphql/index.ts
packages/hoppscotch-data/src/graphql/v/6.ts
packages/hoppscotch-data/src/rest/index.ts
packages/hoppscotch-data/src/rest/v/7.ts

This PR introduces a new `description` field for both request parameters and headers in the API documentation. This allows developers to provide clear and concise explanations for each parameter and header, enhancing the readability and usability of the documentation. It is also added for headers at the collection level.
The `description` field is also accounted for while importing from external sources (`Postman`, `Insomnia` & `OpenAPI`).
A pre-existing issue where edits made to headers from the bulk edit context are not immediately reflected in the default view is resolved.
Closes HFE-535 HFE-538.
> For the auto-generated `Authorization` and `Content-Type` headers, the `description` field will stay disabled and the value will appear empty; while for inherited headers the value specified …

feat: description field for request parameters and headers

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components/environments/Selector.vue
packages/hoppscotch-common/src/components/environments/my/Details.vue
packages/hoppscotch-common/src/components/environments/my/index.vue
packages/hoppscotch-common/src/components/environments/teams/Details.vue
packages/hoppscotch-common/src/components/environments/teams/Environment.vue
packages/hoppscotch-common/src/components/environments/teams/index.vue
packages/hoppscotch-common/src/helpers/utils/sortEnvironmentsAlphabetically.ts

Closes HFE-551
This PR sorts the environments in alphabetical order on the environment section in the sidebar and the environment selector.
The environments have been sorted alphabetically by default for both personal and team. Also made 3 letter minimum length for creating a Personal Environment which was already the criteria for creating a Team Environment.

feat: sort environments alphabetically

---

packages/hoppscotch-cli/src/__tests__/e2e/commands/test.spec.ts
packages/hoppscotch-cli/src/__tests__/e2e/fixtures/collections/multipart-form-data-coll.json
packages/hoppscotch-cli/src/__tests__/e2e/fixtures/collections/oauth2-auth-code-coll.json
packages/hoppscotch-cli/src/__tests__/functions/request/requestRunner.spec.ts
packages/hoppscotch-cli/src/interfaces/request.ts
packages/hoppscotch-cli/src/utils/getters.ts
packages/hoppscotch-cli/src/utils/pre-request.ts
packages/hoppscotch-cli/src/utils/request.ts
packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components/collections/graphql/index.vue
packages/hoppscotch-common/src/components/collections/index.vue
packages/hoppscotch-common/src/components/http/OAuth2Authorization.vue
packages/hoppscotch-common/src/pages/oauth.vue
packages/hoppscotch-common/src/services/oauth/flows/authCode.ts
packages/hoppscotch-common/src/services/oauth/oauth.service.ts
packages/hoppscotch-data/src/collection/v/3.ts
packages/hoppscotch-data/src/graphql/index.ts
packages/hoppscotch-data/src/graphql/v/6.ts
packages/hoppscotch-data/src/rest/index.ts
packages/hoppscotch-data/src/rest/v/7.ts

Fixes HFE-548
**Changes**
This PR adds the ability to refresh generated oauth tokens. We only enable refresh tokens for the `AuthCode` flow. for other flows it doesnt make much sense to add refresh token flows as per my reading. ( but incase we get user requests, we can easily add that ).
The support for the OAuth 2 authorization type is extended to the CLI, relevant business logic to derive `Authorization` headers already existed but a request with the Authorization type set to `oauth-2` was blocked previously reporting a status code of `501` which is changed herewith. This was also the case with the `multipart/form-data` content type which is enabled along with. Necessary updates are made to the test suite aimed at increasing coverage along with the relevant fixture additions.

feat: ability to refresh tokens for oauth flows

---

prod.Dockerfile

Closes # 
This Pull Requests adds the Open Containers Initiative (OCI) labels to the Docker image. This is useful for tools like Renovate Bot to be able to add changelog/release note information to a Pull Request.
As you can see on this PR (https://github.com/DevSecNinja/home/pull/596), Renovate can't find the change log for Hoppschotch while it can for PRs like this: https://github.com/DevSecNinja/home/pull/627
See the following docs:
Renovate Doc: https://docs.renovatebot.com/modules/datasource/docker/#description
Example from Renovate: https://github.com/renovatebot/renovate/blob/main/tools/docker/Dockerfile#L78C1-L81C52
OCI spec sheet: https://specs.opencontainers.org/image-spec/annotations/

Add Open Containers Initiative (OCI) labels

---

packages/hoppscotch-common/src/components/collections/Properties.vue
packages/hoppscotch-common/src/components/environments/teams/Details.vue
packages/hoppscotch-common/src/components/graphql/Headers.vue
packages/hoppscotch-common/src/components/graphql/RequestOptions.vue
packages/hoppscotch-common/src/components/http/Headers.vue
packages/hoppscotch-selfhost-web/src/platform/collections/collections.platform.ts

This PR includes a fix for the following issues:-
- Bulk mode editor wasn't visible in the collection properties modal.
- Attempting to create an environment from a team workspace without specifying a name will result in an infinite loading state regardless of reopening the modal since the component doesn't unmount.
- The `Go to Authorization tab` action from the headers view under the REST/GQL collection properties modal and under the GQL request didn't have an effect.
Also, a few type errors are resolved and proper migrations are added while resolving the `headers` field in the syncing context.
- The `absolute` property for the header bulk editor is disabled for the collection property modal.
- The latest version of `HoppCollection` is specified while pulling collections from upstream …

fix: resolve multiple UI issues and account for `description` field in syncing context

---

packages/hoppscotch-cli/package.json
packages/hoppscotch-cli/src/__tests__/e2e/commands/test.spec.ts
packages/hoppscotch-cli/src/__tests__/e2e/fixtures/collections/aws-signature-auth-coll.json
packages/hoppscotch-cli/src/__tests__/e2e/fixtures/environments/aws-signature-auth-envs.json
packages/hoppscotch-cli/src/utils/pre-request.ts
pnpm-lock.yaml

#4142 adds support for the AWS Signature Authorization type in the UI. This PR extends support for the same in the CLI.
Closes HFE-568.
- Business logic addition for translating the supplied authorization filed values to headers/query params as opted.
- [aws4fetch](https://www.npmjs.com/package/aws4fetch) is added as a dependency to assist with request signing.
- Relevant test suite updates and fixture additions.
Save the request used while verifying the UI changes in #4142 to a collection and export it. Switch to this branch navigate to the CLI path locally and build it. Now, supply the collection file path along with the `test` command and ensure the requests report a status code of `200`.

feat(cli): add support for AWS Signature Authorization type

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components/http/Codegen.vue
packages/hoppscotch-common/src/components/http/Request.vue
packages/hoppscotch-common/src/components/http/ResponseInterface.vue
packages/hoppscotch-common/src/helpers/RequestRunner.ts
packages/hoppscotch-common/src/helpers/utils/EffectiveURL.ts

Closes #4314 
This PR includes fixes for the following issues:-
- Codegen Sidebar crashes upon opening and shows up as blank.
- Choosing AWS Signature as the Authorization type without populating the relevant fields and attempting to send a request results in an exception. Saving the request to a collection in this state and attempting to run it via the CLI will lead to the same error since they are required fields.
- `getEffectiveRESTRequest` returns a Promise, this was not awaited in the computation for the code generation, leading to a null reference, crashing the sidebar. The correction was to await the promise and evaluate based on that. This has been extended to all places of usage.
- Assign default values (empty string) corresponding to the fields while choosing `AWS Signature` as …

fix: sidebar codegen crashing and AWS Signature Auth flow

---

packages/hoppscotch-common/src/components/collections/ImportExport.vue
packages/hoppscotch-common/src/components/collections/graphql/ImportExport.vue
packages/hoppscotch-common/src/components/environments/ImportExport.vue
packages/hoppscotch-common/src/components/environments/my/Environment.vue
packages/hoppscotch-common/src/components/environments/teams/Environment.vue
packages/hoppscotch-common/src/helpers/import-export/export/environment.ts
packages/hoppscotch-common/src/helpers/import-export/export/index.ts
packages/hoppscotch-common/src/platform/std/io.ts

This PR enforces the usage of platform-based API for file exports ensuring compatibility across web and Desktop apps. This accounts for export flows related to collections (REST/GQL) & environments.
Closes #4332 HFE-578.
- The `initializeDownloadCollection()` helper function is renamed to `initializeDownloadFile()` and the implementation has been updated to rely on the platform-level APIs instead of the browser-based behaviour. It now returns a promise.
- For exports in general, there'll be a suggested name having the name computed from the URL (based on contents) as a fallback. The platform-level definition under `hoppscotch-selfhost-web` `saveFileWithDialog()`, is updated to prioritise the name if supplied.
- The `exportAsJSON` helper function compiling the export business logic for …

fix: ensure cross-platform compatibility with file exports

---

.github/workflows/codeql-analysis.yml
.github/workflows/release-push-docker.yml
.github/workflows/ui.yml

Required for using Node.js 20.x in CI
* Changelog for actions/checkout@v4 https://github.com/actions/checkout/blob/main/CHANGELOG.md?rgh-link-date=2024-09-04T18%3A38%3A10Z#v400
* Changelog for actions/setup-node@v4 https://github.com/actions/setup-node/releases/tag/v4.0.0
GitHub Blog post: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

chore: bump github actions to v4

---

packages/hoppscotch-common/src/composables/codemirror.ts

Closes #4327 HFE-577
This PR fixes the issue wherewith context menu where it fails to close while there is a key press and no text selection is present.

fix: close context menu when no text is selected

---

packages/hoppscotch-common/src/components/http/KeyValue.vue

When turning a query parameter/header or header on/off, the `Description` field gets cleared.
- Account for the `description` field value while toggling the field enabled status by supplying it alongside the `updateEntity()` function call.
- Enforce stricter types.

fix: preserve description while toggling field enabled status

---

packages/hoppscotch-common/src/components/environments/index.vue

Closes HFE-597 #4355 
This PR fixes the bug with workspace environment where workspace environments list view falls back to personal environments while navigating to the REST page.
Have added an immediate prop to watch the workspace type so that the list gets updated on page mounting.

fix: workspace environment list reset bug

---

packages/hoppscotch-selfhost-web/package.json
packages/hoppscotch-selfhost-web/vite.config.ts
pnpm-lock.yaml

Recently we had the below issue on our cloud instance, this PR adds the necessery changes required to preemptively fix this. 
**Before**
Whenever a release is out, our webapp seems to get an empty screen. this is happening due to a resource going above the max file size for getting cached and being left out from the precache.
so this is happening,
1. the initial service worker is built, but the oversized file is not included in the service worker cache
2. so when we load the app for the first time, the browser will go and fetch the oversized file from the server, no issues
3. but when a new release is rolled out, the server doesnt have the old oversized file, its hash might have changed, so when the browser tries to go and fetch it, it will get a 404 ( or a redirect to index.html based on …

fix: preemptly update pwa settings to avoid missing files in the service worker cache

---

packages/hoppscotch-common/src/components/collections/ImportExport.vue
packages/hoppscotch-common/src/components/collections/graphql/ImportExport.vue
packages/hoppscotch-common/src/components/environments/ImportExport.vue
packages/hoppscotch-common/src/components/importExport/ImportExportSteps/FileImport.vue
packages/hoppscotch-common/src/components/importExport/ImportExportSteps/MyCollectionImport.vue
packages/hoppscotch-common/src/components/importExport/ImportExportSteps/UrlImport.vue
packages/hoppscotch-common/src/helpers/import-export/import/import-sources/FileSource.ts
packages/hoppscotch-common/src/helpers/import-export/import/import-sources/GistSource.ts
packages/hoppscotch-common/src/helpers/import-export/import/import-sources/UrlSource.ts

This PR addresses the need for a loading state in the `Import/Export` modals that includes collections and environments in scope.
Closes #4145 HFE-594.
- Introduce state variables to keep track of the loading status during a network call while importing to the data store applicable to the team workspace. The `handleImportToStore` function promise resolution is awaited.
- Introduce a `loading` prop to the `FileImport` & `UrlImport` components that default to `false` - toggles the `Import` CTA loading state accordingly. The import CTA stays disabled during a loading state.
- Adds a `loading` prop to the `MyCollectionImport` component to handle the loading state with import from personal collections flow while at a team workspace.
- The `FileSource()` & `UrlSource()` functions now include a …

feat: add loading state for import actions

---

packages/hoppscotch-selfhost-desktop/src-tauri/tauri.conf.json

The desktop application was failing to launch across multiple operating systems and build types. Users reported a perpetual loading spinner.
Closes HFE-598, Closes #4348 , Closes #4100 
- The application now launches successfully on all tested platforms and build types.
- Loading spinner issue is resolved.
- JavaScript compilation errors and EvalErrors related to CSP are no longer occurring.
- GraphQL connections are successful.

fix(desktop): content security policy config preventing app launch

---

packages/hoppscotch-backend/src/team-environments/team-environments.service.ts
packages/hoppscotch-common/src/components/environments/Add.vue
packages/hoppscotch-common/src/components/environments/Selector.vue
packages/hoppscotch-common/src/components/environments/index.vue
packages/hoppscotch-common/src/components/environments/my/Environment.vue
packages/hoppscotch-common/src/components/environments/teams/Details.vue
packages/hoppscotch-common/src/components/environments/teams/Environment.vue
packages/hoppscotch-common/src/components/environments/teams/index.vue
packages/hoppscotch-common/src/helpers/error-messages/index.ts

The duplicate global environment action was specific to the personal workspace, where the entries were added and hidden while at a team workspace with #4245. This PR re-enables the action under team workspaces and extends support. Also, the following changes are added alongside applicable to team workspaces:
- Loading states addition for duplicate regular & global environment actions via the context menu.
- Adds a `- Duplicate` suffix for duplicated environment entries.
Closes HFE-575.
https://github.com/user-attachments/assets/c406ff47-b191-4857-a1ea-06ca4bd6b567
- Adds new props `duplicateGlobalEnvironmentLoading` (keeps track of the n/w call status and dismisses the context menu) & `showContextMenuLoadingState` (Indicates the context menu is to be displayed during the n/w call in a …

feat: duplicate global environment under team workspaces

---

docker-compose.yml
packages/hoppscotch-backend/src/pubsub/topicsDefs.ts
packages/hoppscotch-backend/src/user-collection/user-collection.resolver.ts
packages/hoppscotch-backend/src/user-collection/user-collection.service.ts
packages/hoppscotch-backend/src/user-collection/user-collections.model.ts

Closes HSB-476
In this PR we add a new GQL subscription `userCollectionDuplicated` which returns the entire UserCollection tree when subscribed to.
Nil

chore: addition of new GQL subscription for `UserCollection` duplication

---

packages/hoppscotch-common/src/services/spotlight/searchers/response.searcher.ts

This PR adds ability to open `Generate Data Schema` sidebar from the searcher

feat: add generate data schema option in spotlight searcher

---

packages/hoppscotch-backend/src/team-collection/team-collection.resolver.ts
packages/hoppscotch-backend/src/team-collection/team-collection.service.ts
packages/hoppscotch-backend/src/user-collection/user-collection.resolver.ts
packages/hoppscotch-backend/src/user-collection/user-collection.service.ts
packages/hoppscotch-backend/src/utils.ts

Closes HSB-470
In this PR we add 2 new queries that can be used to export a single `UserCollection` and a `TeamCollection`.
The queries are :
- `exportUserCollectionToJSON`
- `exportCollectionToJSON`
nil

chore: export single User/Team Collection

---

packages/hoppscotch-cli/src/__tests__/unit/workspace-access.spec.ts
packages/hoppscotch-common/src/components/http/authorization/OAuth2.vue
packages/hoppscotch-common/src/services/oauth/flows/clientCredentials.ts
packages/hoppscotch-common/src/services/oauth/flows/password.ts
packages/hoppscotch-common/src/services/persistence/__tests__/__mocks__/index.ts
packages/hoppscotch-data/src/collection/index.ts
packages/hoppscotch-data/src/collection/v/3.ts
packages/hoppscotch-data/src/collection/v/4.ts
packages/hoppscotch-data/src/graphql/index.ts
packages/hoppscotch-data/src/graphql/v/3.ts
packages/hoppscotch-data/src/graphql/v/4.ts
packages/hoppscotch-data/src/graphql/v/6.ts
packages/hoppscotch-data/src/graphql/v/7.ts
packages/hoppscotch-data/src/rest/index.ts
packages/hoppscotch-data/src/rest/v/8.ts
packages/hoppscotch-selfhost-web/src/platform/collections/collections.platform.ts

**Changes**
* Makes client_secret optional for `clientCredentials` and `password` oauth flows. 
* Some schemas were imported with the latest version of dependent schemas instead of the one compatible with them. This PR fixes those imports to point to the correct schemas.
* Update the collection schema to use the updated auth schemas
* Test suite updates accounting for version bumps at the schema level.

chore: make client secret optional across grant types

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components/aiexperiments/ModifyBodyModal.vue
packages/hoppscotch-common/src/components/collections/AddRequest.vue
packages/hoppscotch-common/src/components/collections/EditRequest.vue
packages/hoppscotch-common/src/components/collections/SaveRequest.vue
packages/hoppscotch-common/src/components/collections/graphql/AddRequest.vue
packages/hoppscotch-common/src/components/collections/graphql/EditRequest.vue
packages/hoppscotch-common/src/composables/ai-experiments.ts

**Changes**
1. Updated the copy for requesting feedback after request name generation
2. Remove toast after submitting feedback
3. Submit the modify body prompt on the `Enter` key press.
4. Add a 'Generate' copy to the modify body prompt submit button
5. Ask for feedback following each prompt generation applying to generate request name/modify request body flows.

fix: update copy + improve ux on ai experiments

---

packages/hoppscotch-common/src/services/persistence/validation-schemas/index.ts

This PR fixes the issue with rest tab schema where the tab didn't have type property that lead's to app crashing.
A catch was added to the type property where the default value will be set to "request"

fix: add fallback for `type` field in `restTabState` schema

---

packages/hoppscotch-common/src/components/http/RawBody.vue
packages/hoppscotch-common/src/helpers/editor/linting/jsoncPretty.ts
packages/hoppscotch-common/src/helpers/jsoncParse.ts

Enhancements to JSON's Comment Functionality. This pull request addresses an issue encountered with Prettier when parsing JSON strings containing comments. 
```json
{
"id":       "first",
"id":                  "second",
"key": {
//another comment
"another_key": "another_value",
},
//hello comment
}
```

fix: prettier for json with comments

---

packages/hoppscotch-common/src/components/lenses/renderers/ImageLensRenderer.vue

Closes #3565
This update specifies the MIME type when creating the blob, which resolves the issue with the incorrect Base64 header.

fix: correct SVG rendering issue by adjusting blob type (#3565)

---

packages/hoppscotch-common/package.json
packages/hoppscotch-common/src/helpers/editor/linting/jsonc.ts
pnpm-lock.yaml

This PR intends to fix the issue where the new JSONC system strips parts of URLs when it strips comments.
The `removeComments` function converts the following string erroneously:
Input:
```json
{
"hello": "https://echo.hoppscotch.io"
}
```
Output:
```
{
"hello": "https
}
```
1.  Add `jsonc-parser` NPM package as a dependency
2. Use `jsonc-parser` implementation to strip comments instead of the current implementation.

fix: comments being stripped out of json request body

---

packages/hoppscotch-common/src/components/environments/my/index.vue

Previously, attempting to edit the active environment under personal workspace entry via `Environment Quick Peek` will result in the modal getting displayed with variables from another environment entry. This PR includes a fix for the same.
Closes #4380
Fixed a function to define current env by name

fix: resolve personal environments correctly while editing via quick peek

---

packages/hoppscotch-common/src/pages/index.vue
packages/hoppscotch-common/src/services/spotlight/searchers/request.searcher.ts

**Changes**
PR #4382 introduced a change, where we were passing just the tab name as context instead of the full request to the request rename endpoint. This PR overwrites that change.
Also, spotlight actions specific to a request open under the active tab were in context even for response examples. This includes a fix for the same.

fix: add full request as request context

---

packages/hoppscotch-backend/package.json
pnpm-lock.yaml

Closes HSB-494
This PR downgraded Eslint related npm packages  to `v8` version in `hoppscotch-backend` which ware previously upgraded to `v9` which introduces braking changes.
Nil

HSB-494 fix: downgrade eslint related package

---

packages/hoppscotch-common/src/components/collections/Add.vue
packages/hoppscotch-common/src/components/collections/AddFolder.vue
packages/hoppscotch-common/src/components/collections/AddRequest.vue
packages/hoppscotch-common/src/components/collections/Edit.vue
packages/hoppscotch-common/src/components/collections/EditFolder.vue
packages/hoppscotch-common/src/components/collections/EditRequest.vue
packages/hoppscotch-common/src/components/environments/teams/Details.vue
packages/hoppscotch-common/src/components/teams/Add.vue

This PR adds a check condition to the multiple cases where a repeated keypress will create multiple requests while in loading state. The changes made closes the issue #4134.
- In collections, functions that add or edit collections now return early if the button is in loading state.
- Similarly, add or edit functions in environment and teams also return early in loading state.

fix: prevent keypress actions in the loading state

---

packages/hoppscotch-common/src/components/accessTokens/List.vue

This PR aims to fix a broken reference to an image as part of the `Personal Access Tokens` view empty state on the profile page. Follow up of #4304.
Closes HFE-629.
`colorMode` as consumed from the `useColorMode()` composable is a `reactive` object, hence, inferring the current `Background` selection via the `value` field.
https://github.com/hoppscotch/hoppscotch/blob/9da5f63e701ba072ea393e68847d7f8e395d4c4a/packages/hoppscotch-common/src/modules/theming.ts#L54-L60
https://github.com/hoppscotch/hoppscotch/blob/9da5f63e701ba072ea393e68847d7f8e395d4c4a/packages/hoppscotch-common/src/composables/theming.ts#L1-L4

fix: resolve empty state image correctly in profile page

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components/importExport/ImportExportSteps/FileImport.vue
packages/hoppscotch-common/src/platform/index.ts
packages/hoppscotch-common/src/platform/limits.ts
packages/hoppscotch-selfhost-web/src/main.ts

- Closes HFE-615
- Fixes #4139 
This PR adds the ability to set custom collection import size limit and change it from the default value of 10MB. The size limit for selfhost-web will now be 50MB.

feat(common): introducing ability to set custom collection import size limit

---

packages/hoppscotch-agent/devenv.nix
packages/hoppscotch-agent/package.json
packages/hoppscotch-agent/src-tauri/Cargo.lock
packages/hoppscotch-agent/src-tauri/Cargo.toml
packages/hoppscotch-agent/src-tauri/src/error.rs
packages/hoppscotch-agent/src-tauri/src/state.rs
packages/hoppscotch-agent/src-tauri/src/updater.rs
pnpm-lock.yaml

This PR updates several dependencies in the Hoppscotch Agent, including `tauri-plugin-store`, `tauri-plugin-dialog`, and other Rust and JavaScript packages. 
Closes HFE-628
- Updated the store API in `state.rs` to handle store operations using new methods like `.set()` and `.delete()`, replacing `.insert()` and `.map_err()`.
- As an extension added error propagation.
- `StoreBuilder::new()` now requires a reference to `app_handle`.
- `updater.rs` now uses `MessageDialogButtons` for dialog button customization, replacing `.ok_button_label()` and `.cancel_button_label()`.

chore(agent): major version dependency bump

---

packages/hoppscotch-selfhost-desktop/.envrc
packages/hoppscotch-selfhost-desktop/.gitignore
packages/hoppscotch-selfhost-desktop/devenv.lock
packages/hoppscotch-selfhost-desktop/devenv.nix
packages/hoppscotch-selfhost-desktop/devenv.yaml
packages/hoppscotch-selfhost-desktop/src-tauri/Cargo.lock
packages/hoppscotch-selfhost-desktop/src-tauri/Cargo.toml
packages/hoppscotch-selfhost-desktop/src-tauri/src/interceptor.rs

PR adds `hoppscotch-relay` for HTTP request-response relay to be used in interceptor.
Closes HFE-635

feat: `hoppscotch-relay` for request forwarding

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components/collections/Request.vue
packages/hoppscotch-common/src/components/http/Codegen.vue
packages/hoppscotch-common/src/components/lenses/renderers/JSONLensRenderer.vue
packages/hoppscotch-common/src/components/lenses/renderers/RawLensRenderer.vue
packages/hoppscotch-common/src/components/teams/Invite.vue
packages/hoppscotch-common/src/helpers/backend/mutations/TeamInvitation.ts

Closes HFE-637 HFE-630
This PR fixes the following
- Bug with codegen section where it was breaking when the response example tab was active
- Minor UI polish
- Update team invite UI and i18n strings for more intuitive text.

fix: codegen breaking in example tab and minor UI updates

---

packages/hoppscotch-common/src/components/environments/ImportExport.vue
packages/hoppscotch-common/src/components/environments/my/Details.vue
packages/hoppscotch-common/src/components/environments/teams/Details.vue
packages/hoppscotch-common/src/helpers/import-export/export/environment.ts
packages/hoppscotch-common/src/helpers/import-export/import/postmanEnv.ts

Closes #4470 
This PR addresses the issue of Postman environment secrets being imported as plain text variables. The change introduces a new variable type to correctly identify and import secret variables as masked values, enhancing security.

fix: postman env variables are to be imported as secrets

---

packages/hoppscotch-backend/src/infra-token/infra-token.controller.ts
packages/hoppscotch-backend/src/infra-token/request-response.dto.ts
packages/hoppscotch-backend/src/user/user.service.ts

Closes HSB-495
This PR introduces an API to fetch a user's involvement in workspaces in `User management API` section
```
GET http://localhost:3170/v1/infra/users/{USER_UID}/workspaces
HEADER: infra-token
RESPONSE BODY
[
{
"id": "team_ID"
"name": "Team A",
"my_role": "OWNER",
"owner_count": 1,
"editor_count": 0,
"viewer_count": 0,
"member_count": 1
}
]
```
Nil

HSB-495 feat: user workspace stats api added

---

aio-multiport-setup.Caddyfile
aio-subpath-access.Caddyfile
prod.Dockerfile

This PR allows for users to specify alternate ports for AIO container configurations having sub-path access (single port) configurations. The container normally binds port 80 when using single port access, but port 80 is a privileged port and certain systems (esp. rootless systems like Podman or hardened systems like OpenShift) do not provide root level privileges to allow for binding to port 80.
- Added new optional environment variable `HOPP_AIO_ALTERNATE_PORT` which is used by Caddy to define which port is to be bound to. No behaviour change into Windows.
- If the variable is not specified, Caddy will use the default port 80.
@SanskritiHarmukh do remind me to update the docs to add a section for this.

feat: ability for aio in sub-path access configurations to specify alternate ports

---

packages/hoppscotch-cli/package.json
packages/hoppscotch-cli/src/__tests__/e2e/commands/test.spec.ts
packages/hoppscotch-cli/src/__tests__/e2e/fixtures/collections/digest-auth-coll.json
packages/hoppscotch-cli/src/__tests__/e2e/fixtures/collections/digest-auth-failure-coll.json
packages/hoppscotch-cli/src/__tests__/e2e/fixtures/collections/digest-auth-success-coll.json
packages/hoppscotch-cli/src/__tests__/e2e/fixtures/environments/digest-auth-envs.json
packages/hoppscotch-cli/src/utils/auth/digest.ts
packages/hoppscotch-cli/src/utils/pre-request.ts
packages/hoppscotch-cli/src/utils/request.ts
packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/package.json
packages/hoppscotch-common/src/components.d.ts
packages/hoppscotch-common/src/components/app/spotlight/Entry.vue
packages/hoppscotch-common/src/components/graphql/Authorization.vue
packages/hoppscotch-common/src/components/graphql/Headers.vue
packages/hoppscotch-common/src/components/http/Authorization.vue
packages/hoppscotch-common/src/components/http/authorization/AWSSign.vue
packages/hoppscotch-common/src/components/http/authorization/Digest.vue
packages/hoppscotch-common/src/composables/codemirror.ts
packages/hoppscotch-common/src/helpers/auth/digest.ts
packages/hoppscotch-common/src/helpers/import-export/import/insomnia.ts
packages/hoppscotch-common/src/helpers/utils/EffectiveURL.ts
packages/hoppscotch-common/src/pages/index.vue
packages/hoppscotch-common/src/services/inspection/inspectors/authorization.inspector.ts
packages/hoppscotch-data/src/graphql/index.ts
packages/hoppscotch-data/src/rest/index.ts
packages/hoppscotch-data/src/rest/v/8.ts
packages/hoppscotch-js-sandbox/src/shared-utils.ts
pnpm-lock.yaml

Closes HFE-570
This PR introduces Digest authentication as new request auth types.
The CLI behaviour has been updated so that any failures reported in the pre/post scripts and request execution will result in a non-zero exit code. Previously, this behaviour was exclusive to failed test assertions.
Digest auth works in two stages.
First, it requests for an initial response, where we get necessary information like realm, nonce, algorithm, etc., from the server in the header WWW-Authenticate.
Then, we have to parse information from that header. Finally, we have to generate an authorization header and request with that auth header in the Authorization header property.
`hopp test src/__tests__/e2e/fixtures/collections/digest-auth-coll.json -e …

feat: digest authentication added to the request auth types

---

packages/hoppscotch-common/src/components/settings/Agent.vue
packages/hoppscotch-selfhost-desktop/src/components/settings/NativeInterceptor.vue
packages/hoppscotch-selfhost-desktop/src/platform/interceptors/native/index.ts

Adds HTTP/HTTPS/SOCKS proxy support to the native interceptor in the desktop app. The native interceptor now allows users to:
- Enable/disable proxy usage
- Configure proxy URL with support for:
- HTTP/HTTPS/SOCKS protocols
- Basic Auth and NTLM authentication (via URL)
- Username/password in URL format
- Added proxy configuration UI in NativeInterceptor settings
- Implemented proxy persistence using local storage
- Extended RequestDef type to include proxy information
- Added proxy URL validation and handling in the native interceptor service
- Added IconLucideFileBadge icon to common package for consistency (this is a fix for web-app)
Closes HFE-639

feat(desktop): add CA cert and HTTP proxy support for native interceptor

---

packages/hoppscotch-cli/src/utils/request.ts
packages/hoppscotch-common/src/components/http/Authorization.vue
packages/hoppscotch-common/src/components/http/authorization/Digest.vue
packages/hoppscotch-common/src/services/inspection/inspectors/authorization.inspector.ts

This fix resolves an issue where a scrollbar appeared on digest authentication input fields. Additionally: 
- Fixes the issue where the interceptor warning regarding supported interceptors for Digest Auth was displayed on the Desktop app.
- Stale console logs are removed.
The issue was caused by an extra return character in the placeholder text. This fix removes the extra return character, eliminating the scrollbar.

fix: scrollbar appearing on digest auth input fields and other improvements

---

packages/hoppscotch-common/src/platform/index.ts
packages/hoppscotch-common/src/platform/interceptors.ts
packages/hoppscotch-common/src/platform/std/interceptors/agent/index.ts
packages/hoppscotch-common/src/services/inspection/inspectors/authorization.inspector.ts
packages/hoppscotch-common/src/services/interceptor.service.ts
packages/hoppscotch-selfhost-desktop/src/platform/interceptors/native/index.ts
packages/hoppscotch-selfhost-web/src/main.ts

This PR introduces a new field `supportsDigestAuth` at the interceptor service level replacing the previous `showInterceptorWarningForDigestAuth` platform level feature flag.
The purpose of introducing the above feature flag was to convey whether to show a warning regarding supported interceptors based on the platform. Since it is specific to interceptors, the above is removed in favour of a new member at the interceptor service layer.
N/A

chore: introduce `supportsDigestAuth` field at the interceptor service level

---

packages/codemirror-lang-graphql/package.json
packages/codemirror-lang-graphql/rollup.config.js
packages/codemirror-lang-graphql/tsconfig.json
pnpm-lock.yaml

This PR intends to fix the issues with building `codemirror-lang-graphql` in Node 22.
The issue is caused by Node 22 dropping the `assert` keyword for import assertions. We use `rollup-plugin-ts` as the plugin to parse typescript files, which uses `assert` keyword inside it.
- Move to `@rollup/plugin-typescript` and remove `rollup-plugin-ts` and `rollup-plugin-dts`.
- Update prepare script to also generate declaration file for `codemirror-lang-graphql` package.
Do make sure the GraphQL syntax highlighting still works and is stable across SH, Web and Desktop across debug and production modes.

fix: correct broken codemirror-lang-graphql in node 22

---

packages/hoppscotch-backend/src/admin/admin.service.ts
packages/hoppscotch-backend/src/team/team.service.ts

Closes HSB-497
This PR updated the user deletion. Previously if a user a team owner, that user can not be deleted.
Now, a user can be deleted if he is not solo team owner in any of teams.
3 ways a user can be deleted.
1. User can delete himself
2. User can delete by admin
3. User can delete via API

HSB-497 chore: user deletetion if not solo team owner

---

packages/hoppscotch-selfhost-desktop/src/main.ts

Previously, with the active interceptor being `Proxy` and Authorization set to `Digest Auth`, the warning regarding supported interceptors would appear in the Desktop App. This PR includes a fix for the same.
Related to HFE-642.
Specify `supportsDigestAuth` at the `selfhost-desktop` platform level `Proxy` interceptor config.

fix(selfhost-desktop): specify `Digest Auth` support for `Proxy` interceptor

---

packages/hoppscotch-agent/devenv.nix
packages/hoppscotch-agent/package.json
packages/hoppscotch-agent/src-tauri/Cargo.lock
packages/hoppscotch-agent/src-tauri/Cargo.toml
packages/hoppscotch-agent/src-tauri/src/controller.rs
packages/hoppscotch-agent/src-tauri/src/error.rs
packages/hoppscotch-agent/src-tauri/src/global.rs
packages/hoppscotch-agent/src-tauri/src/lib.rs
packages/hoppscotch-agent/src-tauri/src/state.rs
packages/hoppscotch-agent/src-tauri/src/tray.rs
packages/hoppscotch-agent/src-tauri/tauri.conf.json
packages/hoppscotch-agent/src-tauri/tauri.portable.conf.json

This PR fixes an issue where sane default values set in the ephemeral store were not being propagated to the persistent store if the store was uninitialized or encountered a loading error. Now, if the persistent store is absent or fails to load, default values will be established in the ephemeral store and subsequently saved to the persistent store, syncing two both storage layers.
Closes HFE-645

fix(agent): propagate default values to persistent store

---

packages/hoppscotch-cli/src/__tests__/e2e/commands/test.spec.ts

Test is for the CLI tool to verify how it behaves when attempting to export a report to an invalid path.
But, when running the test on **Windows**, it failed to pass the assertions in the test, even though the error output was as expected.
```javascript
const args = `test ${COLL_PATH} --reporter-junit /non-existent-path/report.xml`;
...
...
const out = getErrorCode(stderr);
expect(out).toBe<HoppErrorCode>("REPORT_EXPORT_FAILED");
});
```
- The test passed **on most platforms**, but not on **Windows**.
- The main issue occurred because we were checking for a specific error code in the `stderr`, but Windows returned something different in `stderr` - `ENOENT`
---
- On **Windows**, `Z:` would be an invalid drive letter (unless the drive is manually mapped, which it usually isn't).
- On …

fix(cli): use os-specific invalid paths for tests

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components/graphql/RequestOptions.vue
packages/hoppscotch-common/src/helpers/graphql/connection.ts
packages/hoppscotch-common/src/pages/graphql.vue

This pull request fixes the error handling for GraphQL connections. It adds a new error message for HTTP errors and updates the connection state to "ERROR" when an HTTP error occurs.

hotfix: graphql connection error handler

---

packages/hoppscotch-common/src/components/collections/ImportExport.vue
packages/hoppscotch-common/src/components/http/RawBody.vue
packages/hoppscotch-common/src/components/importExport/Base.vue
packages/hoppscotch-common/src/components/importExport/ImportExportSteps/AllCollectionImport.vue
packages/hoppscotch-common/src/components/importExport/types.ts
packages/hoppscotch-common/src/composables/ai-experiments.ts

Fixes HP-306 HFE-616.
**Changes**
Previously, we hide the features that required login. This PR shows the features, but when the user tries to trigger it, it will open the login dialogue.
This PR made this change to these features
* Auto rename requests
* Request body generation
* Import from another workspace

feat: show login dialogue for features behind login

---

packages/hoppscotch-common/src/components/collections/SaveRequest.vue
packages/hoppscotch-common/src/components/collections/graphql/AddRequest.vue
packages/hoppscotch-common/src/components/collections/graphql/EditRequest.vue
packages/hoppscotch-common/src/components/collections/graphql/index.vue
packages/hoppscotch-common/src/newstore/collections.ts
packages/hoppscotch-common/src/services/persistence/validation-schemas/index.ts

This PR aims to resolve the issues with the GraphQL workspace, where requests from the collection tree and the ones open under tabs get dissociated following certain actions.
> Dissociation due to request move and overwrite via spotlight `Save as new request` actions are beyond the scope.
Closes HFE-546 #4500.
- The `saveGraphqlRequestAs` function exposed from the store premises, invoking the underlying dispatcher now returns the insertion index for the request being added.
- Updates the places of consumption of the above to leverage the insertion index and resolve issues with the pre-existing implementation where the request index came up as `undefined` resulting in dissociation with the tab.
- Updates signature for the `OnAddRequest` method in the `CollectionGraphql` component removing …

fix: resolve GraphQL collection tree and tab dissociation issues

---

packages/hoppscotch-cli/src/types/request.ts
packages/hoppscotch-cli/src/utils/mutators.ts
packages/hoppscotch-cli/src/utils/pre-request.ts
packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components/http/BodyParameters.vue
packages/hoppscotch-common/src/helpers/functional/formData.ts
packages/hoppscotch-common/src/helpers/new-codegen/har.ts
packages/hoppscotch-common/src/helpers/utils/EffectiveURL.ts
packages/hoppscotch-data/src/rest/index.ts
packages/hoppscotch-data/src/rest/v/9.ts

This PR adds the ability to specify multiple content types for individual fields when using `multipart/formdata` content type.

feat: add individual content types for formadata

---

packages/hoppscotch-common/src/helpers/import-export/import/openapi.ts

Fixs HFE-659
**Before**
If validating an openapi failed, we abort the entire import and shows an error message.
**After**
If the validation failed, but there's a schema available with the error, we import that instead of entirely breaking the import

chore: continue openapi imports on error with a partial import

---

packages/hoppscotch-backend/src/plugins/GQLComplexityPlugin.ts

Closes HSB-500
This fix PR handles the breaking changes of [graphql-query-complexity](https://github.com/slicknode/graphql-query-complexity/releases/tag/v1.0.0).
For the introspection query, now returning 0 value as mentioned in the release note.
Nil

HSB-500 fix: returning introspection complexity to 0

---

packages/hoppscotch-cli/src/interfaces/request.ts
packages/hoppscotch-cli/src/utils/pre-request.ts
packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components/app/Inspection.vue
packages/hoppscotch-common/src/components/http/Body.vue
packages/hoppscotch-common/src/components/http/BodyBinary.vue
packages/hoppscotch-common/src/components/http/Headers.vue
packages/hoppscotch-common/src/components/http/Parameters.vue
packages/hoppscotch-common/src/components/http/Request.vue
packages/hoppscotch-common/src/helpers/utils/EffectiveURL.ts
packages/hoppscotch-common/src/helpers/utils/contenttypes.ts
packages/hoppscotch-common/src/pages/index.vue
packages/hoppscotch-common/src/services/inspection/index.ts
packages/hoppscotch-common/src/services/inspection/inspectors/environment.inspector.ts
packages/hoppscotch-common/src/services/inspection/inspectors/interceptors.inspector.ts
packages/hoppscotch-data/src/rest/content-types.ts
packages/hoppscotch-data/src/rest/v/9.ts

This PR adds support for sending binary data as body.
1. since the binary file is not exported, In `hoppscotch-cli`, added some changes to not error the request out, like how multipart/form-data is behaving right now.
2. hoppscotch/hoppscotch-extension#307 adds support for binary files in our browser extension.

feat: support for binary body

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/platform/std/interceptors/agent/index.ts
packages/hoppscotch-common/src/services/inspection/inspectors/interceptors.inspector.ts
packages/hoppscotch-common/src/services/interceptor.service.ts
packages/hoppscotch-selfhost-desktop/src/main.ts
packages/hoppscotch-selfhost-desktop/src/platform/interceptors/native/index.ts

Added inspector warnings for sending binary data via the Agent interceptor.

chore: show warning for interceptors not supporting binary data

---

packages/hoppscotch-common/src/platform/std/interceptors/proxy.ts

This PR adds binary data content type not supported warning for proxy interceptor.

chore: add inspection warning for proxy interceptor with binary data

---

packages/hoppscotch-cli/bin/hopp.js
packages/hoppscotch-cli/package.json
packages/hoppscotch-cli/tsup.config.ts
pnpm-lock.yaml

This PR aims to drop Node.js `v18` support for the CLI. Also, the user is warned if they are on an unsupported Node.js version.
Context: There were compatibility issues observed from `v0.12.0` of the CLI with Node.js v18 and with `v0.13.0` introduced the `File` API as part of the public data structured maintained under `hoppscotch-data` which gets inlined in the CLI bundle leading to errors while installing.
Ref: #4578, #4580.
- Relevant Node.js version checks are introduced before CLI execution and a warning is displayed when appropriate. The further CLI source bundle is dynamically imported after the above checks preventing errors due to unrecognized APIs in older Node.js versions.
- Adds `semver` as a dev dependency for seamless version checks that are inlined in the CLI bundle.
- Bump …

chore(cli): drop Node.js `v18` support

---

docker-compose.deploy.yml

Closes HSB-516
The `DATABASE_URL` in the `docker-compose.deploy.yaml` file is commented out. Instead, this environment variable will be read from the `.env` file, allowing us to use a separate database that will not reset on every deployment.
Nil

build: enable the use of external DB for internal test deployments

---

packages/hoppscotch-common/src/components/http/test/RunnerModal.vue

Closes HFE-669
This PR updates the collection runner modal UI
- Remove the padding and add a full width
- Move wiki button in the action slot of the tabs and add link w.r.t the tab state.

chore: update collection runner modal UI

---

packages/hoppscotch-common/src/components/http/Codegen.vue

Closes HFE-670 #4286  
Fixes inherited headers and auth of parent collections not being shown in codegen. 
Example before (header and auth not shown in generated code):
After (inherited header and auth shown in generated code):
- Added the array of inherited headers found in the inherited properties of the current document to the generateCode() method.
- The auth is fetched from the document and populated accordingly.

fix: inherited headers and auth included in code generation

---

packages/hoppscotch-backend/src/infra-config/infra-config.service.ts

Closes HSB-515
Currently, data is read from the `ConfigService` to avoid DB calls. But an issue arises, that function is called by different caller functions, where Config Service returns the same data instead of the latest.
Disable SMTP auth and save. Then try to toggle any other SSO and save. If the SSO changes persists then good to go.

HSB-515 fix: read data from DB for latest value

---

packages/hoppscotch-sh-admin/src/components.d.ts
packages/hoppscotch-sh-admin/src/helpers/backend/gql/queries/InvitedUsers.graphql
packages/hoppscotch-sh-admin/src/pages/users/invited.vue

- Closes HFE-694
This PR resolves an issue where the Pending Invites page under the Users section in the Admin Dashboard was only fetching 10 records. The root cause was identified in how the frontend called the relevant query, which defaults to returning a maximum of 10 records unless specified otherwise.
To address this, pagination support is added where the frontend query now explicitly requests the desired number of records and includes additional parameters to enable fetching more data when required. This ensures that the correct number of records is displayed.
- Updated the frontend query to specify the required record count.
- Added pagination support for Pending Invites.

fix(sh-admin): resolve record retrieval limits in pending invites section by implementing pagination

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components/http/BodyParameters.vue
packages/hoppscotch-common/src/components/http/URLEncodedParams.vue

**Before**
The empty element for no body was visible when bulk editing also.
**After**
This PR removes the empty element for no body when bulk editing

fix: do not show an empty body element when bulk editing

---

packages/hoppscotch-common/locales/en.json

**Changes**
* Adds a missing 18n string for pre request script generation error

chore: add missing `i18n` string entry

---

packages/hoppscotch-common/src/helpers/import-export/import/postman.ts

Closes HFE-718 #4649 
This PR addresses an issue where the authorization hierarchy is not correctly transferred when importing collections from Postman. The fix ensures that the proper authorization settings are maintained.

fix authorization hierarchy in postman import

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components/http/Response.vue
packages/hoppscotch-common/src/components/http/SaveResponseName.vue

Closes HFE-717 #4652 
This PR adds a flow where, when saving a response, the name inside the modal will be prefilled with the request name. Additionally, a warning indicator has been added to the modal input, which notifies the user if they attempt to save the response with a name that already exists for the request. The user can still proceed with saving, but the response will be overwritten with the latest changes.
https://github.com/user-attachments/assets/eb2d7776-5fbe-45c3-b7bb-edbedbd59124

chore: add warning prompt for same response name 

---

packages/hoppscotch-common/src/components/http/test/Response.vue
packages/hoppscotch-common/src/components/http/test/Runner.vue
packages/hoppscotch-common/src/components/lenses/ResponseBodyRenderer.vue
packages/hoppscotch-common/src/services/test-runner/test-runner.service.ts

Closes HFE-721
This pull request includes the following enhancements:
1. Request headers now display entries inherited from the parent collection level.
2. Added an empty state placeholder for failed request executions.
3. Introduced a loading state between request runs when a response is already present.

chore: colleciton runner improvements

---

package.json
pnpm-lock.yaml
prod.Dockerfile

This PR intends to clear out most of the security alerts (tested against Trivy and Docker Scout) regarding dependencies in the dependency trees having CVEs.
1. Update the containers to use Alpine 3.19.6 directly (alpine:3.19.6) instead of node:20-alpine3.19.
2. NPM is now sourced from the npmjs.com/install.sh (pinned to v10.9.2 as its the latest version for Node 20)
3. Pin certain npm packages on the chain to the fixed versions.
4. Have a custom build of Caddy generated in the docker build step itself to clear Caddy related warnings.
Please do test the AIO and the single containers

chore: security patches for dependency chain

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components/history/Personal.vue
packages/hoppscotch-common/src/components/history/index.vue
packages/hoppscotch-common/src/components/http/Sidebar.vue
packages/hoppscotch-common/src/components/workspace/Current.vue
packages/hoppscotch-common/src/platform/ui.ts
packages/hoppscotch-common/src/services/__tests__/history-ui-provider.service.spec.ts
packages/hoppscotch-common/src/services/history-ui-provider.service.ts

This PR introduces a new `history-ui-provider` service which can be used to inject custom history related components such as Activity Logs into the `hoppscotch-common` repo.

feat(common): introducing history ui provider service to hoppscotch-common

---

packages/hoppscotch-common/src/components/http/ResponseInterface.vue

Closes HFE-709
Address a schema generation issue by ensuring the response handling for test runner documents is correctly implemented.

Fix schema generation issue on test runner

---

package.json
prod.Dockerfile

This PR intends to pin pnpm v9 (v9.15.4) as the package manager for the Hoppscotch repo.
This is intended as a temporary measure until some issues in pnpm v10 which break the build pipeline are ironed out.
(Follow: https://github.com/orgs/pnpm/discussions/3938#discussioncomment-12050478)
1. Added `packageManager` field pinning the package management to `pnpm@9.15.4`
2. Pin the version of `pnpm` that build dockerfile (prod.Dockerfile) downloads to 9.15.4
If you get an error when running `pnpm install` saying it couldn't find the given version, it is because that given version isn't installed in your system, you can do that by typing:
```
pnpm add -g pnpm@9.15.4
```
NOTE: This will still retain your existing `pnpm` version, but switch to using `9.15.4` when you are interacting with the repo …

chore: pin pnpm v9 as the package manager

---

packages/hoppscotch-common/src/helpers/utils/EffectiveURL.ts

Closes #4690
https://github.com/hoppscotch/hoppscotch/blob/e967b3361d0fba3d2b6648af65509bbc1f49aa69/packages/hoppscotch-common/src/helpers/utils/EffectiveURL.ts#L431-L475 if `body.contentType` is `application/x-www-form-urlencoded`, the processed body is empty string, so I fixed it.

fix: ensure correct body for application/x-www-form-urlencoded in all code exports

---

packages/hoppscotch-common/package.json
packages/hoppscotch-common/src/helpers/new-codegen/index.ts
pnpm-lock.yaml

This PR adds Rust [reqwest](https://docs.rs/reqwest/latest/reqwest/) library code generation to Hoppscotch. All the heavy lifting is done by done library already. It had [support](https://github.com/Kong/httpsnippet/tree/master/src/targets/rust/reqwest) for Rust reqwest but it's not mentioned in the [docs](https://github.com/Kong/httpsnippet/wiki/Targets). So I just had to add a config :)
Also have bumped the httpsnippet version to v3.0.7

feat: support rust reqwest code generation

---

packages/hoppscotch-common/locales/en.json

A simple English spelling correction that resolves the mistake seen below:

Correct the english response body lost rerun msg

---

packages/hoppscotch-common/src/components/collections/index.vue
packages/hoppscotch-common/src/helpers/backend/helpers.ts

I noticed that indentation is used in all methods of exporting data in JSON format. However, there is no such thing when exporting command collections. Fixing it

chore: format collections prior to export

---

healthcheck.sh

- Added a more flexible exit strategy in the `curlCheck` function.
- Changed the script to return status codes instead of directly exiting in `curlCheck`. Now, the main script decides whether to exit based on those returned statuses.
- Updated URL checks to gracefully handle failure without prematurely stopping the entire script.
- The `curlCheck` function now uses `return 1` instead of `exit 1`, allowing better control over script flow.
- This change helps in managing multiple URL checks, and the script will only exit if the individual check fails (not all at once).
Improved code:
curlCheck() {
if ! curl -s --head "$1" | head -n 1 | grep -q "HTTP/1.[01] [23].."; then
echo "URL request failed!"
return 1
else
echo "URL request succeeded!"
return 0
fi
}
if [ "$ENABLE_SUBPATH_BASED_ACCESS" = …

chore: improve health check script

---

packages/hoppscotch-common/src/helpers/import-export/import/postman.ts

Remove unsafe cast and convert value to string if needed, handling numerical values.
This is a small fix for postman import process, according to [Postman collection v2.1.0](https://schema.getpostman.com/json/collection/v2.1.0/collection.json) the form data values should be string but when I tried to import a collection into Hoppscotch it failed due this format issue. 
Here is a screenshot of the error, the import is pending (didn't notify user of import error)

fix(import/postman): handle non-string form values

---

SECURITY.md

Use GitHub markdown alert formatting for note.

docs: use GitHub markdown alert formatting for note

---

packages/hoppscotch-common/src/helpers/import-export/import/postman.ts
packages/hoppscotch-selfhost-desktop/src/platform/collections/collections.platform.ts
packages/hoppscotch-selfhost-web/src/platform/collections/collections.platform.ts

Closes HFE-744
Follow up of #4686.
This pull request addresses an issue where properties are not being inherited correctly when importing collections from Postman. 
Additionally, the following updates are brought to collection-level platform definitions under the `hoppscotch-selfhost-web` & `hoppscotch-selfhost-desktop` packages:
- Ensure `authActive: true` is specified in combination with `authType: "inherit"` while computing authorization data.
- Resolve type errors.

fix: properties not inherited while importing from postman

---

packages/hoppscotch-common/src/components/app/PaneLayout.vue
packages/hoppscotch-sh-admin/src/components/teams/Add.vue

Found 2 source typos via `codespell -q 3 -D ../dictionary.txt -S "./packages/hoppscotch-common/locales,./pnpm-lock.yaml" -L afterall,atleast,childrens,doesnt,inout,parms,requestd,te`
2 typos corrected

chore: fix typos in `.vue` component files

---

packages/hoppscotch-common/src/components/http/BodyParameters.vue
packages/hoppscotch-common/src/components/http/KeyValue.vue
packages/hoppscotch-common/src/components/http/RequestVariables.vue
packages/hoppscotch-common/src/components/http/URLEncodedParams.vue

Closes #4750
This pull request addresses the visual representation of inactive entries within the `SmartEnvInput` components for the following cases:
- Query params.
- Request body with content types set to `multipart/form-data` or `application/x-www-form-urlencoded`. 
- Headers
- Request variables.

feat: visual enhancement for inactive fields

---

packages/hoppscotch-common/src/helpers/curl/__tests__/curlparser.spec.js
packages/hoppscotch-common/src/helpers/curl/sub_helpers/headers.ts

Closes #4707 
This PR addresses the issue where cURL headers fail to import when the key-value pairs are separated by a single `":"` (without a trailing space). The fix replaces the first occurrence of `":"` (assumed to be the key-value separator) with `": "` (colon + space), ensuring proper parsing while maintaining support for values that contain colons. This does not introduce any unwanted side effects, as the parser already includes a trim step to handle trailing spaces.
- Updated the header parser to replace the first occurrence of `":"` with `": "` to ensure correct splitting.
- Added a test case to validate the fix.
I tried other approaches such as using a regex or single `":"` as the separator, but these required additional steps to deal with some other edge cases which turned out …

fix: cURL header imports without trailing space

---

packages/hoppscotch-selfhost-desktop/src/components/modals/NativeCACertificates.vue
packages/hoppscotch-selfhost-desktop/src/components/modals/NativeClientCertsAdd.vue
packages/hoppscotch-selfhost-desktop/src/main.ts
packages/hoppscotch-selfhost-desktop/src/platform/collections/collections.sync.ts
packages/hoppscotch-selfhost-desktop/src/platform/collections/gqlCollections.sync.ts
packages/hoppscotch-selfhost-web/src/platform/collections/collections.sync.ts
packages/hoppscotch-selfhost-web/src/platform/collections/gqlCollections.sync.ts

User and non-user facing typo fixes
Found via `codespell -q 3 -S "./packages/hoppscotch-common/locales,./pnpm-lock.yaml" -L afterall,atleast,childrens,doesnt,inout,parms,requestd,te`

fix: typos in packages/hoppscotch-selfhost-desktop

---

packages/hoppscotch-common/src/components/http/BodyParameters.vue
packages/hoppscotch-data/src/rest/v/9.ts

Closes HFE-761 #2453 #4591
The validation schema has been updated to include error handling for the `Blob` array. The previous implementation:
```javascript
value: z.array(z.instanceof(Blob).nullable())
```
has been replaced with:
```javascript
value: z.array(z.instanceof(Blob).nullable()).catch([])
```
This change ensures that if the validation fails, the result will default to an empty array instead of throwing an error.
I would like to highlight that I don't believe a new versioning is necessary for this change, as we have only added a `.catch([])` to handle validation errors. This modification is minor and does not significantly alter the functionality of the schema.

fix: request validation issue on load persistence tab

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components/settings/Proxy.vue
packages/hoppscotch-common/src/helpers/proxyUrl.ts
packages/hoppscotch-common/src/helpers/strategies/AxiosStrategy.ts
packages/hoppscotch-common/src/newstore/settings.ts
packages/hoppscotch-common/src/platform/infra.ts
packages/hoppscotch-common/src/platform/std/interceptors/proxy.ts

This PR updates the hard coded proxy URL and fetch it from the server if it exist else fall back to the default one.
Dependent on [112](https://github.com/hoppscotch/selfhost-enterprise/pull/112) and [111](https://github.com/hoppscotch/selfhost-enterprise/pull/111)

feat: updated the hard coded proxy url with the server fetched 

---

packages/hoppscotch-common/src/helpers/import-export/import/openapi.ts
packages/hoppscotch-common/src/helpers/import-export/import/workers/openapi-import-worker.ts
packages/hoppscotch-selfhost-web/vite.config.ts

This PR moves the opeanpi validation + dereferencing that happens while importing an openapi document into a worker so that the UI is not froze when importing things. Also brings along changes from #4775

chore: move openapi validation and dereferencing to a worker

---

packages/hoppscotch-desktop/src-tauri/src/lib.rs
packages/hoppscotch-desktop/src-tauri/src/updater.rs
packages/hoppscotch-desktop/src-tauri/tauri.conf.json
packages/hoppscotch-desktop/src/App.vue
packages/hoppscotch-desktop/src/components.d.ts
packages/hoppscotch-desktop/src/views/Home.vue

PR changes updater endpoint from Cloud to SelfHosted, has a few minor UX improvements around stalling updates not notifying (typically happens when network is down or endpoint is inaccessible)

fix(desktop): change updater endpoint and some UX improvements

---

packages/hoppscotch-desktop/plugin-workspace/tauri-plugin-appload/src/cache/mod.rs
packages/hoppscotch-desktop/src-tauri/Cargo.lock
packages/hoppscotch-desktop/src-tauri/tauri.conf.json
packages/hoppscotch-desktop/vite.config.ts
pnpm-lock.yaml

This PR changes how dev server is setup to fix local DNS resolution issue on MacOS after the recent update, increases cache size for LRU hot-cache since the expected bundle size has grown since the latest merge which triggers cache eviction that degrades performance, eviction was purely meant as a fail safe so it being triggered often is not ideal. Also fixes HoppSpinner being missing on launch.

fix(desktop): cache size for larger bundles, dev server, lints

---

packages/hoppscotch-common/src/services/persistence/__tests__/index.spec.ts
packages/hoppscotch-common/src/services/persistence/index.ts
packages/hoppscotch-common/src/services/tab/graphql.ts
packages/hoppscotch-common/src/services/tab/rest.ts

This PR fixes some of the inconsistencies in calls to `PersistenceService` around double serialization/deserialization.
Legacy `PersistenceService` calls are serialized at the call site, for example:
```typescript
persistenceService.setLocalConfig("login_state", JSON.stringify(user))
```
Although `kernel`'s `Store.set` automatically serializes value for storage (and `Store.get` deserializes automatically as well):
```typescript
async set(namespace: string, key: string, value: StoredData): Promise<void> {
const validated = StoredDataSchema.parse(value);
// <platform specific serialization>
this.notifyListeners(namespace, key, validated.data);
}
```
The legacy approach still works due to how platform-dependent serialization/deserialization handles `string` values specifically. When we call …

fix(common): `PersistenceService` call site compat

---

packages/hoppscotch-agent/package.json
packages/hoppscotch-agent/src-tauri/tauri.conf.json
packages/hoppscotch-agent/src-tauri/tauri.portable.conf.json
packages/hoppscotch-desktop/package.json
packages/hoppscotch-selfhost-desktop/package.json
packages/hoppscotch-selfhost-desktop/src-tauri/Cargo.lock
packages/hoppscotch-selfhost-desktop/src-tauri/Cargo.toml
packages/hoppscotch-selfhost-desktop/src-tauri/tauri.conf.json
pnpm-lock.yaml

This PR fixes agent version bump regressions.

fix: version bump regression for sh-desktop and agent

---

packages/hoppscotch-common/src/components/embeds/index.vue

This PR fixes the embeds redirect URL which will redirect the embed to hoppscotch app

fix: update embed redirect URL

---

packages/hoppscotch-common/src/components/settings/Extension.vue
packages/hoppscotch-common/src/platform/std/kernel-interceptors/extension/index.ts
packages/hoppscotch-common/src/platform/std/kernel-interceptors/extension/store.ts

This PR fixes regression in `extension` interceptor service and associated components.
Closes #4804.

fix(common): extension port to relay regression

---

packages/hoppscotch-backend/src/team-request/team-request.service.ts

Closes #4567 
This PR fixes the bug while re-ordering request inside a collection does not persist when refreshing.
Added `orderBy` to `getRequestsInCollection` function to fetch the request in to sort by orderIndex

fix: order request while fetching from db

---

packages/hoppscotch-common/src/components/app/WhatsNewDialog.vue
packages/hoppscotch-common/src/components/collections/ImportExport.vue
packages/hoppscotch-common/src/components/collections/graphql/ImportExport.vue
packages/hoppscotch-common/src/components/environments/ImportExport.vue
packages/hoppscotch-common/src/platform/kernel-io.ts
packages/hoppscotch-common/src/platform/std/kernel-interceptors/extension/index.ts
packages/hoppscotch-common/src/platform/std/kernel-interceptors/extension/store.ts
packages/hoppscotch-common/src/platform/std/kernel-io.ts
packages/hoppscotch-common/src/services/spotlight/searchers/general.searcher.ts

This PR fixes some of the remaining calls to `openExternalLink` that's now routed through `kernel-io`.

fix: kernel-io calls via `openExternalLink`

---

packages/hoppscotch-agent/src-tauri/src/updater.rs

This PR fixes agent updater dialog ambiguity as expressed in #4816 
This will also address ambiguity on some Linux setups where dialog might not appear next to Agent's tray icon.
Now the update dialog will say "Hoppscotch Agent Update Available"
Closes #4816

fix(agent): mention name in updater dialog

---

packages/hoppscotch-common/src/components/history/Personal.vue

Closes #4830 
This PR fixes the issue where the tab crashes when clicking on history request because the tab type was not defined for history request.

fix(common): exception while clicking request history entries

---

packages/hoppscotch-common/src/helpers/graphql/document.ts
packages/hoppscotch-common/src/helpers/graphql/query.ts

This pull request addresses an issue by modifying the HoppGQLDocument type to make the cursorPosition property optional.

fix(common): make `cursorPosition` field optional in `HoppGQLDocument` type

---

packages/hoppscotch-common/src/pages/join-team.vue

Closes #4824 
This PR aims to resolve issues encountered when a user attempts to join a shared workspace and is greeted with an error screen. This is observed particularly in the cloud offering. This happens when the GQL query executed while a user visits the invite link fails with the message `auth/fail` since the login state is not confirmed yet. The proposed changes ensure the relevant login state is confirmed before the network call, maintaining backwards compatibility with SH.
N/A

fix(common): resolve issues around shared workspace invite validation

---

docker-compose.yml
prod.Dockerfile

This PR makes `webapp-server` (the server that the Desktop App uses to gather Hoppscotch App contents) part of the frontend container. Both `Caddy` and `webapp-server` now uses the same `/dist` directory (previously copied over in `webapp-server` container).

feat(infra): make webapp server part of fe container

---

packages/hoppscotch-desktop/plugin-workspace/tauri-plugin-appload/src/api/client.rs
packages/hoppscotch-desktop/src-tauri/Cargo.lock
pnpm-lock.yaml

This PR increases bundle download timeout by creating a separate client just for handling downloads.
Closes #4842
You can test this by using one of the deployed instances and throttling network speeds, current timeout aims for ~15MB over 5mins.

fix(desktop): increase bundle download timeout

---

packages/hoppscotch-common/src/platform/auth.ts
packages/hoppscotch-common/src/platform/io.ts
packages/hoppscotch-common/src/platform/kernel-io.ts
packages/hoppscotch-common/src/platform/std/kernel-interceptors/proxy/index.ts
packages/hoppscotch-common/src/platform/ui.ts

Documentation and non-user facing typo fixes
Found via `codespell -q 3 -S "./packages/hoppscotch-common/locales,./pnpm-lock.yaml" -L afterall,atleast,childrens,doesnt,inout,parms,requestd,te`
n/a

fix: typos in packages/hoppscotch-common/src/platform

---

packages/hoppscotch-agent/src-tauri/Cargo.lock
packages/hoppscotch-agent/src-tauri/tauri.conf.json
packages/hoppscotch-agent/vite.config.ts
packages/hoppscotch-common/src/components/settings/ExtensionSubtitle.vue
packages/hoppscotch-common/src/helpers/kernel/common/content.ts
packages/hoppscotch-common/src/helpers/network.ts
packages/hoppscotch-common/src/platform/std/kernel-interceptors/agent/index.ts
packages/hoppscotch-common/src/platform/std/kernel-interceptors/agent/store.ts
packages/hoppscotch-common/src/platform/std/kernel-interceptors/extension/index.ts
packages/hoppscotch-common/src/platform/std/kernel-interceptors/extension/store.ts
packages/hoppscotch-common/src/platform/std/kernel-interceptors/native/index.ts
packages/hoppscotch-common/src/platform/std/kernel-interceptors/proxy/index.ts
packages/hoppscotch-desktop/plugin-workspace/relay/src/content.rs
packages/hoppscotch-desktop/plugin-workspace/relay/src/interop.rs
packages/hoppscotch-desktop/plugin-workspace/tauri-plugin-relay/Cargo.lock
packages/hoppscotch-desktop/src-tauri/Cargo.lock
packages/hoppscotch-kernel/src/index.ts
packages/hoppscotch-kernel/src/relay/impl/desktop/v/1.ts
packages/hoppscotch-kernel/src/relay/impl/web/v/1.ts
packages/hoppscotch-kernel/src/relay/v/1.ts
pnpm-lock.yaml

This PR fixes some of the inconsistencies in extension detection + polling and form and multipart handling around ser/de.
| Before                                                                                    | After                                                                                     |
| -------------                                                                             | -------------                                                                             |
| ![image](https://github.com/user-attachments/assets/2163ec3e-dc6c-48c5-b377-ef0f085a43f7) | ![image](https://github.com/user-attachments/assets/c7c6a59d-1c12-4ea9-97bf-4c9ad0870641) |
| ![image](https://github.com/user-attachments/assets/b7f52c25-8732-452b-8a32-b8665e10f5d8) | …

feat(kernel): isolate type ser/de to platform

---

packages/hoppscotch-agent/src-tauri/src/webview/mod.rs
packages/hoppscotch-backend/src/team-collection/team-collection.service.spec.ts
packages/hoppscotch-backend/src/user-collection/user-collection.service.spec.ts
packages/hoppscotch-backend/src/user/user.service.spec.ts
packages/hoppscotch-cli/src/__tests__/e2e/fixtures/collections/multipart-form-data-coll.json
packages/hoppscotch-cli/src/interfaces/response.ts
packages/hoppscotch-cli/src/utils/request.ts
packages/hoppscotch-common/assets/scss/styles.scss
packages/hoppscotch-common/src/components/collections/index.vue
packages/hoppscotch-common/src/components/http/BodyBinary.vue
packages/hoppscotch-common/src/components/http/authorization/NTLM.vue
packages/hoppscotch-common/src/composables/stream.ts
packages/hoppscotch-common/src/helpers/collection/collection.ts
packages/hoppscotch-common/src/helpers/functional/record.ts
packages/hoppscotch-common/src/helpers/import-export/import/postman.ts
packages/hoppscotch-common/src/helpers/types/HoppPicked.ts
packages/hoppscotch-common/src/services/__tests__/interceptor.service.spec.ts
packages/hoppscotch-common/src/services/debug.service.ts
packages/hoppscotch-common/src/services/inspection/inspectors/__tests__/environment.inspector.spec.ts
packages/hoppscotch-common/src/services/spotlight/__tests__/index.spec.ts
packages/hoppscotch-common/src/services/spotlight/searchers/settings.searcher.ts
packages/hoppscotch-data/src/predefinedVariables.ts
packages/hoppscotch-desktop/src/views/Home.vue
packages/hoppscotch-sh-admin/locales/en.json
packages/hoppscotch-sh-admin/src/composables/stream.ts
packages/hoppscotch-sh-admin/src/composables/useConfigHandler.ts

Documentation and non-user facing typo fixes
Found via `codespell -q 3 -S "./packages/hoppscotch-common/locales,./pnpm-lock.yaml" -L afterall,atleast,childrens,doesnt,inout,parms,requestd,te`
I made the PR against the 'patch' branch.

fix: resolve typos across packages

---

packages/hoppscotch-common/src/composables/codemirror.ts

Closes #4574 
This PR fixes the issue in windows where when pressing "Ctrl-Enter" sends the request also added a new line when the focus was on a codemirror instance

fix: update the newline key in codemirror

---

packages/hoppscotch-common/src/composables/codemirror.ts

Closes HFE-770
This pull request addresses a bug where the selection of text in the JSON input field does not follow the mouse cursor properly when scrolling. Users may find it difficult to find context menu because of this.
In the file `packages/hoppscotch-common/src/composables/codemirror.ts`, we made an update to the `handleTextSelection` method. The change involves using the 'to' position (end position) instead of the 'from' position to correctly position the context menu at the location where the drag operation ended. This adjustment ensures that the context menu appears at the appropriate spot.

fix(common): correct coordinates calculation for selection end position

---

packages/hoppscotch-desktop/README.md

This PR updates Hoppscotch Desktop App's `README` to include Windows specific caveats.

docs(desktop): include windows specific caveats

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components/graphql/Argument.vue
packages/hoppscotch-common/src/components/graphql/Arguments.vue
packages/hoppscotch-common/src/components/graphql/DocExplorer.vue
packages/hoppscotch-common/src/components/graphql/ExplorerSection.vue
packages/hoppscotch-common/src/components/graphql/Field.vue
packages/hoppscotch-common/src/components/graphql/FieldDocumentation.vue
packages/hoppscotch-common/src/components/graphql/FieldLink.vue
packages/hoppscotch-common/src/components/graphql/Fields.vue
packages/hoppscotch-common/src/components/graphql/Query.vue
packages/hoppscotch-common/src/components/graphql/SchemaDocumentation.vue
packages/hoppscotch-common/src/components/graphql/TypeDocumentation.vue
packages/hoppscotch-common/src/components/graphql/TypeLink.vue
packages/hoppscotch-common/src/helpers/graphql/explorer.ts
packages/hoppscotch-common/src/helpers/graphql/query.ts

Closes HFE-739
This pull request addresses several issues related to the GraphQL query builder. The following fixes have been implemented:
- Resolved an issue where the GraphQL subscription document could be generated in an invalid state under certain conditions.
- Fixed the problem of not being able to populate primitive fields in the default GraphQL example available at https://echo.hoppscotch.io/graphql.
- Added functionality to indicate the active status for GraphQL document arguments, similar to how it is done for fields.
- Improved UI and fixes contrast issue on light mode

feat: improve graphql query builder

---

packages/hoppscotch-selfhost-web/src/platform/collections/desktop/gqlCollections.sync.ts
packages/hoppscotch-selfhost-web/src/platform/collections/desktop/sync.ts
packages/hoppscotch-selfhost-web/src/platform/collections/web/gqlCollections.sync.ts
packages/hoppscotch-selfhost-web/src/platform/collections/web/sync.ts

Closes #4171, HFE-361.
The proposed changes ensure that (REST/GQL) child collections/requests are associated with the respective parent level collections instead of the root collection during imports to the personal workspace.
Updating the parent collection ID when creating a new parent during each recursive call.

fix: preserve hierarchy during personal collection imports

---

packages/hoppscotch-common/src/components/lenses/renderers/HTMLLensRenderer.vue
packages/hoppscotch-common/src/composables/lens-actions.ts

Closes #4862, HFE-776.
This PR fixes the issue where the html preview was not working as expected.
The defaultPreview has been changed to a computedAsync variable since the persistenceService.getLocalConfig is an async function. 
There was already a bug where the iframe sometimes didn't load due to sandbox error 
This can be fixed by allowing `allow-scripts allow-same-origin` in the sandbox attribute of the iframe but have some security issues that follows. This can be tackled separately if necessery

fix: resolve issues around rendering HTML response previews

---

packages/hoppscotch-common/src/platform/std/kernel-interceptors/proxy/index.ts

This PR fixes non-json response types not being correctly decomposed to the base `Uint8Array` type for kernel processors.
Closes #4895
Closes HFE-785
Try any non-json response requests API, the request will fail.
| Before  | After |
| ------------- | ------------- |
| ![image](https://github.com/user-attachments/assets/6db01f10-2295-4e36-b1cf-d57ee1cabc6d) | ![image](https://github.com/user-attachments/assets/b0142921-70f5-4abf-9bc5-5f9d4d12939b)  |
> [!NOTE]
> You may see incorrect interceptor embed after request failure on live version, it is fixed with https://github.com/hoppscotch/hoppscotch/pull/4887

fix(common): pre-process proxy response to base type

---

packages/hoppscotch-agent/src-tauri/Cargo.lock
packages/hoppscotch-desktop/plugin-workspace/relay/Cargo.lock
packages/hoppscotch-desktop/plugin-workspace/relay/Cargo.toml
packages/hoppscotch-desktop/plugin-workspace/relay/src/content.rs
packages/hoppscotch-desktop/plugin-workspace/relay/src/interop.rs
packages/hoppscotch-desktop/plugin-workspace/tauri-plugin-relay/Cargo.lock
packages/hoppscotch-desktop/src-tauri/Cargo.lock
pnpm-lock.yaml

This PR fixes form data ordering by switching to `IndexMap` instead of `HashMap`
You can try this request
```
curl --request POST \
--url https://echo.qubit.codes/ \
--header 'content-type: multipart/form-data' \
--form 1=2 \
--form 3=4 \
--form 5=6 \
--form 7=8
```
previously you will see
```
"post_params": {
"1": "2",
"3": "4",
"5": "6",
"7": "8"
},
"all_params": [
"8",
"2",
"4",
"6"
],
```
See `all_params` has different ordering in each request.
After this fix the response should look like 
```
"post_params": {
"1": "2",
"3": "4",
"5": "6",
"7": "8"
},
"all_params": [
"2",
"4",
"6",
"8"
],
```

fix(desktop): preserve formdata ordering

---

packages/hoppscotch-common/src/components/importExport/ImportExportSteps/UrlImport.vue
packages/hoppscotch-common/src/helpers/import-export/import/import-sources/GistSource.ts

Closes HFE-778
This PR addresses and resolves issues encountered when importing collections via GitHub Gist URLs and OpenAPI specifications through URLs.

fix: resolve issues around import via URL

---

packages/hoppscotch-agent/src-tauri/Cargo.lock
packages/hoppscotch-common/src/services/oauth/flows/authCode.ts
packages/hoppscotch-common/src/services/oauth/flows/clientCredentials.ts
packages/hoppscotch-common/src/services/oauth/flows/password.ts
packages/hoppscotch-desktop/plugin-workspace/relay/src/content.rs
packages/hoppscotch-desktop/plugin-workspace/relay/src/header.rs
packages/hoppscotch-desktop/plugin-workspace/tauri-plugin-relay/Cargo.lock
packages/hoppscotch-desktop/src-tauri/Cargo.lock
packages/hoppscotch-selfhost-web/package.json
pnpm-lock.yaml

This PR fixes header duplication and non-normalization issues that prevent certain flows including OAuth on stricter servers.
| ------ | ------|
| ![image](https://github.com/user-attachments/assets/6113f576-b0c2-490d-82e7-f54134907482) | ![image](https://github.com/user-attachments/assets/e76aa314-ec47-412e-906a-d0dc58984234) | 
Closes HFE-786
Closes #4905 
Issue affects both `Native` interceptor on desktop and `Agent` interceptor on web, PR aimed to fix both.

fix(common): normalize headers before final relay

---

aio_run.mjs
packages/hoppscotch-selfhost-web/prod_run.mjs
packages/hoppscotch-sh-admin/prod_run.mjs

This change sorts environment variables alphabetically before they're processed with import-meta-env that injects them into the index.html. This makes sure consistent hashes across pod restarts when there aren't any functional changes made to the `.env` file.
The issue was affecting desktop app reconnections after k8s pod restarts. The cause was non-deterministic env var ordering (a side-effect of `Map`) during the import-meta-env injection process. Even when the env vars themselves didn't change, their order in the injected JSON could change, ultimately resulting in different file hashes.
This fix ensures that regardless of the order in which env vars are provided by the runtime, they will be sorted alphabetically before being written to the build.env file.

fix(infra): deterministic env var ordering

---

packages/hoppscotch-agent/src-tauri/Cargo.lock
packages/hoppscotch-desktop/plugin-workspace/relay/src/content.rs
packages/hoppscotch-desktop/plugin-workspace/relay/src/header.rs
packages/hoppscotch-desktop/plugin-workspace/tauri-plugin-relay/Cargo.lock
packages/hoppscotch-desktop/src-tauri/Cargo.lock
pnpm-lock.yaml

The prior implementation caused duplicate `Content-Type` headers when users override headers in the UI or use OAuth2 authentication with the agent. Web servers receive multiple `Content-Type` headers which causes undefined behavior and 400 errors for backends that don't accept duplicate headers. This _duplicate headers_ part has been fixed in https://github.com/hoppscotch/hoppscotch/pull/4911, this is a followup that fixes inconsistent behavior when overriding the `Content-Type` header with custom values (e.g., `application/json;v=2`).
Closes #4905
Closes HFE-790
This patch removes the automatic content-type header insertion, allowing user-defined headers to take precedence without duplication. The is a temporary workaround until we implement a HTTP/2-compliant solution with proper …

fix(relay): avoid override with header passthrough

---

packages/hoppscotch-selfhost-web/src/main.ts

This PR enables cookie support for the SH Desktop App.
| ---       | ---    |
| ![Before 1](https://github.com/user-attachments/assets/a02ee9de-e8bd-40fc-afa9-627a1e2577ed) | ![After 1](https://github.com/user-attachments/assets/bafd9d19-47de-43c0-b27a-8535730c7349) | 
| Notice the missing `Cookie` button at the footer | Button is now present |
Closes HFE-796
Closes  #4918
This feature is already present and enabled on the Cloud Desktop App, see the corresponding file in the relevant repo.
For testing this out quickly without setting up AIO container, you can:
```
❯ cd packages/hoppscotch-selfhost-web
❯ pnpm generate && cd webapp-server && RUST_LOG=debug cargo run
```
This will start a temporary bundle server. 
After it's up and running, use `localhost:3200` as the …

fix(desktop): enable cookie support for sh-desktop

---

packages/hoppscotch-common/src/services/oauth/flows/password.ts

Fixes an issue where the `scope` parameter is not sent to the IDP token endpoint when using the `password` oauth2 flow.
The code today sends the scopes as `scopes` and not `scope`, which is not according to the OAuth2 specification. The scopes selected in the UI will not be respected. After this fix, the scopes will be respected as expected.
1. Select the `Authorization` tab of a request.
2. Select `OAuth2` as the authorization type.
3. Select `Password` as the grant type.
4. Enter all endpoints and details for a password client.
5. Select a subset of scopes in the scope parameter.
6. Notice how the subset of scopes is not respected.
Request received in test application (formatted as JSON):
```json
{"grant_type":"password","username":"redacted","password":"redacted","client_id":"test","cli …
```

fix(common): oauth2 password flow not respecting scopes

---

packages/hoppscotch-common/src/helpers/utils/EffectiveURL.ts

Closes HFE-769 #3956
This update simplifies the logic for handling authentication headers. It clearly specifies the conditions under which we should skip adding authorization headers: specifically, when an Authorization header is already defined by the user. This exception does not apply when we are using API-key authentication with a different header name.

fix(common): improve authorization header handling

---

package.json
packages/hoppscotch-agent/package.json
packages/hoppscotch-cli/package.json
packages/hoppscotch-common/package.json
packages/hoppscotch-kernel/package.json
packages/hoppscotch-selfhost-desktop/package.json
packages/hoppscotch-selfhost-web/package.json
packages/hoppscotch-sh-admin/package.json
pnpm-lock.yaml
prod.Dockerfile

This PR intends to update some of the dependencies in the Hoppscotch dependency chain that have published CVEs.
1. Bump and unify axios versions to 1.8.2 across all workspace packages.
2. Bump @babel/runtime to 7.26.10
3. Bump Caddy's build dependency (`golang.org/x/net`)

chore: bump vulnerable dependencies

---

packages/hoppscotch-common/src/helpers/lenses/jsonLens.ts
packages/hoppscotch-common/src/helpers/lenses/lenses.ts

Closes HFE-791 #4239
This pull request introduces improvements to the JSON lens functionality in the `hoppscotch-common` package. The key changes include adding a utility function to validate JSON strings, updating the JSON lens to handle `text/plain` content types, and modifying the lens selection logic to prioritize the JSON lens for valid JSON content.
* [`packages/hoppscotch-common/src/helpers/lenses/jsonLens.ts`](diffhunk://#diff-cbd2b0f64781739021c5b10c958805700cf8a1c12211b3c7d840e2f6570297ffL2-R29): Added a new function `isValidJSONResponse` to check if a string can be parsed as valid JSON.
* [`packages/hoppscotch-common/src/helpers/lenses/lenses.ts`](diffhunk://#diff-79bfbf40575328139052e5ff8d6c432b3345dec7dcf6f01e0f0f5db5abecaa1fL2-R2): Imported the new `isValidJSONResponse` …

feat: format JSON responses having `text/plain` content type

---

packages/hoppscotch-common/src/services/oauth/flows/clientCredentials.ts

fix(common): oauth2 basic header encoding

---

packages/hoppscotch-selfhost-web/src/platform/auth/desktop/index.ts

These changes add explicit `Content-Type` headers to direct (via `native` interceptor) authentication requests after changes made in [PR #4931](https://github.com/hoppscotch/hoppscotch/pull/4931) that modified how `Content-Type` headers are handled in the `relay` plugin.
Closes HFE-799
Closes #4949
In [issue #4905](https://github.com/hoppscotch/hoppscotch/issues/4905), that was about Hoppscotch Agent and Native interceptor inconsistently handling `Content-Type` headers. The issue had two main manifestations, duplicate headers - when overriding the `Content-Type` header in the UI or using OAuth2 authentication, the agent would send multiple `Content-Type` headers to the web server. This caused undefined behavior and often 400 errors for backends that don't accept duplicate headers. And …

fix(web): add explicit headers following prior normalization

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/components/app/Header.vue
packages/hoppscotch-common/src/platform/organization.ts

Closes HFE-771
This PR add's a dashboard link to the profile dropdown, as well as updating the organization platform definition to include admin status.

chore: add organization dashboard link to profile dropdown

---

packages/hoppscotch-common/src/helpers/import-export/import/openapi.ts
packages/hoppscotch-common/src/helpers/utils/isNumber.ts
packages/hoppscotch-common/src/helpers/utils/number.ts

Closes #4956 
- This pull request fixes the bug where importing an OpenAPI request the examples show wrong status codes.
- Also added a new file for the `isNumber` function .

fix(common): OpenAPI response example status code bug

---

packages/hoppscotch-backend/src/auth/auth.service.spec.ts

Closes #4964 
This PR fixes a test case for the `verifyMagicLinkTokens` function.
The test case was related to a timestamp issue, which is difficult to reproduce unless the test runs on a very fast machine.
Most of the time when we run the tests, `expiresOn` becomes slightly outdated by the time and the test function passes.
Whenever you use a fast machine, `expiresOn` may hold the current time, which can trigger an error in subsequent functions.
Nil
Just run the followed cmds
```cmd
cd packages/hoppscotch-backend
pnpm run test
```

test(backend): account for race conditions in `verifyMagicLinkTokens` test suite

---

packages/hoppscotch-common/src/components/collections/ImportExport.vue
packages/hoppscotch-common/src/components/importExport/Base.vue
packages/hoppscotch-common/src/components/importExport/ImportExportList.vue
packages/hoppscotch-common/src/helpers/import-export/import/postman.ts

Closes HFE-730
- This PR adds support for handling http GraphQL requests by formatting the query and variables properly.
- Also disables imports for users having no write access in a teams

feat: add support to export http postman graphql request

---

packages/hoppscotch-common/src/helpers/curl/curlparser.ts
packages/hoppscotch-common/src/helpers/curl/sub_helpers/cookies.ts

Closes HFE-805 #4961
This pull request addresses an issue with the handling of cookies in cURL requests. The current behavior fails when cookies are set using the `-b` option without the appropriate `-H` header. This fix ensures that cookies are correctly processed.

feat(common): enhanced cookie parsing from curl arguments

---

packages/hoppscotch-common/src/platform/std/kernel-interceptors/extension/index.ts

This addresses an issue with the extension interceptor where response metadata (timing metrics and size calculations) was missing from the response object.
This change is an isolated addition since the extension interceptor has become somewhat "detached" from the kernel capabilities over time, while other interceptors were able to be evolved with architecture.
This fix helps bridge that gap without requiring substantial refactoring of the extension interceptor implementation.
Closes HFE-810
The following screenshot shows `extension` interceptor in the upper section at `localhost` (patch) with correct response metadata, followed by the current deployed version with missing response meta.

fix(common): extention interceptor response meta

---

packages/hoppscotch-common/src/components/smart/EnvInput.vue

In the current version of Hoppscotch, the show/hide button for viewing a secret value in the settings dialog box is shoved out of view by the content of the secret value input box. This change enhances the experience by keeping the button in its original location, while not preventing the value from being scrollable so the entire value can be viewed as it in the current state.

chore: truncate long secret environment variables

---

packages/hoppscotch-backend/package.json

**What's changed**
Fixed an issue where the templates folder wasn't being copied to the /dist/backend directory during ARM builds in GitHub Actions. Added the necessary configuration in package.json to ensure the templates are included in the deployment.
**Notes to reviewers**
Nil
**How to test**
1. Run the GitHub Actions workflow for ARM build
2. Verify the templates folder is present in the /dist/backend directory

fix: account for `templates` directory in ARM images

---

packages/hoppscotch-common/locales/es.json

- Add missing translations for the settings section
- Fix key names to ensure translations are displayed correctly.

chore(i18n): update `es` translation

---

.github/workflows/build-hoppscotch-desktop.yml

This PR adds an actions workflow pipeline for building and packaging the self-hosted Hoppscotch Desktop app across different platforms.
Platform supported right now are
- Windows x86_64 (`msi`)
- MacOS x64 and ARM64 (`dmg`)
- Linux x86_64 (`.deb`, `AppImage`)
The workflow can be triggered either automatically when a new release is created or manually through workflow dispatch.
| Dispatch | Runners |
| --- | --- | 
| ![image](https://github.com/user-attachments/assets/f259f8fa-d429-48f7-b366-5c350b9b6255) | ![image](https://github.com/user-attachments/assets/7b007f6f-84f8-4773-925c-03238b8e4415) |
| Artifacts | Files |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/e3020032-db5b-4544-af70-134ac8bba274) | ![image](https://github.com/user-attachments/assets/d5e9eb56-cc96- …

feat(infra): desktop aio build workflow pipeline

---

packages/hoppscotch-desktop/plugin-workspace/tauri-plugin-appload/src/ui/windows/posit.rs
packages/hoppscotch-desktop/src-tauri/Cargo.lock
pnpm-lock.yaml

This adds version checking before using Windows 11-specific DWM APIs.
Closes HFE-821
The desktop app crashes on startup on older Windows versions (pre-Windows 11) due to unsupported DWM API calls for dark mode and caption styling.
According to docs at https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/ne-dwmapi-dwmwindowattribute, both `DWMWA_USE_IMMERSIVE_DARK_MODE` and `DWMWA_CAPTION_COLOR` attributes are only supported starting with Windows 11 Build 22000.
> DWMWA_USE_IMMERSIVE_DARK_MODE: [...] This value is supported starting
> with Windows 11 Build 22000"
and
> DWMWA_CAPTION_COLOR: [...] This value is supported starting
> with Windows 11 Build 22000.
See https://github.com/hoppscotch/hoppscotch/discussions/4984 for more details, for reports of app crashing immediately on …

fix(desktop): add win version checks for DWM attr api

---

packages/hoppscotch-desktop/plugin-workspace/tauri-plugin-appload/Cargo.lock
packages/hoppscotch-desktop/plugin-workspace/tauri-plugin-appload/Cargo.toml
packages/hoppscotch-desktop/plugin-workspace/tauri-plugin-appload/src/storage/error.rs
packages/hoppscotch-desktop/plugin-workspace/tauri-plugin-appload/src/storage/layout.rs
packages/hoppscotch-desktop/plugin-workspace/tauri-plugin-appload/src/storage/manager.rs
packages/hoppscotch-desktop/src-tauri/Cargo.lock
pnpm-lock.yaml

Appload fails to load with a "Storage full" error despite having sufficient disk space. This was caused by a unit mismatch assumption where the `sys-info` crate returns disk space in kilobytes instead of previously assumed bytes.
This PR replace `sys-info v0.9.1` with the more actively maintained `sysinfo 0.34.2` which does return size of the disk in bytes.
| Expected | Before | After |
| --- | --- | --- |
| <img width="425" alt="fix-desktop-du-expected" src="https://github.com/user-attachments/assets/8a084ee7-70d0-4595-957d-d70242ee3a77" /> | <img width="1510" alt="fix-desktop-du-before" src="https://github.com/user-attachments/assets/c28d6cfd-a119-4fbb-8727-ca27b1e77b49" /> | <img width="1510" alt="fix-desktop-du-after" src="https://github.com/user-attachments/assets/8dd39fd3-cf4b-4681-b …

fix(desktop): disk space detection

---

.env.example

Adding this to example will support selfhost proxy to use VITE_PROXYSCOTCH_ACCESS_TOKEN correctly.
Closes # 
https://github.com/hoppscotch/hoppscotch/issues/3557
In vite.config.ts: envPrefix: process.env.HOPP_ALLOW_RUNTIME_ENV ? "VITE_BUILDTIME_" : "VITE_"
And in prod.Dockerfile: ENV HOPP_ALLOW_RUNTIME_ENV=true
If VITE_PROXYSCOTCH_ACCESS_TOKEN is not available on .env.example then VITE_PROXYSCOTCH_ACCESS_TOKEN is never read.

chore: add VITE_PROXYSCOTCH_ACCESS_TOKEN to .env.example

---

pnpm-lock.yaml

This PR fixes stale lockfile affecting `plugin-relay` binding

fix: stale lockfile on rebase

---

packages/hoppscotch-agent/package.json
packages/hoppscotch-agent/src-tauri/Cargo.lock
packages/hoppscotch-agent/src-tauri/Cargo.toml
packages/hoppscotch-agent/src-tauri/tauri.conf.json
packages/hoppscotch-agent/src-tauri/tauri.portable.conf.json
packages/hoppscotch-desktop/plugin-workspace/relay/src/response.rs
packages/hoppscotch-desktop/plugin-workspace/tauri-plugin-relay/Cargo.lock
packages/hoppscotch-desktop/src-tauri/Cargo.lock
packages/hoppscotch-desktop/src-tauri/src/lib.rs
pnpm-lock.yaml

This PR addresses an issue where headers with different capitalizations were not being matched during `Content-Type` detection due to HTTP/2.0 middlewares (like Istio's) normalizing headers to lowercase according to RFC 7540.
Closes HFE-832
The new method iterates over all headers with `headers.iter()` and then converts header keys to lowercase before comparison. Also fixes log guard ordering, to capture plugin init logs and prevent server from dropping early.

fix(relay): better matching for `content-type` detection

---

packages/hoppscotch-common/src/components/lenses/renderers/HTMLLensRenderer.vue
packages/hoppscotch-common/src/components/lenses/renderers/PDFLensRenderer.vue
packages/hoppscotch-common/src/components/lenses/renderers/XMLLensRenderer.vue

Closes #4265 
Added extension for downloaded filename 
- [] Completed

feat: add file extensions to response exports

---

package.json
pnpm-lock.yaml

This PR addresses security vulnerabilities (CVEs) in the insomnia-importers package, which were primarily due to its dependency on an outdated version of xmldom. To resolve this, I have to overridden the existing `apiconnect-wsdl` package used in insomnia-importer to upgrade the xmldom to @xmldom/xmldom.
First, I have upgraded the apiconnect-wsdl package which introduced the @xmldom/xmldom(^v0.8.5) package. Then upgrade it to latest(v0.9.8) to resolve the security issues from it.
https://github.com/xmldom/xmldom/security/advisories/GHSA-crh6-fp67-6883

feat: update xmldom version to xmldom/xmldom0.9.8

---

packages/hoppscotch-common/src/components/app/Header.vue
packages/hoppscotch-common/src/components/teams/Edit.vue
packages/hoppscotch-common/src/components/teams/Invite.vue
packages/hoppscotch-common/src/components/teams/index.vue
packages/hoppscotch-common/src/composables/graphql.ts
packages/hoppscotch-common/src/platform/ui.ts

This pull request introduces support for custom UI components for team invite and edit functionality, improved GraphQL query behavior. Below is a summary of the most important changes grouped by theme:
* Replaced hardcoded role strings (`'OWNER'`, `'EDITOR'`, `'VIEWER'`) with the `TeamMemberRole` enum for better type safety and readability. (`packages/hoppscotch-common/src/components/teams/Edit.vue`, [[1]](diffhunk://#diff-cb9c050f11dee81270e534eb989340c0a9070a070334fdebbb796fc813a8e4f5L104-R107) [[2]](diffhunk://#diff-cb9c050f11dee81270e534eb989340c0a9070a070334fdebbb796fc813a8e4f5L117-R123) [[3]](diffhunk://#diff-cb9c050f11dee81270e534eb989340c0a9070a070334fdebbb796fc813a8e4f5L130-R139)
These changes collectively enhance the flexibility, maintainability, and performance of the team …

feat(common): platform ui definition for team edit and invite

---

packages/hoppscotch-common/src/helpers/curl/curlparser.ts

Closes #5013
If the method is POST, the body is non-empty, and no Content-Type is explicitly provided, default to "application/x-www-form-urlencoded".
This aligns with curl's documented default behavior: https://everything.curl.dev/http/post/content-type.html

fix: default Content-Type to x-www-form-urlencoded when importing curl POST with body

---

packages/hoppscotch-common/src/helpers/functional/process-request.ts

These changes fix URL parameter encoding behavior based on how parameter values are encoded, those based on the `ENCODE_MODE` setting.
Closes HFE-833
Closes #4971
Context: We encode query parameter values according to [RFC 3986 Section 3.4](https://datatracker.ietf.org/doc/html/rfc3986#section-3.4), query components should be encoded, which is controlled by `ENCODE_MODE` setting.
When the encoding mode was set to "enable", a parameter value like `{second-testing}` would be encoded to `%257Bsecond-testing%257D` instead of `%7Bsecond-testing%7D`.
This occurred because of a combination of the custom encoding logic and the browser's native `searchParams.append()` method.
As in [RFC 3986#2.4](https://datatracker.ietf.org/doc/html/rfc3986#section-2.4), percent-encoding is non-idempotent. When …

fix(common): url and param encoding

---

package.json
pnpm-lock.yaml

`@xmldom/xmldom: 0.9.8` was introduced a breaking change for some other dependent packages. So, downgraded to `0.8.10` version for stability.
Please test the insomnia-importers package thoroughly, as it might be impacted by this change. Expecting, everything will work as expected.

hotfix: pin `xmldom` to `v0.8.10` addressing breaking change

---

packages/hoppscotch-backend/src/main.ts

Closes #4199
This pull request addresses the issue of identical CORS settings being used in both development and production environments. It refines the logic in the backend to differentiate the CORS configuration based on the environment (development vs. production).
- In development (`if` block), more permissive CORS settings are applied for easier testing.
- In production (`else` block), restricted CORS settings are applied to enhance security.
- The changes maintain backward compatibility by ensuring the development environment retains flexibility while securing the production environment.
- Tested locally to ensure proper CORS behavior for both environments.
- Let me know if additional changes are needed, or if there are any specific configurations you'd like to refine further!

chore(backend): configure CORS for development and production environments

---

docker-compose.deploy.yml
docker-compose.yml

The current health check block doesn't check for errors or exceptions that might occur during the request.
Here is the modified code for a 'precise health check' :
healthcheck:
test: [ "CMD", "curl", "-f", "-s", "-o", "/dev/null", "-w", "%{http_code}", "http://localhost:80" ]
interval: 2s
timeout: 10s
retries: 30
Closes #

chore: improve healthcheck configuration for AIO container

---

docker-compose.deploy.yml
packages/hoppscotch-backend/src/user-collection/user-collections.model.ts

Closes HSB-514
This PR performs a cleanup by removing an unused GraphQL enum named `CollType`.
No functional changes introduced. This is purely a cleanup PR to keep the codebase tidy.

HSB-514 refactor: remove unused `CollType` GQL enum

---

packages/hoppscotch-common/src/modules/i18n.ts

This pull request introduces functionality to allow dynamic registration and merging of additional i18n messages for specific locales in the `i18n` module. The most significant changes include the addition of a mechanism to register and merge external translations with existing locale messages and an enhancement to apply these additional messages when the app language changes.

feat(common): add support for registering and merging additional locale messages

---

packages/hoppscotch-desktop/src-tauri/Cargo.lock
packages/hoppscotch-desktop/src-tauri/Cargo.toml
packages/hoppscotch-desktop/src-tauri/src/lib.rs
packages/hoppscotch-desktop/src-tauri/src/logger.rs
packages/hoppscotch-desktop/src-tauri/src/main.rs

This changes how logging is initialized and managed, fixing an issue where some logs were missing from `io.hoppscotch.log` files.
Closes HFE-838
Basically some debug log messages just weren't appearing in the logs. This was quite odd because other debug messages from the same module were appearing correctly.
In Tauri app, logging is tricky... mainly because of the application lifecycle. The application starts in `main.rs` before any Tauri-specific functionality is available. Having log sinks setup at `main` would be great, but we also need file-based logging that requires the Tauri AppHandle to determine the right log file paths.
There is a "theoretical" way to achieve this, to simply initialize logging twice:
```rust
// In main.rs - Basic console logging
tracing_subscriber::registry() …
```

feat(desktop): complete lifecycle logs

---

packages/hoppscotch-desktop/plugin-workspace/tauri-plugin-appload/Cargo.lock
packages/hoppscotch-desktop/plugin-workspace/tauri-plugin-appload/Cargo.toml
packages/hoppscotch-desktop/plugin-workspace/tauri-plugin-appload/src/storage/manager.rs
packages/hoppscotch-desktop/plugin-workspace/tauri-plugin-appload/src/ui/windows/posit.rs
packages/hoppscotch-desktop/src-tauri/Cargo.lock
pnpm-lock.yaml

The storage init was failing on Windows when checking available disk space due to verbatim paths (also known as extended-length paths) returned by `std::fs::canonicalize()`.
Windows has two path formats: traditional paths limited to 260 characters, and extended-length paths (prefixed with `\\?\`) that support longer paths.
While Rust's `std::path` is "platform-independent", Windows-specific behavior still requires special consideration for these extended-length paths.
This fixes that.
Closes HFE-839
Closes #4859
Basically the issue occurred because `std::fs::canonicalize()` on Windows may return extended-length paths when:
1. The path exceeds 260 characters
2. The path contains certain special characters
3. The system is configured to use extended paths (fairly common on Win 10/11)
The …

fix(desktop): verbatim path handling in disk resolution

---

packages/hoppscotch-common/src/kernel/store.ts
packages/hoppscotch-common/src/platform/std/kernel-interceptors/agent/index.ts
packages/hoppscotch-common/src/platform/std/kernel-interceptors/agent/store.ts
packages/hoppscotch-common/src/platform/std/kernel-interceptors/extension/store.ts
packages/hoppscotch-common/src/platform/std/kernel-interceptors/native/index.ts
packages/hoppscotch-common/src/platform/std/kernel-interceptors/native/store.ts
packages/hoppscotch-common/src/platform/std/kernel-interceptors/proxy/store.ts
packages/hoppscotch-kernel/README.md
packages/hoppscotch-kernel/package.json
packages/hoppscotch-kernel/src/store/impl/desktop/v/1.ts
packages/hoppscotch-kernel/src/store/impl/web/v/1.ts
packages/hoppscotch-kernel/src/store/v/1.ts

This adds a multi-store architecture to the kernel storage module, adding ability to manages persistent data across execution environments.
It also bubbles up the storage realm setup from library level to consumer API level, basically moving
```typescript
const STORE_PATH = `${window.location.host}.hoppscotch.store`
```
from `hoppscotch-kernel/store` to `hoppscotch-common/kernel/store`
This basically allows for concurrent access to multiple isolated storage instances, each addressable by a distinct path, and this also addresses an architectural limitation in the current implementation, which relies on a singleton pattern plus a constant.
Closes HFE-877
There are no functional changes so we only need to make sure everything works as expected, especially the store operation.
The existing …

feat(kernel): multi-instance support for `store`

---

packages/hoppscotch-cli/src/utils/pre-request.ts
packages/hoppscotch-common/src/helpers/utils/EffectiveURL.ts

Closes #5064
This pull request addresses issue #5084 by modifying the effective request functions to include the request body when signing requests with AWS V4. This enhancement ensures that the request signature is generated accurately, taking into account the content of the request body, which is crucial for the integrity and security of the requests made to AWS services.

fix: include request body to AWS V4 signer in effective request functions

---

packages/hoppscotch-desktop/README.md

This PR adds detailed minimum system requirements for all supported platforms to help users understand compatibility requirements for installing the desktop app.
The requirements section covers Windows 10 1803+/Windows 11, macOS 10.15+ with both arch (Intel and Apple Silicon) support, and Linux distro with special emphasis on GLIBC 2.38+ requirements.
Also the documentation specifically goes over why Ubuntu 24.04 is the recommended distro - mainly due to its inclusion of WebKit2GTK version 2.44.0-2, which gets us relatively stable interaction between WebKit, UI libraries, Mesa drivers, and Wayland displays. 
Also added known workarounds for users experiencing display issues on Wayland systems.
Plus it restructures sections to improve clarity, consolidating instructions for both Community …

docs(desktop): add minimum system requirements

---

packages/hoppscotch-common/locales/en.json

Add a new translation string for `assign`

chore(common): improved i18n strings

---

packages/hoppscotch-common/src/components/importExport/ImportExportSteps/UrlImport.vue
packages/hoppscotch-common/src/helpers/functional/json.ts

Closes HFE-844 #5030
Update the URL import logic to support parsing response bodies in both JSON and YAML formats. And import from URL by both JSON and YAML.

feat(common): support importing OpenAPI YAML definitions from URL

---

packages/hoppscotch-data/src/rest/index.ts

Adjust the import statements in the REST module for consistency and clarity.

fix: correct import order for HoppRESTAuth

---

packages/hoppscotch-cli/src/utils/request.ts
packages/hoppscotch-common/src/components/environments/my/Details.vue
packages/hoppscotch-common/src/components/environments/teams/Details.vue
packages/hoppscotch-common/src/helpers/editor/extensions/HoppEnvironment.ts
packages/hoppscotch-common/src/helpers/import-export/export/environment.ts
packages/hoppscotch-common/src/helpers/import-export/import/insomniaEnv.ts
packages/hoppscotch-common/src/helpers/import-export/import/postmanEnv.ts
packages/hoppscotch-common/src/helpers/utils/environments.ts
packages/hoppscotch-common/src/newstore/environments.ts
packages/hoppscotch-common/src/services/inspection/inspectors/environment.inspector.ts
packages/hoppscotch-data/src/environment/index.ts
packages/hoppscotch-data/src/environment/v/2.ts

This PR fixes the issue where current value is empty on migration.

fix: fill current value to existing value

---

healthcheck.sh

Fixes healthcheck.sh not considering the value of HOPP_AIO_ALTERNATE_PORT, thus reporting unhealthy for any custom port that differs from 80
Uses the port set in HOPP_AIO_ALTERNATE_PORT (defaults to 80) for the healthcheck to prevent wrongfully reporting unhealthy status when HOPP_AIO_ALTERNATE_PORT set to custom port
Tested successfully with the latest version of AIO Container (at time of pull request was 2025.5.1)

fix: use `HOPP_AIO_ALTERNATE_PORT` in healthcheck

---

packages/hoppscotch-common/src/components/http/Request.vue

This PR adds color styling to the selected HTTP request type to make the color consistent with:
- The color of the request type in the tab
- The color of the request type in the dropdown selector
Before:
After:
Closes #5112 
Added a color style to the `input` element of `HoppSmartSelectWrapper` based on the active REST request method type

feat(common): change REST method text color based on selected method

---

packages/hoppscotch-desktop/src/types/index.ts
packages/hoppscotch-desktop/src/utils/updater.ts
packages/hoppscotch-desktop/src/views/Home.vue

This fixes a Windows-specific issue where the updater would hang during download and installation.
The cause was file I/O operations called from within progress callbacks conflicting with Windows' "stricter" fs behavior during concurrent ops.
This move that to an in-memory tracking with periodic polling, removing all disk writes from the download callback to only for actual final commits.
Closes HFE-892
Closes #5038
This is a Windows-specific thing, doesn't affect Mac/Linux functionality.
The core change is moving from synchronous progress persistence to asynchronous polling-based updates.
Progress tracking remains fully functional with 100ms polling intervals for just a bit smooth UI updates.
The existing implementation called `saveUpdateState()` directly within the updater's progress …

fix(desktop): in-memory update progress polling

---

packages/hoppscotch-agent/src-tauri/Cargo.lock
packages/hoppscotch-agent/src-tauri/Cargo.toml
packages/hoppscotch-agent/src-tauri/src/error.rs
packages/hoppscotch-agent/src-tauri/src/lib.rs
packages/hoppscotch-agent/src-tauri/src/logger.rs
packages/hoppscotch-agent/src-tauri/src/main.rs
packages/hoppscotch-agent/src-tauri/src/tray.rs

This adds a file-based logging system with size-based rotation to the Hoppscotch Agent.
It essentially redirects existing diagnostic to size-based rotating files for troubleshooting environment-specific issues.
Closes HFE-897
Agent currently lacks a persistent logging mechanism in production environments. Logs are only available through the development mode console. Mainly aiming to understand errors in specific environments that can't be reproduced in our testing setups.
This implementation uses the tracing ecosystem (`tracing`, `tracing_subscriber`, `tracing_appender`) along with `file_rotate` to create log files in the platform's log directory.
The logs are automatically rotated when they reach 10MB, with a maximum of 5 files retained.
Thinking `10 * 5 MB` just like the desktop app is …

feat(agent): file-based logs with rotation

---

packages/hoppscotch-common/src/components/environments/Selector.vue
packages/hoppscotch-common/src/components/environments/my/index.vue
packages/hoppscotch-common/src/components/environments/teams/Details.vue
packages/hoppscotch-common/src/components/environments/teams/index.vue

Closes #5148 
This PR fixes the bug with team environment where user with `VIEWER` access could not save current environment value. 
Also enabled environment search in empty cases with proper placeholder in place.

fix: team environment user access bug

---

packages/hoppscotch-agent/package.json
packages/hoppscotch-agent/src-tauri/Cargo.lock
packages/hoppscotch-agent/src-tauri/Cargo.toml
packages/hoppscotch-agent/src-tauri/tauri.conf.json
packages/hoppscotch-agent/src-tauri/tauri.portable.conf.json

This PR bumps Hoppscotch Agent to `v0.1.11`.

chore(agent): version bump

---

packages/hoppscotch-common/src/components/collections/Properties.vue
packages/hoppscotch-common/src/components/collections/index.vue

Closes #3957 
Access tokens are not propagated to child requests when using `OAuth2.0 authorization`. This behavior is observed for `Team Workspaces` only.
- During the callback from auth provider to the Hoppscotch application (at route `/oauth`), `collection.id` is not preserved
- As the variable `path` is preserved, we use that to deduce the value of `collectionId`
**Video demonstrating the fix:**
https://github.com/user-attachments/assets/dd6524e2-b19b-4101-ac34-22836865d9e9
Key things to note in the video:
- Access token now remains preserved in collection properties dialog box after clicking on the save button
- Auth type of inherit on a child request would now successfully point to this access token

fix: auth tokens not propagating to child requests

---

packages/hoppscotch-common/src/helpers/teams/TeamEnvironmentAdapter.ts

This PR fixes the bug with migrating team environments leading to empty values. Now the fetched team environment variables is parsed to latest new environment schema.
Related to #5104.

fix: team env not migrating in edge cases

---

packages/hoppscotch-common/src/components/environments/my/Details.vue
packages/hoppscotch-common/src/components/environments/teams/Details.vue
packages/hoppscotch-common/src/helpers/RequestRunner.ts
packages/hoppscotch-common/src/helpers/editor/extensions/HoppEnvironment.ts
packages/hoppscotch-common/src/helpers/utils/environments.ts
packages/hoppscotch-common/src/newstore/environments.ts

Closes HFE-890
This PR updates the environment usage flow where the initial environment variable value is used as the environment value if current value is empty at the time of request run without persisting the value.

chore: use initial value in runtime if current value is empty

---

.github/ISSUE_TEMPLATE/--bug-report.yaml

This PR simplifies the bug report template by combining similar sections into common ones with unified fields, and also reorders required information at the top.
This also fixes an issue where section requiring log and screenshot didn't show the file upload section causing confusion, see https://github.com/hoppscotch/hoppscotch/issues/5134#issue-3124592715.
| --- | --- |
| ![image](https://github.com/user-attachments/assets/2b382a81-a24b-407e-9e45-835b5afc368e) | ![image](https://github.com/user-attachments/assets/c0be0972-76f2-4c90-bb67-ffe073f62c1b) |

docs: unified fields for bug report template

---

packages/hoppscotch-selfhost-web/src/main.ts

This adds drag/drop event listeners to prevent Tauri's WebView from opening files when users accidentally drop files outside of intended drop zone.
This fixes that while preserving drag/drop functionality in rest of the inputs like vuedraggable components, file uploads, and code editors (CodeMirror), "browse", etc.
Closes HFE-886
Closes #5089
This occurred because Tauri's WebView inherits standard browser behavior of opening dropped files when they land outside of components designed to handle them.
The current impl uses event listeners that simply skip legitimate drop targets via selectors. The allowed list is made by checking against known patterns from the codebase, things like vuedraggable with `.draggable-content` and `[draggable="true"]`, file upload inputs using …

fix(desktop): prevent navigation on file drops

---

packages/hoppscotch-common/src/helpers/kernel/common/content.ts

Closes HFE-905 #5159
This PR fixes the issue of auto unescaping UTF-8 in the request body. Maintain original payload integrity in HTTP request.

fix(common): auto unescape utf-8 issue in the request body

---

packages/hoppscotch-backend/src/auth/strategies/github.strategy.ts
packages/hoppscotch-backend/src/auth/strategies/google.strategy.ts
packages/hoppscotch-backend/src/auth/strategies/jwt.strategy.ts
packages/hoppscotch-backend/src/auth/strategies/microsoft.strategy.ts
packages/hoppscotch-backend/src/auth/strategies/rt-jwt.strategy.ts
packages/hoppscotch-backend/src/errors.ts

refactor(auth): enhance GithubStrategy with type safety, error handling, and secure validation
- Added explicit typing for accessToken, refreshToken, and profile
- Introduced defensive checks for missing GitHub email
- Wrapped logic in try-catch for robust error handling
- Ensured use of Passport's `done()` callback
- Improved future safety with optional chaining and explicit string config values

refactor(backend): enhance auth strategies with type safety and better error handling

---

packages/hoppscotch-common/package.json
packages/hoppscotch-desktop/package.json
packages/hoppscotch-desktop/plugin-workspace/tauri-plugin-appload/pnpm-lock.yaml
packages/hoppscotch-desktop/plugin-workspace/tauri-plugin-relay/pnpm-lock.yaml
packages/hoppscotch-desktop/src-tauri/Cargo.lock
packages/hoppscotch-desktop/src-tauri/Cargo.toml
packages/hoppscotch-kernel/package.json
pnpm-lock.yaml

This PR aligns `plugin-workspace` hashes post `typescript` bump to `v:^5.8.3`.

chore(desktop): update `typescript` bump hash

---

packages/hoppscotch-common/assets/scss/styles.scss
packages/hoppscotch-common/src/helpers/editor/extensions/HoppEnvironment.ts
packages/hoppscotch-common/src/helpers/editor/extensions/HoppPredefinedVariables.ts

This PR fixes the alignment issue with tooltips where the flex direction was set to column for env tooltip but the other tooltip was not accounted.

fix: tooltip alignment update

---

packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/helpers/shortcuts.ts

This adds tab navigation shortcuts to the shortcuts help dialog for desktop users and conditionally shows them only in desktop mode.
| Web app | Desktop app |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/97c15625-b323-4bc0-9382-78cf1fd78ae4) | ![image](https://github.com/user-attachments/assets/4211aa82-2b24-4472-bc30-94b94accda9d) |
The shortcuts help now includes a "Tabs" section with all available tab management shortcuts, but only displays them when running in desktop kernel mode to avoid confusing web users with non-functional shortcuts.
Closes FE-917
The desktop app already had functional tab navigation shortcuts, but they weren't documented in the app's shortcuts help dialog (accessible via `?` or `Cmd/Ctrl+/`). This made the shortcuts less discoverable for …

feat(desktop): tab shortcuts discoverability

---

packages/hoppscotch-common/src/helpers/import-export/import/postman.ts

Closes FE-916 #4452 
This PR fixes the bug when importing a response body with a Unicode which fail while saving with Prisma.[[ref](https://dba.stackexchange.com/questions/115029/unicode-error-with-u0000-on-copy-of-large-json-file-into-postgres)]
The Unicode is now replaced with an empty string while importing a request.

fix: unicode error in postman import

---

packages/hoppscotch-common/src/components.d.ts
packages/hoppscotch-common/src/components/graphql/Response.vue
packages/hoppscotch-common/src/components/graphql/ResponseMeta.vue
packages/hoppscotch-common/src/helpers/graphql/connection.ts

Closes HFE-775 #4395
What’s changed
•	Added HttpResponseMeta to Response.vue to handle GraphQL responses for http.
•	Commented out the redundant AppShortcutsPrompt in Response.vue since HttpResponseMeta now covers its functionality.
•	Modified connection.ts in helpers/graphql to format the data for HttpResponseMeta.
Notes to reviewers
•	The AppShortcutsPrompt was redundant with HttpResponseMeta, so it’s only commented out for now to preserve the original logic.
•	Let me know if the data handling in connection.ts for HttpResponseMeta needs any adjustments.

feat(common): add status code and additional metadata to GraphQL responses

---

packages/hoppscotch-common/src/services/tab/__tests__/tab.service.spec.ts

This adds test coverage for the tab navigation methods added in FE-907
the native tab keyboard shortcuts implementation.
Closes FE-909
The recently implemented desktop tab keyboard shortcuts added new tab
navigation methods to the `TabService` class (`goToNextTab()`,
`goToPreviousTab()`, `goToFirstTab()`, `goToLastTab()`,
`goToTabByIndex()`, and `reopenClosedTab()`). These methods lacked
corresponding test coverage.
Tab Navigation Tests:
- `goToNextTab()` - Verifies cycling through tabs in forward direction with wrap-around behavior
- `goToPreviousTab()` - Verifies cycling through tabs in reverse direction with wrap-around behavior
- `goToFirstTab()` - Verifies navigation to the leftmost tab regardless of current position
- `goToLastTab()` - Verifies navigation to the rightmost tab …

test(common): coverage for desktop tab navigation

---

packages/hoppscotch-sh-admin/src/composables/useOnboardingConfigHandler.ts

This PR fixes the issue in SMTP where submitting the config failed because some of the required field didn't get submitted to the BE.

fix: onboarding flow smtp bug

---

packages/hoppscotch-common/locales/es.json

Fixed typo in the spanish locale

fix: resolve typo in `i18n` string

---

packages/hoppscotch-common/src/components/http/RequestTab.vue
packages/hoppscotch-common/src/components/smart/EnvInput.vue

Closes #5304 
This PR fixes an issue in `SmartEnvInput` where the environment variables were not being populated in the context. The root cause was that the `RequestOption` component was not correctly propagating the env prop.
With this fix, we now check if the `env` array is empty and populate `envVars` accordingly to ensure the expected environment context is applied.

fix: `SmartEnvInput` environment context bug

---

packages/hoppscotch-agent/package.json
packages/hoppscotch-agent/src-tauri/Cargo.lock
packages/hoppscotch-agent/src-tauri/Cargo.toml
packages/hoppscotch-agent/src-tauri/tauri.conf.json
packages/hoppscotch-agent/src-tauri/tauri.portable.conf.json

Updates agent to version 0.1.12 with relay dependency that includes expanded MIME type support for file uploads.
Follows #5306

chore(agent): bump version to `0.1.12`

---

packages/hoppscotch-common/src/components/importExport/ImportExportList.vue

This PR improves the visual spacing of the exporter buttons in the import/export modal.
•	Added margin-top to the exporter button list in ImportExportList.vue to provide clearer separation from the importers section.
•	No functional changes, UI only.
•	Aligns with Hoppscotch design consistency for modal layouts.
**Before**
**After**

fix: (import-export) add spacing above exporter buttons

---

packages/hoppscotch-common/src/helpers/editor/themes/baseTheme.ts

This pull request introduces JSON fold summaries in the response viewer. When collapsing objects or arrays, the placeholder now shows how many fields or items they contain. For example, objects display as { … } (n fields) and arrays as [ … ] (n items).
This makes it easier to scan large JSON responses without expanding everything, giving a clearer and faster overview (similar to what Insomnia provides).
For styling, the summary currently uses a light opacity and italic font. If the font style or color doesn’t feel consistent with the rest of the UI, we can easily adjust it through the jsonFoldSummaryTheme.
Fixes #5332

feat: add structured JSON fold indicators in response viewer

---

packages/hoppscotch-common/src/components/app/Inspection.vue
packages/hoppscotch-common/src/components/collections/TeamCollections.vue
packages/hoppscotch-common/src/components/collections/index.vue
packages/hoppscotch-common/src/components/importExport/ImportExportSteps/AllCollectionImport.vue
packages/hoppscotch-common/src/components/smart/EnvInput.vue
packages/hoppscotch-common/src/helpers/backend/gql/subscriptions/TeamCollectionMoved.graphql
packages/hoppscotch-common/src/helpers/collection/collection.ts
packages/hoppscotch-common/src/helpers/editor/extensions/HoppEnvironment.ts
packages/hoppscotch-common/src/helpers/import-export/import/openapi/example-generators/v2.ts
packages/hoppscotch-common/src/helpers/teams/TeamCollection.ts
packages/hoppscotch-common/src/helpers/teams/TeamCollectionAdapter.ts
packages/hoppscotch-common/src/helpers/types/HoppInheritedProperties.ts
packages/hoppscotch-common/src/helpers/utils/inheritedCollectionVarTransformer.ts
packages/hoppscotch-common/src/newstore/collections.ts
packages/hoppscotch-common/src/newstore/environments.ts
packages/hoppscotch-common/src/services/inspection/index.ts
packages/hoppscotch-common/src/services/inspection/inspectors/environment.inspector.ts
packages/hoppscotch-common/src/services/persistence/validation-schemas/index.ts

Closes FE-992
This PR fixes some edge cases and bug's with collection variables

fix: handle edge cases and bugs in collection variables

---

packages/hoppscotch-backend/src/team/team.service.spec.ts
packages/hoppscotch-backend/src/team/team.service.ts
packages/hoppscotch-common/locales/en.json
packages/hoppscotch-common/src/helpers/backend/types/TeamName.ts

Closes FE-943 #5271 
This PR updates the shared workspace name validation to check for a non-empty string instead of enforcing a minimum length of 6 characters.

feat: allow non-empty shared workspace names

---

prod.Dockerfile

This PR updates the [prod.Dockerfile](vscode-file://vscode-app/c:/Users/LELUU2/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html) to explicitly install npm alongside nodejs in the Alpine base image. 
On Alpine, nodejs does not include npm by default, which caused build failures when running npm install -g .... 
The fix adds npm to the apk add command, ensuring the Node.js environment is complete and compatible with subsequent global package installations.
Closes # 
https://github.com/hoppscotch/hoppscotch/issues/5396
Add npm to the apk add --no-cache nodejs npm curl tini bash command in the Node.js base stage.
This resolves /bin/sh: npm: not found errors during Docker builds in CI and local environments.

fix: ensure npm is installed for Node.js base image

---

packages/hoppscotch-common/src/services/oauth/flows/authCode.ts
packages/hoppscotch-common/src/services/oauth/flows/clientCredentials.ts
packages/hoppscotch-common/src/services/oauth/flows/implicit.ts
packages/hoppscotch-common/src/services/oauth/flows/password.ts
packages/hoppscotch-common/src/services/oauth/utils.ts
packages/hoppscotch-data/src/rest/index.ts
packages/hoppscotch-data/src/rest/v/15/auth.ts

Closes FE-1004
This pull request refactors the OAuth flow parameter schemas in the service layer to use shared, centralized schemas from `@hoppscotch/data`. It replaces locally-defined schemas with the imported ones, omitting unnecessary fields and ensuring required arrays for service logic. This change improves maintainability and consistency across the codebase.

refactor: streamline duplicated advanced param type definitions for oauth grant types

---

packages/hoppscotch-agent/package.json
packages/hoppscotch-agent/src-tauri/Cargo.lock
packages/hoppscotch-agent/src-tauri/Cargo.toml
packages/hoppscotch-agent/src-tauri/tauri.conf.json
packages/hoppscotch-agent/src-tauri/tauri.portable.conf.json

Bump agent to version `v0.1.14` with `relay` dependency changes as per https://github.com/hoppscotch/hoppscotch/pull/5394, and direct dependency change according to https://github.com/hoppscotch/hoppscotch/pull/5402.

chore(agent): bump version to `0.1.14`

---

README.md
netlify.toml
packages/hoppscotch-common/src/components/app/Share.vue
packages/hoppscotch-common/src/services/spotlight/searchers/general.searcher.ts

This PR updates references from the deprecated [twitter.com](http://twitter.com) domain to the current [x.com](http://x.com) branding for consistency and to avoid user-facing legacy brand usage. The change is mechanical (string/domain replacement) and does not introduce functional logic changes.
Replaced all occurrences of `twitter.com` with `x.com` in:
- Documentation (README/markdown files)
-  Metadata/config files
- UI or footer/social link definitions
N/A

chore: replace all instances of `twitter.com` with `x.com`

---

packages/hoppscotch-common/src/components/environments/my/Details.vue
packages/hoppscotch-common/src/components/environments/teams/Details.vue
packages/hoppscotch-common/src/helpers/RequestRunner.ts
packages/hoppscotch-common/src/helpers/editor/extensions/HoppEnvironment.ts
packages/hoppscotch-common/src/helpers/utils/environments.ts
packages/hoppscotch-common/src/newstore/environments.ts
packages/hoppscotch-common/src/services/__tests__/secret-environment.service.spec.ts
packages/hoppscotch-common/src/services/persistence/validation-schemas/index.ts
packages/hoppscotch-common/src/services/secret-environment.service.ts

Closes #5430 
This PR fixes the bug where the secret initial variable value was getting synced to the server. Now the initial value is stored in the secret environment service just like the current environment value.
Previously, secret environment variable initial values were persisted and synced to the server alongside other environment data. This exposed sensitive bootstrap values that should remain local-only (similar to how secret current values are handled). This PR changes the handling so that both secret `currentValue` and `initialValue` are stored only in the local `SecretEnvironmentService` (backed by local storage) and are stripped from the synced environment payload.
Secret initial values were never separated from the canonical environment object before persistence/sync …

fix: prevent syncing secret variable initial values
